import {createServer} from 'node:http';
import {expect,start,stop,login,ok,call,sql,origin,out,t,dump,ready,instrument,randomUUID,env} from './harness.mjs';
const results=[],traces=[],runtime=[];let action='setup',calls=0,swapped=false;
const passage='A thoughtful student learns(learn) by building a steady learning(learn) routine through daily reading and discussion. Each morning the student reviews a few ideas, connects them with practical examples, and writes a short reflection. Friends later compare their observations, ask clear questions, and share useful explanations about what they learned(learn). This patient practice makes new knowledge easier to remember and apply with confidence.';
const provider=createServer(async(req,res)=>{if(req.url==='/models'){res.setHeader('content-type','application/json');res.end(JSON.stringify({data:[{id:'provider/integration',supported_parameters:['structured_outputs']}]}));return;}if(req.url!=='/chat/completions'){res.writeHead(404);res.end();return;}let body='';for await(const c of req)body+=c;calls++;const probe=JSON.parse(body).messages.some(m=>m.content.includes('fixed compatibility probe'));const candidate={passage:passage+(probe?' The group also discussed vulnerability(vulnerable) with empathy.':''),tags:['study'],targets:{learn:{entry_meaning:'gain knowledge through study',hint_phrase:'learning(learn) through learned(learn) examples while learning(learn)'}}};if(probe)candidate.targets.vulnerable={entry_meaning:'open to harm',hint_phrase:'vulnerable(vulnerable) communities'};res.setHeader('content-type','text/event-stream');res.end('data: '+JSON.stringify({choices:[{delta:{content:JSON.stringify(candidate)}}]})+'\n\ndata: [DONE]\n\n');});
await new Promise(r=>provider.listen(38082,'127.0.0.1',r));
const browser=await start(),admin=await browser.newContext(),user=await browser.newContext({timezoneId:'America/Los_Angeles',viewport:{width:1280,height:900}}),page=await user.newPage();instrument(page,runtime,()=>action);
async function test(id,name,fn){action=id;try{await fn();results.push({id,name,result:'PASS'});}catch(e){results.push({id,name,result:'FAIL',error:String(e)});await page.screenshot({path:new URL(id+'-failure.png',out).pathname,fullPage:true}).catch(()=>{});}dump('business-results.json',{results,localProviderCalls:calls,realProviderCalls:0});console.log(id,results.at(-1).result);}
async function raw(c,path,method,data,extra={}){const headers={origin,'sec-fetch-site':'same-origin',...extra};if(method!=='GET')headers['x-csrf-token']=(await ok(c,'/bootstrap')).csrf_token;return c.request.fetch(origin+'/api/v1'+path,{method,data,headers});}
const button=(key)=>page.getByRole('button',{name:t(key),exact:true});
const register=async(c,kind)=>(await ok(c,'/auth/register','POST',{username:'qa5_'+kind+'_'+Date.now(),password:env.ADMIN_PASSWORD,password_confirmation:env.ADMIN_PASSWORD,ui_locale:'en-US'})).actor.id;
let userId,modelId,ids=[],sessionId,submitted=[];
try{
 await login(admin);userId=await register(user,'review');
 const cred=await ok(admin,'/admin/openrouter-credential');await ok(admin,'/admin/openrouter-credential','PUT',{api_key:'qa5-local-fixture-key',confirmed:true,expected_revision:cred.revision});
 const m=await ok(admin,'/admin/models','POST',{display_name:'QA05 deterministic provider',description:'Isolated local fixture',openrouter_model_id:'provider/integration'});modelId=m.model.id;await ok(admin,'/admin/models/'+modelId+'/enable','POST',{expected_revision:m.revision});
 async function group(ids){const g=await ok(admin,'/admin/groups'),b=g.items.find(x=>x.code==='basic');return ok(admin,'/admin/groups/basic','PUT',{expected_revision:g.revision,priority:b.priority,max_entries:5,rolling_24h_limit:50,model_ids:ids,allowed_lengths:['short']});}
 await group([modelId]);sql("INSERT INTO wordweave.checkin_rules(effective_day,base_points,step_points,cap_points,normal_experience) VALUES(CURRENT_DATE-60,1,1,7,1) ON CONFLICT(effective_day) DO NOTHING");
 for(let i=0;i<3;i++){const r=await raw(user,'/generations/stream','POST',{model_id:modelId,meaning_language:'en',scenario:'story',length:'short',entries:['learn']});expect(r.status()).toBe(200);const events=(await r.text()).split('\n\n').filter(x=>x.startsWith('event:')).map(x=>{const lines=x.split('\n');return{event:lines[0].slice(7),data:JSON.parse(lines.find(x=>x.startsWith('data:')).slice(6))}});const started=events.find(x=>x.event==='generation.started').data;expect(events.filter(x=>/^generation\.(validated|failed|cancelled)$/.test(x.event)).map(x=>x.event)).toEqual(['generation.validated']);const saved=await raw(user,'/generations/'+started.run_id+'/save','POST',{}, {'X-Generation-Token':started.generation_token});expect(saved.status()).toBe(201);ids.push((await saved.json()).data.batch_id);}
 // Only historical timestamps are synthesized; all content/targets were created by actual generation/save APIs.
 for(const [i,date] of ['2026-09-11T06:59:59Z','2026-09-11T07:00:00Z','2026-09-12T07:00:00Z'].entries())sql(`UPDATE wordweave.learning_batches SET saved_at='${date}' WHERE id='${ids[i]}'`);
 const range={start_date:'2026-09-10',end_date:'2026-09-11',timezone:'America/Los_Angeles'};
 const query=r=>new URLSearchParams(r).toString();
 await test('V05','Browser-local inclusive date range, multi-batch snapshot and participation changes',async()=>{
  expect(await ok(user,'/me/review-range/preview?'+query(range))).toEqual({batch_count:2,entry_count:2,empty:false});
  expect((await ok(user,'/me/review-range/preview?'+query({...range,timezone:'Asia/Shanghai'}))).batch_count).toBe(2);
  expect((await ok(user,'/me/review-range/preview?'+query({...range,start_date:'2026-09-10',end_date:'2026-09-10'}))).batch_count).toBe(1);
  expect((await ok(user,'/me/review-range/preview?'+query({...range,start_date:'2026-09-10',end_date:'2026-09-10',timezone:'Asia/Shanghai'}))).batch_count).toBe(0);
  await page.goto(origin+'/review');await ready(page);await page.getByLabel(t('l.from'),{exact:true}).fill(range.start_date);await page.getByLabel(t('l.to'),{exact:true}).fill(range.end_date);await expect(page.locator('.range-count strong')).toHaveText('2');await button('l.begin').click();await expect(page.locator('.slot')).toHaveCount(5);sessionId=page.url().split('/').at(-1);
  const before=(await ok(user,'/me/review-sessions/'+sessionId)).session;expect(before.progress.total_batches).toBe(2);expect(Object.keys(before.current_batch).sort()).toEqual(['batch_id','saved_at','scenario']);
  await ok(user,'/me/batches/'+ids[0],'PATCH',{participates_in_range_review:false});expect((await ok(user,'/me/review-range/preview?'+query(range))).batch_count).toBe(1);expect((await ok(user,'/me/review-sessions/'+sessionId)).session.progress.total_batches).toBe(2);
  await page.screenshot({path:new URL('V05-range-batch.png',out).pathname,fullPage:true});traces.push({action,range,before,afterToggle:(await ok(user,'/me/review-sessions/'+sessionId)).session});
 });
 await test('V06','Two batches progress through next/completion; unique mastery and no persisted comparisons',async()=>{
  expect(sessionId).toBeTruthy();for(let n=0;n<2;n++){await expect(page.locator('.slot')).toHaveCount(5);for(const[i,c]of [...'learn'].entries())await page.locator('.slot').nth(i).fill(c);await button('next').click();for(const[i,s]of ['learns','learning','learned'].entries())await page.locator('.gap').nth(i).fill(s);await button('overview').click();const pending=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/submit'));await button('submit').click();const r=await pending;expect(r.status()).toBe(200);const data=(await r.json()).data;expect(data.receipt.successful).toBe(true);expect(data.session.progress).toEqual({completed_batches:n+1,total_batches:2,successful_batches:n+1,unsuccessful_batches:0,skipped_batches:0});expect(data.growth.new_masteries).toBe(n===0?1:0);submitted.push(data.receipt.attempt_id);await expect(page.locator('.result-word')).toHaveCount(4);if(n===0)await button('nextbatch').click();else await expect(button('finish')).toBeVisible();traces.push({action,receipt:data.receipt,progress:data.session.progress,growth:data.growth});}
  expect((await ok(user,'/me/growth')).mastered_total).toBe(1);expect(new Set(submitted).size).toBe(2);await page.screenshot({path:new URL('V06-final-summary.png',out).pathname,fullPage:true});await page.reload();await ready(page);await expect(page.locator('.result-word')).toHaveCount(0);await expect(page.getByText(t('l.summary.unavailable'),{exact:true})).toBeVisible();for(const id of submitted){const read=await ok(user,'/me/review-attempts/'+id);expect(read.state).toBe('submitted');expect(read.comparison).toBeUndefined();expect(read.attempt).toBeUndefined();}
 });
 await test('V07','Empty/stale range replacement preserves old session; successful replacement rejects old work',async()=>{
  await ok(user,'/me/batches/'+ids[0],'PATCH',{participates_in_range_review:true});const s=(await ok(user,'/me/review-sessions','POST',{mode:'range',...range})).session;const version=(await ok(user,'/me/review-sessions/'+s.session_id)).session_revision;
  const empty=await call(user,'/me/review-sessions/'+s.session_id+'/replace','POST',{confirmed:true,expected_session_revision:version,range:{...range,start_date:'2020-01-01',end_date:'2020-01-01'}});expect(empty.status).toBe(422);expect((await ok(user,'/me/review-sessions/active-range')).session.session_id).toBe(s.session_id);
  const attempt=(await ok(user,'/me/review-sessions/'+s.session_id+'/attempts','POST',{})).attempt;const stale=await call(user,'/me/review-sessions/'+s.session_id+'/replace','POST',{confirmed:true,expected_session_revision:version,range});expect(stale.status).toBe(409);
  const current=(await ok(user,'/me/review-sessions/'+s.session_id)).session_revision;const replaced=await ok(user,'/me/review-sessions/'+s.session_id+'/replace','POST',{confirmed:true,expected_session_revision:current,range});expect(replaced.replaced_session_id).toBe(s.session_id);expect((await ok(user,'/me/review-sessions/'+s.session_id)).session.status).toBe('abandoned');expect((await call(user,'/me/review-sessions/'+s.session_id+'/attempts','POST',{})).status).toBe(409);expect((await call(user,'/me/review-attempts/'+attempt.attempt_id+'/restart','POST',{expected_revision:attempt.revision})).status).toBe(409);traces.push({action,emptyStatus:422,staleStatus:409,old:s.session_id,new:replaced.session.session_id});
 });
 await test('V08','Random candidate exhaustion, current-library/other-owner boundaries and no quota/growth mutation',async()=>{
  // A temporary two-entry snapshot makes random outcomes exhaustive, without changing the immutable vocabulary asset.
  sql("BEGIN; UPDATE wordweave.vocabulary_snapshots SET version='qa5-original' WHERE version='m001'; INSERT INTO wordweave.vocabulary_snapshots(version,sha256,byte_size,entry_count) VALUES('m001',repeat('c',64),1,2); INSERT INTO wordweave.vocabulary_entries(snapshot_id,entry,source_order,lexeme_id) SELECT s.id,l.canonical_entry,row_number() OVER(ORDER BY l.id),l.id FROM wordweave.lexemes l CROSS JOIN wordweave.vocabulary_snapshots s WHERE s.version='m001' AND l.canonical_entry IN ('learn','book'); COMMIT;");swapped=true;
  const before=await ok(user,'/generation-options'),growth=await ok(user,'/me/growth'),ledger=sql(`SELECT count(*) FROM wordweave.quota_charges WHERE owner_id='${userId}'`);
  expect(await ok(user,'/vocabulary/random','POST',{selected_entries:[]})).toEqual({entry:'book',reason:null});expect(await ok(user,'/vocabulary/random','POST',{selected_entries:['book']})).toEqual({entry:null,reason:'no_candidates'});
  const other=await browser.newContext();await register(other,'random');expect(await ok(other,'/vocabulary/random','POST',{selected_entries:['book']})).toEqual({entry:'learn',reason:null});const guest=await browser.newContext();expect(await ok(guest,'/vocabulary/random','POST',{selected_entries:['book']})).toEqual({entry:'learn',reason:null});
  const bad=await call(user,'/vocabulary/random','POST',{selected_entries:['not-in-the-vocabulary']});expect(bad.status).toBe(422);
  expect((await ok(user,'/generation-options')).quota).toEqual(before.quota);expect((await ok(user,'/generation-options')).extra_quota).toEqual(before.extra_quota);expect(await ok(user,'/me/growth')).toEqual(growth);expect(sql(`SELECT count(*) FROM wordweave.quota_charges WHERE owner_id='${userId}'`)).toBe(ledger);
  for(const id of ids)expect((await call(user,'/me/batches/'+id,'DELETE')).status).toBe(204);expect((await ok(user,'/me/growth')).mastered_total).toBe(1);expect(await ok(user,'/vocabulary/random','POST',{selected_entries:['book']})).toEqual({entry:'learn',reason:null});traces.push({action,quota:before.quota,extra:before.extra_quota,ledgerCount:ledger,masteredAfterDeletion:1,knownCandidateReturnedAfterDeletion:'learn'});await other.close();await guest.close();
 });
 if(swapped){sql("BEGIN; DELETE FROM wordweave.vocabulary_entries WHERE snapshot_id=(SELECT id FROM wordweave.vocabulary_snapshots WHERE version='m001'); DELETE FROM wordweave.vocabulary_snapshots WHERE version='m001'; UPDATE wordweave.vocabulary_snapshots SET version='m001' WHERE version='qa5-original'; COMMIT;");swapped=false;}
 const models=[];for(const name of ['A','B','C'])models.push((await ok(admin,'/admin/models','POST',{display_name:'QA05 model '+name,description:null,openrouter_model_id:'qa05/'+name})).model);sql(`UPDATE wordweave.ai_models SET enabled=true WHERE id IN (${models.map(m=>"'"+m.id+"'").join(',')})`);
 async function define(name,which,days){const d=await ok(admin,'/admin/growth/items','POST',{kind:'model_trial',name:{zh_CN:null,en_US:name},description:{zh_CN:null,en_US:'QA05 overlap verification'},exchange_price:'0',activation_ttl_seconds:2592000,effect:{kind:'model_trial',model_ids:which.map(i=>models[i].id),trial_seconds:days*86400,retirement_points:'20'}});await ok(admin,'/admin/growth/items/'+d.item.id+'/listing','PUT',{listed:true,expected_revision:d.revision});return d.item.id;}
 const ab=await define('QA05 AB three days',[0,1],3),bc=await define('QA05 BC six days',[1,2],6);
 const acquire=async(c,id)=>(await ok(c,'/shop/exchanges','POST',{definition_id:id,quantity:1},randomUUID())).receipt.items[0].item_id;
 async function activate(c,id){const p=await ok(c,'/me/items/'+id+'/activation-preview','POST',{});expect(p.can_activate).toBe(true);const key=randomUUID(),body={confirmation_token:p.confirmation_token,confirm_discard:false};const r=await ok(c,'/me/items/'+id+'/activate','POST',body,key);return{p,r,key,body};}
 const times=r=>Object.fromEntries(r.item.model_times.map(x=>[x.model_id,x]));
 await test('V09','AB 3d + BC 6d and reverse order independently add each model; retries never duplicate time',async()=>{
  for(const reverse of [false,true]){const c=await browser.newContext(),uid=await register(c,reverse?'reverse':'forward');const before=await ok(c,'/generation-options');const one=await acquire(c,reverse?bc:ab),two=await acquire(c,reverse?ab:bc);const a=await activate(c,one),b=await activate(c,two);const ta=times(a.r),tb=times(b.r);const B=models[1].id;expect(Date.parse(tb[B].contribution_starts_at)).toBe(Date.parse(ta[B].contribution_ends_at));expect(Date.parse(tb[B].aggregate_ends_at)-Date.parse(ta[B].contribution_starts_at)).toBe(9*86400000);for(const x of a.r.item.model_times)expect(Date.parse(x.contribution_ends_at)-Date.parse(x.contribution_starts_at)).toBe((reverse?6:3)*86400000);for(const x of b.r.item.model_times)expect(Date.parse(x.contribution_ends_at)-Date.parse(x.contribution_starts_at)).toBe((reverse?3:6)*86400000);
   const count=sql(`SELECT count(*) FROM wordweave.model_time_contributions WHERE owner_id='${uid}'`);expect(count).toBe('4');const repeat=await ok(c,'/me/items/'+two+'/activate','POST',b.body,b.key);expect(repeat.receipt.id).toBe(b.r.receipt.id);const repeat2=await call(c,'/me/items/'+two+'/activate','POST',b.body,randomUUID());expect([200,422]).toContain(repeat2.status);expect(sql(`SELECT count(*) FROM wordweave.model_time_contributions WHERE owner_id='${uid}'`)).toBe(count);const after=await ok(c,'/generation-options');expect(after.quota).toEqual(before.quota);expect(after.extra_quota).toEqual(before.extra_quota);traces.push({action,reverse,first:a.r.item.model_times,second:b.r.item.model_times,repeatStatus:repeat2.status,contributions:count,quota:after.quota});if(!reverse){const p=await c.newPage();await p.goto(origin+'/account/items');await ready(p);await expect(p.locator('.item-model')).toHaveCount(2);await p.screenshot({path:new URL('V09-overlap-items.png',out).pathname,fullPage:true});}await c.close();}
 });
 await test('V10','Plan coverage blocks all-model cards, permits partial coverage and does not pause existing grants',async()=>{
  const c=await browser.newContext(),uid=await register(c,'coverage'),owned=await acquire(c,ab);await group([modelId,models[0].id,models[1].id]);const p=await ok(c,'/me/items/'+owned+'/activation-preview','POST',{});expect(p.can_activate).toBe(false);expect(p.reason).toBe('plan_already_covers_models');expect(p.confirmation_token).toBeNull();expect(sql(`SELECT count(*) FROM wordweave.model_time_contributions WHERE owner_id='${uid}'`)).toBe('0');await group([modelId,models[0].id]);const activation=await activate(c,owned);expect(activation.r.item.model_times).toHaveLength(2);const before=sql(`SELECT jsonb_agg(jsonb_build_object('model',model_id,'start',starts_at,'end',ends_at) ORDER BY model_id) FROM wordweave.model_time_contributions WHERE owner_id='${uid}'`);await group([modelId,models[0].id,models[1].id]);await ok(c,'/generation-options');await group([modelId]);await ok(c,'/generation-options');expect(sql(`SELECT jsonb_agg(jsonb_build_object('model',model_id,'start',starts_at,'end',ends_at) ORDER BY model_id) FROM wordweave.model_time_contributions WHERE owner_id='${uid}'`)).toBe(before);traces.push({action,blocked:p.reason,partialActivated:2,preservedTimes:JSON.parse(before)});await c.close();
 });
}catch(e){results.push({id:'setup',result:'FAIL',error:String(e)});console.log(String(e));}
finally{if(swapped)sql("BEGIN; DELETE FROM wordweave.vocabulary_entries WHERE snapshot_id=(SELECT id FROM wordweave.vocabulary_snapshots WHERE version='m001'); DELETE FROM wordweave.vocabulary_snapshots WHERE version='m001'; UPDATE wordweave.vocabulary_snapshots SET version='m001' WHERE version='qa5-original'; COMMIT;");dump('business-details.json',{traces,runtime});dump('business-results.json',{results,localProviderCalls:calls,realProviderCalls:0});console.log(JSON.stringify(results,null,2));await stop(browser);await new Promise(r=>provider.close(r));if(results.some(x=>x.result==='FAIL'))process.exitCode=1;}
