import {createServer} from 'node:http';
import {expect,start,stop,login,ok,call,sql,origin,out,t,dump,ready,instrument,randomUUID,env} from './harness.mjs';
const results=[],traces=[],runtime=[];let action='setup',calls=0,swapped=false;
const passage='A thoughtful student learns(learn) by building a steady learning(learn) routine through daily reading and discussion. Each morning the student reviews a few ideas, connects them with practical examples, and writes a short reflection. Friends later compare their observations, ask clear questions, and share useful explanations about what they learned(learn). This patient practice makes new knowledge easier to remember and apply with confidence.';
const provider=createServer(async(req,res)=>{if(req.url==='/models'){res.setHeader('content-type','application/json');res.end(JSON.stringify({data:[{id:'provider/integration',supported_parameters:['structured_outputs']}]}));return;}if(req.url!=='/chat/completions'){res.writeHead(404);res.end();return;}let body='';for await(const c of req)body+=c;calls++;const probe=JSON.parse(body).messages.some(m=>m.content.includes('fixed compatibility probe'));const candidate={passage:passage+(probe?' The group also discussed vulnerability(vulnerable) with empathy.':''),tags:['study'],targets:{learn:{entry_meaning:'gain knowledge through study',hint_phrase:'learning(learn) through learned(learn) examples while learning(learn)'}}};if(probe)candidate.targets.vulnerable={entry_meaning:'open to harm',hint_phrase:'vulnerable(vulnerable) communities'};res.setHeader('content-type','text/event-stream');res.end('data: '+JSON.stringify({choices:[{delta:{content:JSON.stringify(candidate)}}]})+'\n\ndata: [DONE]\n\n');});
await new Promise(r=>provider.listen(38082,'127.0.0.1',r));
const browser=await start(),admin=await browser.newContext(),user=await browser.newContext({timezoneId:'America/Los_Angeles',viewport:{width:1280,height:900}}),page=await user.newPage();instrument(page,runtime,()=>action);
async function test(id,name,fn){action=id;try{await fn();results.push({id,name,result:'PASS'});}catch(e){results.push({id,name,result:'FAIL',error:String(e)});await page.screenshot({path:new URL(id+'-failure.png',out).pathname,fullPage:true}).catch(()=>{});}dump('inherited-results.json',{results,localProviderCalls:calls,realProviderCalls:0});console.log(id,results.at(-1).result);}
async function raw(c,path,method,data,extra={}){const headers={origin,'sec-fetch-site':'same-origin',...extra};if(method!=='GET')headers['x-csrf-token']=(await ok(c,'/bootstrap')).csrf_token;return c.request.fetch(origin+'/api/v1'+path,{method,data,headers});}
const button=(key)=>page.getByRole('button',{name:t(key),exact:true});
const register=async(c,kind)=>(await ok(c,'/auth/register','POST',{username:'qa5_'+kind+'_'+Date.now(),password:env.ADMIN_PASSWORD,password_confirmation:env.ADMIN_PASSWORD,ui_locale:'en-US'})).actor.id;
let userId,modelId,ids=[],sessionId,submitted=[];try{
 await login(admin);const username='qa5_inherited_'+Date.now();userId=(await ok(user,'/auth/register','POST',{username,password:env.ADMIN_PASSWORD,password_confirmation:env.ADMIN_PASSWORD,ui_locale:'en-US'})).actor.id;modelId=(await ok(admin,'/admin/models')).items.find(x=>x.openrouter_model_id==='provider/integration').id;
 for(let i=0;i<2;i++){const r=await raw(user,'/generations/stream','POST',{model_id:modelId,meaning_language:'en',scenario:'story',length:'short',entries:['learn']});expect(r.status()).toBe(200);const events=(await r.text()).split('\n\n').filter(x=>x.startsWith('event:')).map(x=>{const lines=x.split('\n');return{event:lines[0].slice(7),data:JSON.parse(lines.find(x=>x.startsWith('data:')).slice(6))}});const started=events.find(x=>x.event==='generation.started').data;expect(events.filter(x=>/^generation\.(validated|failed|cancelled)$/.test(x.event)).map(x=>x.event)).toEqual(['generation.validated']);const saved=await raw(user,'/generations/'+started.run_id+'/save','POST',{}, {'X-Generation-Token':started.generation_token});expect(saved.status()).toBe(201);ids.push((await saved.json()).data.batch_id);}
 const second=await browser.newContext();await ok(second,'/auth/login','POST',{username,password:env.ADMIN_PASSWORD,browser_ui_locale:'en-US'});const adminPage=await admin.newPage();instrument(adminPage,runtime,()=>action);
 await test('V11','Inherited library exact-target search, pagination, paused batches and title exclusion',async()=>{
  const detail=(await ok(user,'/me/batches/'+ids[0])).batch;await ok(user,'/me/batches/'+ids[0],'PATCH',{title:'book',expected_title_revision:detail.title_revision});await ok(user,'/me/batches/'+ids[1],'PATCH',{participates_in_range_review:false});
  const first=await call(user,'/me/batches?entry=LEARN&limit=1');expect(first.status).toBe(200);expect(first.body.data.items).toHaveLength(1);expect(first.body.meta.has_more).toBe(true);const cursor=first.body.meta.next_cursor,last=await call(user,'/me/batches?entry=learn&limit=1&cursor='+encodeURIComponent(cursor));expect(last.body.meta.has_more).toBe(false);expect([first.body.data.items[0].id,last.body.data.items[0].id]).toEqual(ids);expect(last.body.data.items[0].participates_in_range_review).toBe(false);expect((await ok(user,'/me/batches?entry=book')).items).toHaveLength(0);expect((await call(user,'/me/batches?entry=book&limit=1&cursor='+encodeURIComponent(cursor))).status).toBe(422);
  const stats=await ok(user,'/me/learning-summary');await page.goto(origin+'/library');await ready(page);await page.getByRole('searchbox').fill('learn');await button('l.searchAction').click();await expect(page.locator('.library-card')).toHaveCount(2);await page.getByRole('searchbox').fill('book');await button('l.searchAction').click();await expect(page.getByText(t('l.noresults'),{exact:true})).toBeVisible();expect(await ok(user,'/me/learning-summary')).toEqual(stats);await page.screenshot({path:new URL('V11-title-not-target.png',out).pathname,fullPage:true});traces.push({action,matched:ids,bookTitleMatches:0,pausedIncluded:true,stableStatistics:stats});
 });
 await test('V12','Administrator opens actual user library and current title; all content write/impersonation routes deny access',async()=>{
  const data=await ok(admin,'/admin/users/'+userId+'/batches');expect(data.items.map(x=>x.id)).toEqual(ids);expect(data.items.every(x=>!('single_batch_review'in x))).toBe(true);const detail=(await ok(admin,'/admin/users/'+userId+'/batches/'+ids[0])).batch;expect(detail.title).toBe('book');expect(detail.targets.map(x=>x.entry)).toEqual(['learn']);
  await adminPage.goto(origin+'/admin/users/'+userId);await ready(adminPage);await adminPage.getByRole('button',{name:t('a.user.learning'),exact:true}).click();await expect(adminPage.locator('.admin-library-row')).toHaveCount(2);await adminPage.locator('.admin-library-row').first().getByRole('button',{name:t('a.reader'),exact:true}).click();const d=adminPage.locator('dialog[open]');await expect(d.locator('.admin-reader-title')).toHaveText('book');await expect(d.locator('.story-text')).toHaveText(detail.passage);await expect(d.locator('input,textarea,select,[contenteditable=true]')).toHaveCount(0);for(const key of ['l.delete','l.single'])await expect(d.getByRole('button',{name:t(key),exact:true})).toHaveCount(0);await adminPage.screenshot({path:new URL('V12-admin-readonly.png',out).pathname,fullPage:true});
  const rejections=[];for(const [path,method,body]of [['/me/batches/'+ids[0],'PATCH',{title:'illegal',expected_title_revision:detail.title_revision}],['/me/batches/'+ids[0],'DELETE',{}],['/me/review-sessions','POST',{mode:'single_batch',batch_id:ids[0]}],['/admin/users/'+userId+'/batches/'+ids[0],'PATCH',{title:'illegal'}],['/admin/users/'+userId+'/batches/'+ids[0],'DELETE',{}]]){const response=await raw(admin,path,method,body);expect([403,404,405]).toContain(response.status());rejections.push({path,method,status:response.status()});}expect((await ok(user,'/me/batches/'+ids[0])).batch).toEqual(detail);const other=await browser.newContext(),otherId=await register(other,'readonly');expect((await call(admin,'/admin/users/'+otherId+'/batches/'+ids[0])).status).toBe(404);await other.close();traces.push({action,rejections,unchangedContent:true});
 });
 await test('V13','Account UI language persists across a new login with opposite browser locale',async()=>{
  await page.goto(origin+'/library');await ready(page);await page.getByRole('button',{name:t('language'),exact:true}).click();await expect.poll(async()=>(await ok(user,'/bootstrap')).ui_locale).toBe('zh-CN');await page.reload();await ready(page);await expect(page.locator('h1')).toHaveText('我的书架');const c=await browser.newContext({locale:'en-US'});const identity=await ok(c,'/auth/login','POST',{username,password:env.ADMIN_PASSWORD,browser_ui_locale:'en-US'});expect(identity.ui_locale).toBe('zh-CN');const p=await c.newPage();await p.goto(origin+'/library');await ready(p);await expect(p.locator('h1')).toHaveText('我的书架');await p.screenshot({path:new URL('V13-account-locale.png',out).pathname,fullPage:true});await c.close();await ok(user,'/me/ui-locale','PUT',{ui_locale:'en-US'});traces.push({action,persistedLocale:identity.ui_locale,browserLocale:'en-US'});
 });
 await test('V14','Administrator password reset validates confirmation and revokes all target sessions only',async()=>{
  await adminPage.goto(origin+'/admin/users/'+userId);await ready(adminPage);await adminPage.getByRole('button',{name:t('a.user.password'),exact:true}).click();let d=adminPage.locator('dialog[open]');const fresh='QA05-new-local-'+randomUUID();await d.getByLabel(t('newpassword'),{exact:true}).fill(fresh);await d.getByLabel(t('a.password.confirm'),{exact:true}).fill(fresh+'mismatch');await expect(d.getByText(t('a.password.mismatch'),{exact:true})).toBeVisible();await expect(d.getByRole('button',{name:t('confirm'),exact:true})).toBeDisabled();await d.getByRole('button',{name:t('cancel'),exact:true}).click();expect((await call(user,'/me/account')).status).toBe(200);expect((await call(second,'/me/account')).status).toBe(200);
  await adminPage.getByRole('button',{name:t('a.user.password'),exact:true}).click();d=adminPage.locator('dialog[open]');await d.getByLabel(t('newpassword'),{exact:true}).fill(fresh);await d.getByLabel(t('a.password.confirm'),{exact:true}).fill(fresh);const response=adminPage.waitForResponse(r=>r.request().method()==='PUT'&&r.url().endsWith('/password'));await d.getByRole('button',{name:t('confirm'),exact:true}).click();expect((await response).status()).toBe(204);await expect(d).toHaveCount(0);expect((await call(user,'/me/account')).status).toBe(401);expect((await call(second,'/me/account')).status).toBe(401);expect((await call(admin,'/admin/users/'+userId)).status).toBe(200);
  const c=await browser.newContext();expect((await call(c,'/auth/login','POST',{username,password:env.ADMIN_PASSWORD,browser_ui_locale:'en-US'})).status).toBe(401);expect((await call(c,'/auth/login','POST',{username,password:fresh,browser_ui_locale:'en-US'})).status).toBe(200);expect((await ok(c,'/me/batches')).items).toHaveLength(2);await c.close();traces.push({action,oldSessionStatuses:[401,401],oldPasswordStatus:401,newPasswordStatus:200,contentRetained:2,adminSessionStatus:200});await adminPage.screenshot({path:new URL('V14-reset-success.png',out).pathname,fullPage:true});
 });
}catch(e){results.push({id:'setup',result:'FAIL',error:String(e)});console.log(String(e));}
finally{dump('inherited-details.json',{traces,runtime});dump('inherited-results.json',{results,localProviderCalls:calls,realProviderCalls:0});console.log(JSON.stringify(results,null,2));await stop(browser);await new Promise(r=>provider.close(r));if(results.some(x=>x.result==='FAIL'))process.exitCode=1;}
