import {expect,start,stop,ok,call,sql,origin,out,t,dump,ready,randomUUID,env} from './harness.mjs';
const browser=await start(),user=await browser.newContext(),page=await user.newPage(),results=[],traces=[];let action='V08',swapped=false;
const fixture=JSON.parse(sql("SELECT jsonb_build_object('id',id,'username',username) FROM wordweave.accounts WHERE username LIKE 'qa5_review_%'")),userId=fixture.id;
await ok(user,'/auth/login','POST',{username:fixture.username,password:env.ADMIN_PASSWORD,browser_ui_locale:'en-US'});
const ids=JSON.parse(sql(`SELECT jsonb_agg(id) FROM wordweave.learning_batches WHERE owner_id='${userId}'`));expect(ids).toHaveLength(3);
const register=async(c,kind)=>(await ok(c,'/auth/register','POST',{username:'qa5_'+kind+'_'+Date.now(),password:env.ADMIN_PASSWORD,password_confirmation:env.ADMIN_PASSWORD,ui_locale:'en-US'})).actor.id;
async function test(id,name,fn){try{await fn();results.push({id,name,result:'PASS'});}catch(e){results.push({id,name,result:'FAIL',error:String(e)});}console.log(id,results.at(-1).result);}
try{
 await test('V08','Random candidate exhaustion, current-library/other-owner boundaries and no quota/growth mutation',async()=>{
  // A temporary two-entry snapshot makes random outcomes exhaustive, without changing the immutable vocabulary asset.
  sql("BEGIN; UPDATE wordweave.vocabulary_snapshots SET version='qa5-original' WHERE version='m001'; INSERT INTO wordweave.vocabulary_snapshots(version,sha256,byte_size,entry_count) VALUES('m001',repeat('c',64),1,2); INSERT INTO wordweave.vocabulary_entries(snapshot_id,entry,source_order,lexeme_id) SELECT s.id,l.canonical_entry,row_number() OVER(ORDER BY l.id),l.id FROM wordweave.lexemes l CROSS JOIN wordweave.vocabulary_snapshots s WHERE s.version='m001' AND l.canonical_entry IN ('learn','book'); COMMIT;");swapped=true;
  const before=await ok(user,'/generation-options'),growth=await ok(user,'/me/growth'),ledger=sql(`SELECT count(*) FROM wordweave.generation_charges WHERE account_id='${userId}'`);
  expect(await ok(user,'/vocabulary/random','POST',{selected_entries:[]})).toEqual({entry:'book',reason:null});expect(await ok(user,'/vocabulary/random','POST',{selected_entries:['book']})).toEqual({entry:null,reason:'no_candidates'});
  const other=await browser.newContext();await register(other,'random');expect(await ok(other,'/vocabulary/random','POST',{selected_entries:['book']})).toEqual({entry:'learn',reason:null});const guest=await browser.newContext();expect(await ok(guest,'/vocabulary/random','POST',{selected_entries:['book']})).toEqual({entry:'learn',reason:null});
  const bad=await call(user,'/vocabulary/random','POST',{selected_entries:['not-in-the-vocabulary']});expect(bad.status).toBe(422);
  expect((await ok(user,'/generation-options')).quota).toEqual(before.quota);expect((await ok(user,'/generation-options')).extra_quota).toEqual(before.extra_quota);expect(await ok(user,'/me/growth')).toEqual(growth);expect(sql(`SELECT count(*) FROM wordweave.generation_charges WHERE account_id='${userId}'`)).toBe(ledger);
  for(const id of ids)expect((await call(user,'/me/batches/'+id,'DELETE',{})).status).toBe(204);expect((await ok(user,'/me/growth')).mastered_total).toBe(1);expect(await ok(user,'/vocabulary/random','POST',{selected_entries:['book']})).toEqual({entry:'learn',reason:null});traces.push({action,quota:before.quota,extra:before.extra_quota,ledgerCount:ledger,masteredAfterDeletion:1,knownCandidateReturnedAfterDeletion:'learn'});await other.close();await guest.close();
 });
}finally{if(swapped)sql("BEGIN; DELETE FROM wordweave.vocabulary_entries WHERE snapshot_id=(SELECT id FROM wordweave.vocabulary_snapshots WHERE version='m001'); DELETE FROM wordweave.vocabulary_snapshots WHERE version='m001'; UPDATE wordweave.vocabulary_snapshots SET version='m001' WHERE version='qa5-original'; COMMIT;");dump('random-v2-results.json',{results,traces,localProviderCalls:0,realProviderCalls:0});console.log(JSON.stringify(results,null,2));await stop(browser);if(results.some(x=>x.result==='FAIL'))process.exitCode=1;}
