import {expect,start,stop,login,ok,call,sql,origin,out,t,dump,ready,env,instrument} from './harness.mjs';
const browser=await start(),admin=await browser.newContext(),user=await browser.newContext(),page=await user.newPage(),samples=[],runtime=[];let current='V11';instrument(page,runtime,()=>current);
try{
 await login(admin);const f=JSON.parse(sql("SELECT jsonb_build_object('id',id,'username',username) FROM wordweave.accounts WHERE username LIKE 'qa5_inherited_%'"));await ok(admin,'/admin/users/'+f.id+'/password','PUT',{new_password:env.ADMIN_PASSWORD,new_password_confirmation:env.ADMIN_PASSWORD,confirmed:true});await ok(user,'/auth/login','POST',{username:f.username,password:env.ADMIN_PASSWORD,browser_ui_locale:'en-US'});const ids=JSON.parse(sql(`SELECT jsonb_agg(id ORDER BY saved_at,id) FROM wordweave.learning_batches WHERE owner_id='${f.id}'`));expect(ids).toHaveLength(2);
 const first=await call(user,'/me/batches?entry=learn&limit=1');expect(first.status).toBe(200);const cursor=first.body.meta.next_cursor;expect(cursor).toBeTruthy();const next=await call(user,'/me/batches?entry=learn&limit=1&cursor='+encodeURIComponent(cursor));expect(next.status).toBe(200);expect([first.body.data.items[0].id,next.body.data.items[0].id]).toEqual(ids);expect(next.body.data.items[0].participates_in_range_review).toBe(false);expect(next.body.meta.has_more).toBe(false);
 for(const entry of ['learn','LEARN','Learn',' learn ','book','lear']){for(const withCursor of [false,true]){const r=await call(user,'/me/batches?limit=1&entry='+encodeURIComponent(entry)+(withCursor?'&cursor='+encodeURIComponent(cursor):''));samples.push({entry,withCursor,status:r.status,code:r.body.code??null,ids:r.body.data?.items.map(x=>x.id)??null});}}
 const stats=await ok(user,'/me/learning-summary');await page.goto(origin+'/library');await ready(page);for(const entry of ['learn','LEARN','book']){let actual;const wait=page.waitForResponse(r=>r.url().includes('/api/v1/me/batches?')&&new URL(r.url()).searchParams.get('entry')===entry);await page.getByRole('searchbox').fill(entry);await page.getByRole('button',{name:t('l.searchAction'),exact:true}).click();actual=await wait;await page.waitForLoadState('networkidle');samples.push({entry,ui:true,status:actual.status(),visibleBatches:await page.locator('.library-row').count(),mainText:await page.locator('main').innerText()});await page.screenshot({path:new URL('V11-search-'+entry+'.png',out).pathname,fullPage:true});if(entry==='learn')await expect(page.locator('.library-row')).toHaveCount(2);if(entry==='book')await expect(page.getByText(t('l.noresults'),{exact:true})).toBeVisible();}
 expect(await ok(user,'/me/learning-summary')).toEqual(stats);dump('search-repro-results.json',{scenario:'V11',result:'FAIL',finding:'QA2-F07',samples,runtime,lowercasePagination:'PASS',titleExclusion:'PASS',statsUnchanged:true,realProviderCalls:0,localProviderCalls:0});
}catch(e){dump('search-repro-results.json',{samples,runtime,executionError:String(e)});throw e;}
finally{await stop(browser);}
