import {expect,start,stop,login,ok,call,sql,origin,out,t,dump,ready,instrument,randomUUID,env} from './harness.mjs';
const browser=await start(),admin=await browser.newContext(),a=await browser.newContext(),b=await browser.newContext(),c=await browser.newContext(),results=[],details=[],runtime=[];let action='setup';const page=await admin.newPage();instrument(page,runtime,()=>action);
async function check(id,name,fn){action=id;try{await fn();results.push({id,name,result:'PASS'});}catch(e){results.push({id,name,result:'FAIL',error:String(e)});}console.log(id,results.at(-1).result);dump('analytics-results.json',{results,realProviderCalls:0});}
const shift=(day,n)=>{const d=new Date(day+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const events=[];async function event(ctx,kind='page_view',source,action){const v={event_id:randomUUID(),kind,page:'PAGE-205',...(source?{source}:{}),...(action?{action}: {})};const r=await call(ctx,'/analytics/events','POST',v);expect(r.status).toBe(204);events.push(v);return v;}
const eventWhere=ids=>ids.map(id=>`event_key LIKE '%:${id}'`).join(' OR ');
function age(ids,day){const where=eventWhere(ids);sql(`UPDATE wordweave.traffic_sessions SET started_at='${day}T08:00:00+08:00',last_event_at='${day}T08:05:00+08:00',ended_at='${day}T08:35:00+08:00' WHERE id IN(SELECT traffic_session_id FROM wordweave.analytics_events WHERE ${where}); UPDATE wordweave.analytics_events SET occurred_at='${day}T08:02:00+08:00',learning_day='${day}' WHERE ${where}`);}
try{
 await login(admin);const today=(await ok(admin,'/admin/overview')).learning_day,day=shift(today,-5),tomorrow=shift(day,1),empty=shift(today,-8),q='?start_day='+day+'&end_day='+day;
 const e1=await event(a,'page_view',{utm_source:'qa4',referrer_host:'search.example'});const duplicate=await call(a,'/analytics/events','POST',e1);expect(duplicate.status).toBe(204);await event(a);await event(b,'page_view',{referrer_host:'search.example'});await event(c);await event(c,'key_action',null,'select_word');age(events.map(e=>e.event_id),day);const e6=await event(a);age([e6.event_id],tomorrow);
 // Historical, deterministic logical-run facts in the disposable DB; no provider calls or simulated page events used to claim run success.
 for(const kind of ['generation_valid','generation_valid','generation_failed','generation_failed','generation_cancelled',null]){const id=randomUUID();sql(`INSERT INTO wordweave.analytics_events(event_key,event_kind,occurred_at,started_at,learning_day,source_kind,reference_key) VALUES('qa4-start:${id}','generation_started','${day}T09:00:00+08:00','${day}T09:00:00+08:00','${day}','visitor','${id}')`);if(kind)sql(`INSERT INTO wordweave.analytics_events(event_key,event_kind,occurred_at,started_at,learning_day,source_kind,reference_key) VALUES('qa4-end:${id}','${kind}','${day}T09:01:00+08:00','${day}T09:00:00+08:00','${day}','visitor','${id}')`);}
 const setupAt=sql('SELECT clock_timestamp()::text');dump('analytics-fixture.json',{today,day,tomorrow,empty,events,duplicateStatus:duplicate.status,logicalRuns:{valid:2,failed:2,cancelled:1,ongoing:1},setupAt});
 // Observe the actual minute maintenance job; do not inject aggregate totals.
 await expect.poll(()=>sql('SELECT analytics_updated_at::text FROM wordweave.growth_settings WHERE singleton'),{timeout:75000,intervals:[1000,2000,5000]}).not.toBe(sql('SELECT analytics_updated_at::text FROM wordweave.growth_settings WHERE singleton'));
 await check('T11','Real event ingestion deduplicates retries, distinguishes browsers and channels, and deduplicates UV across two days',async()=>{
  const one=await ok(admin,'/admin/analytics/traffic'+q),range=await ok(admin,'/admin/analytics/traffic?start_day='+day+'&end_day='+tomorrow);expect(one.pv.value).toBe(4);expect(one.uv.value).toBe(3);expect(one.bounce_rate).toMatchObject({numerator:1,denominator:3,status:'ready'});expect(one.bounce_rate.value).toBeCloseTo(1/3);expect(range.pv.value).toBe(5);expect(range.uv.value).toBe(3);expect(range.series.reduce((n,x)=>n+x.uv.value,0)).toBe(4);expect(range.bounce_rate).toMatchObject({value:0.5,numerator:2,denominator:4});expect(Object.fromEntries(range.channels.map(x=>[x.source_type,x.pv.value]))).toEqual({utm:3,referrer:1,direct_unknown:1});expect(range.clarity).toEqual({available:false,url:null});expect(Number(sql(`SELECT count(*) FROM wordweave.analytics_events WHERE event_key LIKE '%:${e1.event_id}'`))).toBe(1);details.push({action,one,range});
 });
 await check('T12','Failure rate excludes cancelled and ongoing runs; empty samples and immature retention are not displayed as zero rates',async()=>{
  const funnel=await ok(admin,'/admin/analytics/funnel'+q);expect(funnel.generation.valid.value).toBe(2);expect(funnel.generation.failed.value).toBe(2);expect(funnel.generation.cancelled.value).toBe(1);expect(funnel.generation.ongoing.value).toBe(1);expect(funnel.generation.failure_rate).toMatchObject({value:0.5,numerator:2,denominator:4,status:'ready'});const noSample=await ok(admin,'/admin/analytics/funnel?start_day='+empty+'&end_day='+empty);expect(noSample.generation.failure_rate).toMatchObject({value:null,denominator:0,status:'no_sample'});const retention=await ok(admin,'/admin/analytics/retention?start_day='+today+'&end_day='+today);expect(retention.cohorts[0].accounts).toBeGreaterThanOrEqual(2);for(const k of ['d1','d7','d30'])expect(retention.cohorts[0][k]).toMatchObject({value:null,status:'observing'});const expired=await ok(admin,'/admin/analytics/traffic?start_day='+shift(today,-92)+'&end_day='+shift(today,-91));expect(expired.uv).toMatchObject({value:null,status:'unavailable',reason:'detail_expired'});details.push({action,funnel,noSample,retention,expired});
 });
 await check('T13','Collection rejects private fields and forged business events, excludes administrators, and restricts analytical reads',async()=>{
  const before=Number(sql('SELECT count(*) FROM wordweave.analytics_events'));const adminEvent={event_id:randomUUID(),kind:'page_view',page:'PAGE-205'};expect((await call(admin,'/analytics/events','POST',adminEvent)).status).toBe(204);expect(Number(sql('SELECT count(*) FROM wordweave.analytics_events'))).toBe(before);const rejected=[];for(const body of [{...adminEvent,event_id:randomUUID(),answer:'private-text'},{...adminEvent,event_id:randomUUID(),kind:'generation_valid'},{...adminEvent,event_id:randomUUID(),source:{referrer_host:'search.example/private?answer=value'}}]){const r=await call(b,'/analytics/events','POST',body);expect(r.status).toBe(422);rejected.push({status:r.status,code:r.body.code});}expect(Number(sql('SELECT count(*) FROM wordweave.analytics_events'))).toBe(before);const guest=await call(b,'/admin/analytics/traffic'+q);expect(guest.status).toBe(401);await ok(c,'/auth/register','POST',{username:'qa4_analytics_'+Date.now(),password:env.ADMIN_PASSWORD,password_confirmation:env.ADMIN_PASSWORD,ui_locale:'en-US'});const learner=await call(c,'/admin/analytics/traffic'+q);expect(learner.status).toBe(403);const response=await admin.request.get(origin+'/api/v1/admin/analytics/traffic'+q);expect(response.headers()['cache-control']).toContain('no-store');details.push({action,rejected,adminEventRows:0,guestStatus:guest.status,learnerStatus:learner.status,cacheControl:response.headers()['cache-control']});
 });
 await check('T14','Analytics page renders real collected values and a period change; account and analytics pages do not load Clarity',async()=>{
  const clarity=[];page.on('request',r=>{if(/clarity\.ms/i.test(r.url()))clarity.push(r.url());});await page.goto(origin+'/admin/analytics');await ready(page);await expect(page.locator('.metric').filter({hasText:t('pv')}).locator('strong')).toHaveText('5');await expect(page.locator('.metric').filter({hasText:t('failure')}).locator('strong')).toHaveText('50%');const pending=page.waitForResponse(r=>r.url().includes('/admin/analytics/traffic?')&&r.status()===200);await page.getByLabel(t('period'),{exact:true}).selectOption('30');await pending;await expect(page.getByLabel(t('period'),{exact:true})).toHaveValue('30');await page.screenshot({path:new URL('T14-analytics.png',out).pathname,fullPage:true});expect(clarity).toEqual([]);details.push({action,period:30,clarityRequests:clarity});
 });
}catch(e){results.push({id:'setup',result:'FAIL',error:String(e)});console.log(String(e));}
finally{dump('analytics-results.json',{results,realProviderCalls:0});dump('analytics-details.json',{details,runtime});console.log(JSON.stringify(results,null,2));await stop(browser);if(results.some(r=>r.result==='FAIL'))process.exitCode=1;}
