import {expect,start,stop,login,ok,sql,origin,out,t,dump,ready,instrument,env} from './harness.mjs';
const browser=await start(),admin=await browser.newContext(),user=await browser.newContext(),results=[],runtime=[],requests=[],api=[];let action='T14';const page=await admin.newPage(),up=await user.newPage();instrument(page,runtime,()=>action);instrument(up,runtime,()=>action);
try{
 await login(admin);const username=sql("SELECT username FROM wordweave.accounts WHERE username LIKE 'qa4_analytics_%' ORDER BY created_at DESC LIMIT 1");await ok(user,'/auth/login','POST',{username,password:env.ADMIN_PASSWORD,browser_ui_locale:'en-US'});
 for(const p of [page,up])p.on('request',r=>{if(/clarity\.ms/i.test(r.url()))requests.push(r.url());});
 await page.goto(origin+'/admin/analytics');await ready(page);
 const today=(await ok(admin,'/admin/overview')).learning_day,d=new Date(today+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-6);const query='?start_day='+d.toISOString().slice(0,10)+'&end_day='+today;const traffic=await ok(admin,'/admin/analytics/traffic'+query),funnel=await ok(admin,'/admin/analytics/funnel'+query);api.push({traffic,funnel});expect(traffic.pv.value).toBeGreaterThanOrEqual(5);
 await expect(page.locator('.metric').filter({hasText:t('pv')}).locator('strong')).toHaveText(String(traffic.pv.value));await expect(page.locator('.metric').filter({hasText:t('failure')}).locator('strong')).toHaveText('50%');
 const pending=page.waitForResponse(r=>r.url().includes('/admin/analytics/traffic?')&&r.status()===200);await page.getByLabel(t('period'),{exact:true}).selectOption('30');const response=await pending;api.push({period30:(await response.json()).data});await expect(page.getByLabel(t('period'),{exact:true})).toHaveValue('30');await page.screenshot({path:new URL('T14-analytics-verified.png',out).pathname,fullPage:true});
 await up.goto(origin+'/account/growth');await ready(up);expect(requests).toEqual([]);expect(runtime.filter(e=>e.kind==='pageerror'||/hydration/i.test(e.text))).toEqual([]);results.push({id:'T14',name:'Analytics UI matches the same API date range including current QA activity; period switch works; private account/admin pages load no Clarity',result:'PASS'});
}catch(e){results.push({id:'T14',result:'FAIL',error:String(e)});}
finally{dump('analytics-ui-results.json',{results,api,runtime,clarityRequests:requests,realProviderCalls:0});console.log(JSON.stringify(results,null,2));await stop(browser);if(results.some(r=>r.result==='FAIL'))process.exitCode=1;}
