import {expect,start,stop,login,ok,sql,origin,out,t,dump,ready,instrument,env} from './harness.mjs';
const browser=await start(),admin=await browser.newContext(),user=await browser.newContext(),results=[],runtime=[],requests=[],api=[];let action='T14';const page=await admin.newPage(),up=await user.newPage();instrument(page,runtime,()=>action);instrument(up,runtime,()=>action);
try{
 await login(admin);const username=sql("SELECT username FROM wordweave.accounts WHERE username LIKE 'qa4_analytics_%' ORDER BY created_at DESC LIMIT 1");await ok(user,'/auth/login','POST',{username,password:env.ADMIN_PASSWORD,browser_ui_locale:'en-US'});
 for(const p of [page,up])p.on('request',r=>{if(/clarity\.ms/i.test(r.url()))requests.push(r.url());});
 await page.goto(origin+'/admin/analytics');await ready(page);
 const today=(await ok(admin,'/admin/overview')).learning_day,d=new Date(today+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-6);const query='?start_day='+d.toISOString().slice(0,10)+'&end_day='+today;const traffic=await ok(admin,'/admin/analytics/traffic'+query),funnel=await ok(admin,'/admin/analytics/funnel'+query);api.push({traffic,funnel});expect(traffic.pv.value).toBeGreaterThanOrEqual(5);
 await expect(page.locator('.metric').filter({hasText:t('pv')}).locator('strong')).toHaveText(String(traffic.pv.value));const failureText=await page.locator('.metric').filter({hasText:t('failure')}).locator('strong').innerText();expect(failureText.endsWith('%')).toBe(true);expect(Number.parseFloat(failureText)/100).toBe(funnel.generation.failure_rate.value);
 dump('T14-before-period.json', {fields:await page.locator('select').evaluateAll(es=>es.map(e=>({value:e.value,disabled:e.disabled,html:e.outerHTML}))),text:await page.locator('main').innerText()});page.on('response',r=>{if(r.url().includes('analytics')){api.push({url:r.url(),status:r.status()});dump('T14-network.json',api);}});dump('T14-label-diagnostic.json',{labelCount:await page.getByLabel(t('period'),{exact:true}).count(),comboboxCount:await page.getByRole('combobox',{name:t('period'),exact:true}).count(),aria:await page.locator('select').ariaSnapshot()});await page.locator('select').selectOption('30');await expect(page.locator('select')).toBeEnabled();await expect(page.locator('select')).toHaveValue('30');await expect.poll(()=>api.filter(x=>x.url?.includes('/admin/analytics/traffic?')).length,{timeout:12000}).toBeGreaterThan(0);await page.screenshot({path:new URL('T14-analytics-verified.png',out).pathname,fullPage:true});
 await up.goto(origin+'/account/growth');await ready(up);expect(requests).toEqual([]);expect(runtime.filter(e=>e.kind==='pageerror'||/hydration/i.test(e.text))).toEqual([]);results.push({id:'T14',name:'Analytics UI matches the same API date range including current QA activity; period switch works; private account/admin pages load no Clarity',result:'PASS'});
}catch(e){await page.screenshot({path:new URL('T14-final-failure.png',out).pathname,fullPage:true});results.push({id:'T14',result:'FAIL',error:String(e)});}
finally{dump('analytics-ui-final-results.json',{results,api,runtime,clarityRequests:requests,realProviderCalls:0});console.log(JSON.stringify(results,null,2));await stop(browser);if(results.some(r=>r.result==='FAIL'))process.exitCode=1;}
