import {expect,start,stop,login,ok,call,sql,origin,out,t,dump,ready,instrument,randomUUID,env} from './harness.mjs';
const browser=await start(),admin=await browser.newContext(),user=await browser.newContext({viewport:{width:1440,height:1000}}),results=[],details=[],runtime=[];let action='setup';const page=await user.newPage();instrument(page,runtime,()=>action);
async function check(id,name,fn){action=id;try{await fn();results.push({id,name,result:'PASS'});}catch(e){results.push({id,name,result:'FAIL',error:String(e)});await page.screenshot({path:new URL(id+'-failure.png',out).pathname,fullPage:true});}console.log(id,results.at(-1).result);}
const shift=(day,n)=>{const d=new Date(day+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
try{
 await login(admin);const account=await ok(user,'/auth/register','POST',{username:'qa4_makeup_'+Date.now(),password:env.ADMIN_PASSWORD,password_confirmation:env.ADMIN_PASSWORD,ui_locale:'en-US'}),id=account.actor.id;
 const today=(await ok(user,'/me/growth')).learning_day,target=shift(today.slice(0,8)+'01',-1);expect(target>=shift(today,-30)).toBe(true);expect(shift(target,2)<today).toBe(true);
 sql(`UPDATE wordweave.accounts SET created_at=clock_timestamp()-interval '60 days' WHERE id='${id}'; INSERT INTO wordweave.checkin_rules(effective_day,base_points,step_points,cap_points,normal_experience) VALUES('${shift(target,1)}',20,3,100,5),('${today}',50,10,200,9); INSERT INTO wordweave.growth_balances(owner_id,points,experience) VALUES('${id}',51,13) ON CONFLICT(owner_id) DO UPDATE SET points=51,experience=13; INSERT INTO wordweave.user_growth(owner_id,highest_checkin_streak,highest_review_streak) VALUES('${id}',2,7) ON CONFLICT(owner_id) DO UPDATE SET highest_checkin_streak=2,highest_review_streak=7; INSERT INTO wordweave.user_checkins(owner_id,learning_day,kind,rule_id,streak_at_last_settlement,points_paid,normal_experience_paid) SELECT '${id}',d.day,'normal',(SELECT id FROM wordweave.checkin_rules WHERE effective_day<=d.day ORDER BY effective_day DESC LIMIT 1),d.streak,d.points,d.xp FROM (VALUES('${shift(target,-1)}'::date,1,8,3),('${shift(target,1)}'::date,1,20,5),('${shift(target,2)}'::date,2,23,5)) AS d(day,streak,points,xp); INSERT INTO wordweave.user_learning_days(owner_id,learning_day,active,review_success,review_submissions,successful_reviews) VALUES('${id}','${shift(today,-2)}',true,true,1,1),('${id}','${shift(today,-1)}',true,true,1,1)`);
 const definition=await ok(admin,'/admin/growth/items','POST',{kind:'makeup',name:{zh_CN:null,en_US:'QA04 makeup pass'},description:{zh_CN:null,en_US:'Restore one missed check-in'},exchange_price:'0',activation_ttl_seconds:2592000,effect:{kind:'makeup'}});await ok(admin,'/admin/growth/items/'+definition.item.id+'/listing','PUT',{listed:true,expected_revision:definition.revision});const cards=(await ok(user,'/shop/exchanges','POST',{definition_id:definition.item.id,quantity:2},randomUUID())).receipt.items.map(i=>i.item_id);
 const config=await ok(admin,'/admin/growth/achievements?kind=checkin_streak');const achievement=await ok(admin,'/admin/growth/achievements','PUT',{kind:'checkin_streak',expected_revision:config.revision,changes:[{client_key:randomUUID(),id:null,value:{threshold:4,enabled:true,name:{zh_CN:null,en_US:'QA04 four-day streak'},title:{zh_CN:null,en_US:'Four days together'},description:{zh_CN:null,en_US:'Reward is claimed manually'},reward:{points:'7',experience:'11',item_definition_id:null,item_count:0}}}]});const tier=achievement.configuration.items.find(a=>a.name.en_US==='QA04 four-day streak');
 const snapshot=()=>JSON.parse(sql(`SELECT json_build_object('checkins',(SELECT json_agg(c ORDER BY learning_day) FROM (SELECT learning_day,kind,streak_at_last_settlement,points_paid,normal_experience_paid FROM wordweave.user_checkins WHERE owner_id='${id}')c),'items',(SELECT json_agg(c ORDER BY id) FROM (SELECT id,activated_at FROM wordweave.user_items WHERE owner_id='${id}')c),'learning',(SELECT json_agg(c ORDER BY learning_day) FROM (SELECT learning_day,active,review_success,review_submissions,successful_reviews FROM wordweave.user_learning_days WHERE owner_id='${id}')c))`));
 const before=await ok(user,'/me/growth'),dbBefore=snapshot();let preview,settlement,requestBody,usedCard;
 await check('T08','Cross-month makeup uses each day historical rule, displays separate positive differences, and preview consumes nothing',async()=>{
  preview=await ok(user,'/me/growth/makeup-preview','POST',{item_id:cards[0],learning_day:target});expect(preview.can_use).toBe(true);expect(preview.points_added).toBe('22');expect(preview.experience_added).toBe('0');expect(preview.affected_days.map(d=>({day:d.day,before:d.before_points,after:d.after_points,difference:d.difference}))).toEqual([{day:target,before:'0',after:'10',difference:'10'},{day:shift(target,1),before:'20',after:'26',difference:'6'},{day:shift(target,2),before:'23',after:'29',difference:'6'}]);expect(snapshot()).toEqual(dbBefore);expect((await ok(user,'/me/growth')).points).toBe('51');
  await page.goto(origin+'/account/items');await ready(page);await page.locator('.item-makeup').first().getByRole('button',{name:t('makeup'),exact:true}).click();const d=page.locator('dialog[open]');await expect(d.getByRole('button',{name:t('confirm'),exact:true})).toBeDisabled();await d.locator('button[title="'+target+'"]').click();await expect(d).toContainText('0 → 10');await expect(d).toContainText('20 → 26');await expect(d).toContainText('23 → 29');await page.screenshot({path:new URL('T08-historical-differences.png',out).pathname,fullPage:true});expect(snapshot()).toEqual(dbBefore);details.push({action,today,target,preview:{...preview,confirmation_token:'REDACTED'},before});
 });
 await check('T09','UI confirmation consumes one card, adds only 22 historical points, preserves review days, and leaves new achievement unclaimed',async()=>{
  const d=page.locator('dialog[open]'),pending=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/growth/makeups'));await d.getByRole('button',{name:t('confirm'),exact:true}).click();const r=await pending;expect(r.status()).toBe(200);await expect(d).toHaveCount(0);requestBody=r.request().postDataJSON();usedCard=requestBody.item_id;settlement=(await r.json()).data;expect(settlement.receipt.points_delta).toBe('22');expect(settlement.receipt.experience_delta).toBe('0');const after=await ok(user,'/me/growth');expect(after.points).toBe('73');expect(after.experience).toBe('13');expect(after.checkin.highest_streak).toBe(4);expect(after.review_streak).toEqual(before.review_streak);const db=snapshot();expect(db.learning).toEqual(dbBefore.learning);expect(db.items.filter(i=>i.activated_at!==null)).toHaveLength(1);const ach=(await ok(user,'/me/growth/achievements')).items.find(a=>a.tier_id===tier.id);expect(ach.state).toBe('claimable');expect(ach.claimed_at).toBeNull();const cal=await ok(user,'/me/growth/checkins?start_date='+target+'&end_date='+shift(target,2));expect(cal.days[0]).toMatchObject({day:target,state:'makeup',points_paid:'10',can_makeup:false});await page.goto(origin+'/account/growth');await ready(page);const card=page.locator('.achievement').filter({hasText:'QA04 four-day streak'});await expect(card.getByRole('button',{name:t('claim'),exact:true})).toBeEnabled();await expect(card).toContainText('Four days together');await page.screenshot({path:new URL('T09-unclaimed-achievement.png',out).pathname,fullPage:true});details.push({action,after,db,settlement,achievement:ach,calendar:cal});
 });
 await check('T10','Replay does not double-pay; already signed, outside-window and pre-registration days cannot consume another card',async()=>{
  const repeated=await ok(user,'/me/growth/makeups','POST',requestBody,randomUUID());expect(repeated.receipt.id).toBe(settlement.receipt.id);const spare=cards.find(i=>i!==usedCard);const denied=await call(user,'/me/growth/makeups','POST',{item_id:spare,learning_day:target,confirmation_token:preview.confirmation_token},randomUUID());expect(denied.status).toBe(422);expect(denied.body.code).toBe('day_already_checked_in');const checks=[];for(const day of [shift(today,-31),today,shift(today,1)]){const r=await ok(user,'/me/growth/makeup-preview','POST',{item_id:spare,learning_day:day});expect(r.can_use).toBe(false);expect(r.reason).toBe('invalid_target_day');checks.push({day,result:r});}
  const oldEnough=await ok(user,'/me/growth/makeup-preview','POST',{item_id:spare,learning_day:shift(today,-30)});expect(oldEnough.can_use).toBe(true);sql(`UPDATE wordweave.accounts SET created_at=clock_timestamp()-interval '10 days' WHERE id='${id}'`);const beforeRegistration=await ok(user,'/me/growth/makeup-preview','POST',{item_id:spare,learning_day:shift(today,-20)});expect(beforeRegistration.can_use).toBe(false);expect(beforeRegistration.reason).toBe('invalid_target_day');sql(`UPDATE wordweave.accounts SET created_at=clock_timestamp()-interval '60 days' WHERE id='${id}'`);const after=await ok(user,'/me/growth');expect(after.points).toBe('73');expect(after.experience).toBe('13');expect(snapshot().items.find(i=>i.id===spare).activated_at).toBeNull();details.push({action,sameReceipt:true,duplicateStatus:denied.status,checks,boundaryThirtyDaysEligible:true,beforeRegistration,after});
 });
}catch(e){results.push({id:'setup',result:'FAIL',error:String(e)});console.log(String(e));}
finally{dump('makeup-results.json',{results,realProviderCalls:0});dump('makeup-details.json',{details,runtime});console.log(JSON.stringify(results,null,2));await stop(browser);if(results.some(r=>r.result==='FAIL'))process.exitCode=1;}
