import{createRequire}from'node:module';import{readFileSync,writeFileSync}from'node:fs';import{execFileSync}from'node:child_process';import{createServer,request}from'node:http';
const{chromium}=createRequire(process.cwd()+'/frontend/package.json')('@playwright/test');const work=readFileSync('/tmp/wordweave-fe-m002-current','utf8'),env=JSON.parse(readFileSync(work+'/env.json'));if(!env.APP_DATABASE_URL.includes('63541/wordweave_fe_m002'))throw Error('Wrong stack');const origin='http://127.0.0.1:3302';
const proxy=createServer((req,res)=>{const r=request({hostname:'127.0.0.1',port:req.url.startsWith('/api/v1')?38081:3331,path:req.url,method:req.method,headers:{...req.headers,origin:'http://127.0.0.1:3301','x-forwarded-host':'127.0.0.1:3301','x-forwarded-proto':'http'}},u=>{res.writeHead(u.statusCode,u.headers);u.pipe(res)});r.on('error',()=>res.end());req.pipe(r)});await new Promise(r=>proxy.listen(3302,'127.0.0.1',r));
const name=execFileSync('/opt/homebrew/opt/postgresql@18/bin/psql',[env.APP_DATABASE_URL,'-t','-A','-c',"SELECT username FROM wordweave.accounts WHERE username LIKE 'qa3_control_%' ORDER BY created_at DESC LIMIT 1"],{encoding:'utf8'}).trim();const browser=await chromium.launch(),c=await browser.newContext(),p=await c.newPage(),events=[];
p.on('console',m=>{if(/hydration|mismatch/i.test(m.text()))events.push({url:p.url(),type:m.type(),message:m.text().slice(0,5000)})});p.on('pageerror',e=>events.push({url:p.url(),type:'pageerror',message:e.message}));
try{
 const boot=await(await c.request.get(origin+'/api/v1/bootstrap')).json();const login=await c.request.post(origin+'/api/v1/auth/login',{headers:{origin:'http://127.0.0.1:3301','x-csrf-token':boot.data.csrf_token,'sec-fetch-site':'same-origin'},data:{username:name,password:env.ADMIN_PASSWORD,browser_ui_locale:'en-US'}});if(!login.ok())throw Error('Login failed '+login.status());
 for(const path of ['/account','/account/growth','/account/items','/account/exchange','/library','/review','/']){await p.goto(origin+path);await p.waitForFunction(()=>document.documentElement.dataset.appReady==='true');await p.waitForTimeout(400)}
 const b2=await(await c.request.get(origin+'/api/v1/bootstrap')).json();await c.request.post(origin+'/api/v1/auth/logout',{headers:{origin:'http://127.0.0.1:3301','x-csrf-token':b2.data.csrf_token,'sec-fetch-site':'same-origin'},data:{}});
 const b3=await(await c.request.get(origin+'/api/v1/bootstrap')).json();await c.request.post(origin+'/api/v1/auth/login',{headers:{origin:'http://127.0.0.1:3301','x-csrf-token':b3.data.csrf_token,'sec-fetch-site':'same-origin'},data:{username:env.ADMIN_USERNAME,password:env.ADMIN_PASSWORD,browser_ui_locale:'en-US'}});
 for(const path of ['/admin','/admin/growth','/admin/presets']){await p.goto(origin+path);await p.waitForFunction(()=>document.documentElement.dataset.appReady==='true');await p.waitForTimeout(400)}
}catch(e){events.push({type:'harness',message:String(e)})}finally{writeFileSync(new URL('runtime-audit.json',import.meta.url),JSON.stringify({events},null,2));console.log(JSON.stringify(events,null,2));await browser.close();await new Promise(r=>proxy.close(r));}
