import{readFileSync,writeFileSync}from'node:fs';import{execFileSync}from'node:child_process';import{createHash}from'node:crypto';import{dirname,join,resolve}from'node:path';import{fileURLToPath}from'node:url';
const dir=dirname(fileURLToPath(import.meta.url)),root=resolve(dir,'../../../../../..'),sha=b=>createHash('sha256').update(b).digest('hex');
const paths=execFileSync('rg',['--files','--hidden','-g','!.git','-g','!node_modules','-g','!.nuxt','-g','!.output','-g','!test-results','-g','!playwright-report','-g','!.env','-g','!**/.env.*','-g','!**/evidence/cr037-081/**'],{cwd:root,encoding:'utf8'}).trim().split('\n');
const hashes=Object.fromEntries(paths.map(p=>[p,sha(readFileSync(join(root,p)))])),state=readFileSync(join(root,'.planning/workflow/state.yaml'),'utf8');if(!/active_agent: "?qa-quinn"?/.test(state)||!/stage: "?verification"?/.test(state))throw Error('Wrong active role');
const approved=readFileSync(join(root,'.planning/milestones/M001/reviews/implementation-cr037-independent-verification-approval.md'),'utf8'),snapshots=[...approved.matchAll(/\| \[([^\]]+)\]\([^)]*\) \| (\d+) \| `([a-f0-9]+)` \|/g)];for(const[,p,size,h]of snapshots){const b=readFileSync(join(root,'.planning/milestones/M001',p));if(b.length!==Number(size)||sha(b)!==h)throw Error('Approved artifact changed '+p);}
writeFileSync(join(dir,'source-baseline.json'),JSON.stringify({date:new Date().toISOString(),hashes,approvedSnapshots:snapshots.length},null,2),{flag:'wx'});console.log(JSON.stringify({files:paths.length,approvedSnapshots:snapshots.length}));

const yaml=(await import('../../../../../../frontend/node_modules/.pnpm/yaml@2.9.0/node_modules/yaml/dist/index.js')).default;
const project=yaml.parse(readFileSync(join(root,'.planning/agt/project.yaml'),'utf8')),profile=readFileSync(join(root,'../agt-coding-v2',project.agt_base.profile.source));if(sha(profile)!==project.agt_base.profile.sha256)throw Error('Profile lock changed');
const registry=yaml.parse(readFileSync(join(root,'.planning/agt/agents.yaml'),'utf8'));if(registry.agents.filter(a=>a.status==='active').map(a=>a.display_name).join(',')!=='qa-quinn')throw Error('Wrong active registry');
const docs=['verification/coverage-matrix.md','verification/report.md','verification/ui-design-audit.md','verification/ai-evaluation.md','verification/uat.md','handoffs/verification.md','changes/CR-037.md'];const reporting=docs.map(path=>{const s=readFileSync(join(root,'.planning/milestones/M001',path),'utf8'),end=s.indexOf('\n---\n',4)+5;return{path,header:s.slice(0,end),bodyHash:sha(s.slice(end))};});writeFileSync(join(dir,'reporting-baseline.json'),JSON.stringify(reporting,null,2),{flag:'wx'});

