import{execFileSync,spawnSync}from'node:child_process';import{readFileSync,writeFileSync}from'node:fs';import{join,resolve}from'node:path';import{createHash}from'node:crypto';import{dir,sql}from'./lib.mjs';
const root=resolve(dir,'../../../../../..'),docker=args=>execFileSync('docker',args,{encoding:'utf8'}).trim(),source=JSON.parse(readFileSync(join(dir,'source-baseline.json'))),baseline=JSON.parse(readFileSync(join(dir,'baseline.json')));
const modified=Object.entries(source.hashes).filter(([p,h])=>createHash('sha256').update(readFileSync(join(root,p))).digest('hex')!==h).map(([p])=>p);if(modified.length)throw Error('Unexpected changes before reporting: '+modified.join(','));
const names=['ww-qa-081-nginx','ww-qa-081-frontend','ww-qa-081-backend','ww-qa-081-db'],networks=['ww-qa-081','ww-qa-081-edge'];for(const n of names)if(JSON.parse(docker(['inspect',n]))[0].Config.Labels['wordweave.qa']!=='081')throw Error('Unowned container '+n);for(const n of networks)if(JSON.parse(docker(['network','inspect',n]))[0].Labels['wordweave.qa']!=='081')throw Error('Unowned network '+n);
const data=JSON.parse(sql("SELECT json_build_object('accounts',(SELECT count(*) FROM wordweave.accounts),'batches',(SELECT count(*) FROM wordweave.learning_batches),'review_sessions',(SELECT count(*) FROM wordweave.review_sessions),'generation_runs',(SELECT count(*) FROM wordweave.generation_runs),'models',(SELECT count(*) FROM wordweave.ai_models),'credentials',(SELECT count(*) FROM wordweave.openrouter_credentials))"));if(data.batches||data.review_sessions||data.generation_runs||data.models||data.credentials)throw Error('Unexpected out-of-scope data');
writeFileSync(join(dir,'pre-cleanup-data.json'),JSON.stringify(data,null,2),{flag:'wx'});
docker(['stop','--time','2',...names]);docker(['rm',...names]);for(const n of networks)docker(['network','rm',n]);
const uat=JSON.parse(docker(['inspect','wordweave_uat-frontend-1','wordweave_uat-backend-1','wordweave_uat-nginx-1','wordweave_uat-postgres-1'])).map(x=>({name:x.Name,id:x.Id,image:x.Image,started:x.State.StartedAt}));
const result={date:new Date().toISOString(),verifiedBaselineFiles:Object.keys(source.hashes).length,modifiedBeforeReport:modified,uatUnchanged:JSON.stringify(uat)===JSON.stringify(baseline.uat),original6010Available:(await fetch('http://127.0.0.1:6010/prototype/')).status===200,port6101Released:spawnSync('lsof',['-nP','-iTCP:6101','-sTCP:LISTEN']).status===1,ownedContainersRemaining:docker(['ps','-a','--filter','label=wordweave.qa=081','--format','{{.Names}}']),removedContainers:names,removedNetworks:networks,data,dataRecovery:'Synthetic tmpfs DB removed, not recoverable; reproducible fixture scripts retained. UAT untouched.'};writeFileSync(join(dir,'cleanup.json'),JSON.stringify(result,null,2),{flag:'wx'});console.log(JSON.stringify(result));if(!result.uatUnchanged||!result.original6010Available||!result.port6101Released||result.ownedContainersRemaining)process.exitCode=1;

