import{readFileSync,writeFileSync,existsSync}from'node:fs';import{createHash}from'node:crypto';import{dirname,join,resolve}from'node:path';import{fileURLToPath}from'node:url';import{execFileSync}from'node:child_process';
import YAML from '../../../../../../frontend/node_modules/.pnpm/yaml@2.9.0/node_modules/yaml/dist/index.js';
const dir=dirname(fileURLToPath(import.meta.url)),root=resolve(dir,'../../../../../..'),base='.planning/milestones/M001/',json=p=>JSON.parse(readFileSync(join(root,p))),sha=b=>createHash('sha256').update(b).digest('hex'),checks=[];
const check=(id,ok)=>{checks.push({id,pass:!!ok});if(!ok)throw Error(id);};
const statePath='.planning/workflow/state.yaml',historyPath='.planning/workflow/history.yaml',stateText=readFileSync(join(root,statePath),'utf8'),historyText=readFileSync(join(root,historyPath),'utf8'),state=YAML.parse(stateText),history=YAML.parse(historyText),agents=YAML.parse(readFileSync(join(root,'.planning/agt/agents.yaml'),'utf8'));
check('verification qa-quinn remains active',state.stage==='verification'&&state.active_agent==='qa-quinn'&&state.active_role==='quality/base');
check('one registered active specialist',agents.agents.filter(a=>a.status==='active').length===1&&agents.agents.find(a=>a.status==='active').display_name===state.active_agent);
check('continuous approval explicitly stops at UAT',state.continuous_authorization?.stop_at.includes('UAT handoff'));
check('remain decision permitted',state.allowed_transitions.includes('remain_in_current_stage'));
check('no pending product decisions',state.pending_user_decisions.length===0);
check('required artifacts exist',state.required_artifacts.every(p=>existsSync(join(root,p))));
const qa=json(base+'verification/evidence/cr036-078/delivery-validation.json'),smoke=json(base+'verification/evidence/uat-079/smoke-final-results.json'),deployment=json(base+'verification/evidence/uat-079/deployment.json');
check('independent pass evidence',qa.validated&&qa.verdict==='passed_for_functional_uat'&&qa.results.length===19&&qa.results.every(r=>r.verified&&r.counts.FAIL===0&&r.counts.ERROR===0));
for(const r of qa.results){const raw=json(base+'verification/evidence/cr036-078/'+r.file);check('raw '+r.file,raw.counts.PASS===r.counts.PASS&&raw.counts.FAIL===0&&raw.counts.ERROR===0);}
check('paired healthy UAT with preserved data/runtime',deployment.healthy&&deployment.pairedImages&&deployment.dataUnchanged&&deployment.databaseContainerUnchanged&&deployment.nginxContainerUnchanged&&deployment.runtimeEnvironmentPreserved&&deployment.migrationsRun===false&&deployment.realAICalls===0);
check('UAT smoke102 and both logins',smoke.counts.PASS===102&&smoke.counts.FAIL===0&&smoke.counts.ERROR===0&&smoke.credentialsVerified.includes('uat_admin')&&smoke.credentialsVerified.includes('uat_learner'));
const candidate=json(base+'implementation/evidence/cr036-077/candidate.json');
check('seven fixed source digests',candidate.sourceFiles.length===7&&candidate.sourceFiles.every(f=>sha(readFileSync(join(root,f.path)))===f.sha256));
const baseline=json(base+'verification/evidence/cr036-078/source-baseline.json'),production=Object.entries(baseline.hashes).filter(([p])=>!p.startsWith('.planning/'));
check('all existing non-planning source unchanged after independent baseline',production.every(([p,d])=>sha(readFileSync(join(root,p)))===d));
const reporting=json(base+'verification/evidence/cr036-078/reporting-baseline.json');
for(const doc of reporting.docs){let text=readFileSync(join(root,base+doc.path),'utf8');const header=text.match(/^---\n[\s\S]*?\n---\n/)[0];text=text.slice(header.length).replace(/^\n<!-- UAT079 CURRENT BEGIN -->[\s\S]*?<!-- UAT079 CURRENT END -->\n/,'');const index=text.indexOf(doc.insertion);check('QA078 insertion retained '+doc.path,index!==-1);text=text.slice(0,index)+text.slice(index+doc.insertion.length);check('historical body '+doc.path,sha(text)===doc.bodyHash);}
for(let n=29;n<=36;n++){const p=base+'changes/CR-0'+n+'.md',text=readFileSync(join(root,p),'utf8'),front=YAML.parse(text.match(/^---\n([\s\S]*?)\n---/)[1]);check('resolved CR-0'+n,front.status==='resolved');}
const snapshots=[{"path":".planning/milestones/M001/verification/cr036-078-report.md","sha256":"fcf330d36bd1d5b2256535a8adf3af7280420949cd3748e5e432dd6df93a3395"},{"path":".planning/milestones/M001/verification/cr036-078-coverage.md","sha256":"d28c01c28de28b277528a84098e70e2ce37833c9e0c18f2077dc417c9eee23d3"},{"path":".planning/milestones/M001/verification/evidence/cr036-078/delivery-validation.json","sha256":"e0e41b64b07cfb9d8f2c2d4c0b5a2bfae48d907f618d72ba6b2d48135dea9694"},{"path":".planning/milestones/M001/verification/uat-079-handoff.md","sha256":"6dacf6eb76381003287af4584e0f359eac609e16505911634425dca891c95a60"},{"path":".planning/milestones/M001/verification/evidence/uat-079/deployment.json","sha256":"050c8b657cf7e2034f18c607341b430b13eeed24326c968e70b7beb63f5d7f99"},{"path":".planning/milestones/M001/verification/evidence/uat-079/smoke-final-results.json","sha256":"ebab1b0a1f5927de36dbc6a031cacfe32578b2553ce4d18fdc208925204e47bd"},{"path":".planning/milestones/M001/verification/report.md","sha256":"048f0fcd034e4ba0e5bb1a2d8dc089445f0b4690299a4bfe72758d4becafcf7e"},{"path":".planning/milestones/M001/verification/uat.md","sha256":"265d12b8f3424d34ca3ad11f3f6810e72ffceb4b4d0d3646c8b8931720e8ec5c"},{"path":".planning/milestones/M001/handoffs/verification.md","sha256":"630ae1f6f041b2f91ad000e6537cfe8dab6b572b91d383cff85d45aa2a790b21"}];for(const s of snapshots)check('snapshot '+s.path,sha(readFileSync(join(root,s.path)))===s.sha256);
const broken=[];for(const p of [base+'verification/uat-079-handoff.md']){const t=readFileSync(join(root,p),'utf8');for(const m of t.matchAll(/\]\(([^)]+)\)/g)){const url=m[1];if(!/^(https?:|#)/.test(url)&&!existsSync(resolve(root,dirname(p),url.split('#')[0])))broken.push(url);}}
check('UAT guide local links',broken.length===0);
check('existing 78 transition records append-only candidate',history.transitions.length===78&&history.transitions.at(-1).id==='TRANSITION-M001-078');
const now=new Date().toISOString(),record={id:'TRANSITION-M001-079',from:'verification',to:'verification',operation:'transition-stage',decision:'remain_in_current_stage',previous_role:'quality/base',previous_agent:'qa-quinn',active_role:'quality/base',active_agent:'qa-quinn',confirmed_by:'user',authorization:'依据077记录的连续批准接收QA078与UAT079交付；只批准已验功能UAT交接，不代表用户验收或发布通过。',decision_id:'TRANSITION-M001-079',timestamp:now,evidence:base+'reviews/verification-local-uat-handoff-approval.md',approved_artifacts:snapshots.map(s=>s.path),resolved_change_requests:Array.from({length:8},(_,i)=>'CR-0'+(29+i)),functional_uat:'awaiting_user_acceptance',release_readiness:'blocked',next_action:'Wait for user UAT feedback; continuous handoff authorization has reached its terminal boundary.'};
const next={...state,status:'awaiting_user_review',open_change_requests:[],last_transition:{...record},uat:{id:'UAT-M001-079',url:'http://localhost:6001',handoff:base+'verification/uat-079-handoff.md',functional_status:'awaiting_user_acceptance',user_accepted:false,release_readiness:'blocked',real_ai:'not_verified',frontend_image:candidate.frontend,backend_image:candidate.backend}};
delete next.last_transition.id;
const out={date:now,agent:'gatekeeper-owen',validated:true,checks,productionBaselineFiles:production.length,snapshots,oldStateSha256:sha(stateText),oldHistorySha256:sha(historyText),oldHistoryBytes:Buffer.byteLength(historyText),newState:YAML.stringify(next,{lineWidth:0,aliasDuplicateObjects:false}),historyAppend:'\n'+YAML.stringify([record],{lineWidth:0,aliasDuplicateObjects:false}).split('\n').filter((l,i,a)=>i!==a.length-1||l!=='').map(l=>'  '+l).join('\n')+'\n'};
writeFileSync(join(dir,'gate-preflight.json'),JSON.stringify({...out,newState:undefined,historyAppend:undefined},null,2),{flag:'wx'});console.log(JSON.stringify(out));
