import {createServer} from 'node:http';
import {readFileSync} from 'node:fs';
import {expect,start,stop,login,ok,call,sql,origin,out,dump,randomUUID,env} from './harness.mjs';
const passage='A thoughtful student learns(learn) by building a steady learning(learn) routine through daily reading and discussion. Each morning the student reviews a few ideas, connects them with practical examples, and writes a short reflection. Friends later compare their observations, ask clear questions, and share useful explanations about what they learned(learn). This patient practice makes new knowledge easier to remember and apply with confidence.';
let mode='valid',calls=0,action='SETUP';const results=[],samples=[],held=new Set();
const provider=createServer(async(req,res)=>{if(req.url!=='/chat/completions'){res.writeHead(404);res.end();return;}for await(const chunk of req){}calls++;if(mode==='http-failure'){res.writeHead(503,{'content-type':'application/json'});res.end(JSON.stringify({error:{message:'local provider unavailable'}}));return;}res.setHeader('content-type','text/event-stream');if(mode==='hold'){held.add(res);res.on('close',()=>held.delete(res));res.write('data: '+JSON.stringify({choices:[{delta:{content:'{"passage":"A'}}]})+'\n\n');return;}const candidate=mode==='invalid'?{passage:'Too short.',tags:['study'],targets:{}}:{passage,tags:['study'],targets:{learn:{entry_meaning:'gain knowledge through study',hint_phrase:'learning(learn) through learned(learn) examples while learning(learn)'}}};res.end('data: '+JSON.stringify({choices:[{delta:{content:JSON.stringify(candidate)}}]})+'\n\ndata: [DONE]\n\n');});
await new Promise(r=>provider.listen(38082,'127.0.0.1',r));const browser=await start(),admin=await browser.newContext(),user=await browser.newContext(),other=await browser.newContext();const fixture=JSON.parse(readFileSync(new URL('fixture.json',out))),modelId=fixture.modelId,body={model_id:modelId,meaning_language:'en',scenario:'story',length:'short',entries:['learn']};let owner,extraItem;
async function test(id,name,fn){action=id;try{await fn();results.push({id,name,result:'PASS'});}catch(e){results.push({id,name,result:'FAIL',error:String(e)});}dump('generation-results.json',{results,samples,localProviderCalls:calls,realProviderCalls:0});console.log(id,results.at(-1).result);}
const register=async(c,k)=>(await ok(c,'/auth/register','POST',{username:'qa6_'+k+'_'+Date.now(),password:env.ADMIN_PASSWORD,password_confirmation:env.ADMIN_PASSWORD,ui_locale:'en-US'})).actor.id;
async function raw(c,path,method,data,extra={}){const headers={origin,'sec-fetch-site':'same-origin',...extra};if(method!=='GET')headers['x-csrf-token']=(await ok(c,'/bootstrap')).csrf_token;return c.request.fetch(origin+'/api/v1'+path,{method,data,headers});}
const charge=id=>JSON.parse(sql(`SELECT row_to_json(c) FROM (SELECT run_id,source_kind,plan_code,origin,item_id,state,units FROM wordweave.generation_charges WHERE run_id='${id}') c`));
const stats=()=>ok(user,'/me/learning-summary');
async function stream(){const csrf=(await ok(user,'/bootstrap')).csrf_token,cookies=(await user.cookies(origin)).map(x=>x.name+'='+x.value).join('; '),controller=new AbortController();let resolveStart,rejectStart;const started=new Promise((r,j)=>{resolveStart=r;rejectStart=j;});const events=[];const response=await fetch('http://127.0.0.1:38081/api/v1/generations/stream',{method:'POST',headers:{origin,'sec-fetch-site':'same-origin','content-type':'application/json','x-csrf-token':csrf,cookie:cookies},body:JSON.stringify(body),signal:controller.signal});expect(response.status).toBe(200);const reader=response.body.getReader(),decoder=new TextDecoder();const done=(async()=>{let pending='';try{while(true){const {value,done}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});let at;while((at=pending.indexOf('\n\n'))>=0){const piece=pending.slice(0,at);pending=pending.slice(at+2);const name=piece.split('\n').find(x=>x.startsWith('event:'))?.slice(6).trim(),data=piece.split('\n').find(x=>x.startsWith('data:'))?.slice(5).trim();if(!name||!data)continue;const event={event:name,data:JSON.parse(data)};events.push(event);if(name==='generation.started')resolveStart(event.data);}}return {events};}catch(e){rejectStart(e);return{events,interrupted:true};}})();return{...(await started),events,done,abort:()=>controller.abort()};}
const runCall=(s,c,path)=>raw(c,'/generations/'+s.run_id+path,'POST',{}, {'X-Generation-Token':s.generation_token});
async function failed(s,kind){await s.done;const ends=s.events.filter(x=>/^generation\.(validated|failed|cancelled)$/.test(x.event));expect(ends.map(x=>x.event)).toEqual(['generation.failed']);expect(ends[0].data.quota_refunded).toBe(true);await expect.poll(()=>charge(s.run_id).state).toBe('refunded');const saved=await runCall(s,user,'/save');expect(saved.status()).toBe(409);samples.push({action,kind,terminal:ends[0],charge:charge(s.run_id),saveRejected:saved.status()});}
try{await login(admin);owner=await register(user,'quota');await register(other,'quota_other');
 await test('G01','Vocabulary lookup and generation precheck do not consume quota',async()=>{const before=await ok(user,'/generation-options'),n=calls,count=sql(`SELECT count(*) FROM wordweave.generation_charges WHERE account_id='${owner}'`);for(const q of ['learn','LEARN'])expect((await ok(user,'/vocabulary/search?q='+q)).items[0].entry).toBe('learn');for(const bad of [{...body,entries:['learn','learn']},{...body,entries:['not-a-vocabulary-entry']},{...body,length:'nonexistent'},{...body,prompt:'not allowed'}]){const r=await call(user,'/generations/stream','POST',bad);expect(r.status).toBe(422);}expect((await ok(user,'/generation-options')).quota).toEqual(before.quota);expect(calls).toBe(n);expect(sql(`SELECT count(*) FROM wordweave.generation_charges WHERE account_id='${owner}'`)).toBe(count);samples.push({action,invalidRequests:4,providerCalls:0,chargesUnchanged:true});});
 await test('G02','Active-run conflict and explicit cancellation charge once without check-in',async()=>{mode='hold';const before=await stats(),options=await ok(user,'/generation-options'),n=calls,s=await stream();await expect.poll(()=>calls).toBe(n+1);expect((await call(user,'/generations/stream','POST',body)).status).toBe(409);expect((await runCall(s,other,'/cancel')).status()).toBe(404);const cancel=await runCall(s,user,'/cancel');expect(cancel.status()).toBe(200);expect((await cancel.json()).data).toEqual({status:'cancelled',quota_refunded:false});await s.done;expect(s.events.filter(x=>/^generation\.(validated|failed|cancelled)$/.test(x.event)).map(x=>x.event)).toEqual(['generation.cancelled']);expect(charge(s.run_id)).toMatchObject({source_kind:'plan',origin:'base',state:'consumed'});for(let i=0;i<2;i++)expect((await(await runCall(s,user,'/cancel')).json()).data).toEqual({status:'cancelled',quota_refunded:false});expect((await runCall(s,user,'/save')).status()).toBe(409);expect((await stats()).generation_count).toBe(before.generation_count+1);expect((await ok(user,'/generation-options')).quota.remaining).toBe(options.quota.remaining-1);expect((await ok(user,'/me/growth')).checkin.signed_today).toBe(false);samples.push({action,charge:charge(s.run_id),signedToday:false,conflict:409,crossOwner:404,terminal:'cancelled'});});
 await test('G03','Provider and content-validation failures refund base source once',async()=>{for(const kind of ['http-failure','invalid']){mode=kind;const before=await stats(),options=await ok(user,'/generation-options'),n=calls,s=await stream();await failed(s,kind);expect(await stats()).toEqual(before);expect((await ok(user,'/generation-options')).quota).toEqual(options.quota);expect((await ok(user,'/me/growth')).checkin.signed_today).toBe(false);expect(calls-n).toBeLessThanOrEqual(3);const repeated=await runCall(s,user,'/cancel');expect((await repeated.json()).data).toEqual({status:'failed',quota_refunded:true});expect(charge(s.run_id)).toMatchObject({source_kind:'plan',origin:'base',state:'refunded'});}});
 await test('G04','Transport interruption differs from explicit cancellation and refunds once',async()=>{mode='hold';const before=await stats(),options=await ok(user,'/generation-options'),n=calls,s=await stream();await expect.poll(()=>calls).toBe(n+1);s.abort();await s.done;await expect.poll(()=>charge(s.run_id).state,{timeout:15000}).toBe('refunded');expect(await stats()).toEqual(before);expect((await ok(user,'/generation-options')).quota).toEqual(options.quota);expect((await runCall(s,user,'/save')).status()).toBe(409);samples.push({action,charge:charge(s.run_id),generationCountUnchanged:true});});
 await test('G05','Valid generation then discard remains charged and automatically checked in',async()=>{mode='valid';const before=await stats(),s=await stream();await s.done;expect(s.events.filter(x=>/^generation\.(validated|failed|cancelled)$/.test(x.event)).map(x=>x.event)).toEqual(['generation.validated']);expect((await runCall(s,user,'/discard')).status()).toBe(204);expect((await runCall(s,user,'/save')).status()).toBe(409);expect(charge(s.run_id).state).toBe('consumed');expect((await stats()).generation_count).toBe(before.generation_count+1);expect((await ok(user,'/me/growth')).checkin.signed_today).toBe(true);expect((await ok(user,'/me/batches')).items).toEqual([]);samples.push({action,charge:charge(s.run_id),signedToday:true,savedBatches:0});});
 await test('G06','Extra-credit failures refund the original card and cancellation consumes it once',async()=>{const created=await ok(admin,'/admin/growth/items','POST',{kind:'extra_credit',name:{zh_CN:null,en_US:'QA06 extra credits'},description:{zh_CN:null,en_US:'Local quota settlement fixture'},exchange_price:'0',activation_ttl_seconds:3600,effect:{kind:'extra_credit',extra_count:5}});await ok(admin,'/admin/growth/items/'+created.item.id+'/listing','PUT',{listed:true,expected_revision:created.revision});extraItem=(await ok(user,'/shop/exchanges','POST',{definition_id:created.item.id,quantity:1},randomUUID())).receipt.items[0].item_id;const preview=await ok(user,'/me/items/'+extraItem+'/activation-preview','POST',{});await ok(user,'/me/items/'+extraItem+'/activate','POST',{confirmation_token:preview.confirmation_token,confirm_discard:false},randomUUID());const groups=await ok(admin,'/admin/groups'),basic=groups.items.find(x=>x.code==='basic');await ok(admin,'/admin/groups/basic','PUT',{expected_revision:groups.revision,priority:basic.priority,max_entries:5,rolling_24h_limit:0,model_ids:[modelId],allowed_lengths:['short']});const balance=()=>JSON.parse(sql(`SELECT row_to_json(b) FROM (SELECT remaining_count,expires_at FROM wordweave.extra_credit_balances WHERE item_id='${extraItem}') b`));const before=balance();expect(before.remaining_count).toBe(5);mode='http-failure';const fail=await stream();await failed(fail,'extra HTTP failure');expect(charge(fail.run_id)).toMatchObject({source_kind:'extra_credit',item_id:extraItem,state:'refunded'});expect(balance()).toEqual(before);await runCall(fail,user,'/cancel');expect(balance()).toEqual(before);mode='hold';const n=calls,s=await stream();await expect.poll(()=>calls).toBe(n+1);await runCall(s,user,'/cancel');await s.done;expect(charge(s.run_id)).toMatchObject({source_kind:'extra_credit',item_id:extraItem,state:'consumed'});expect(balance()).toEqual({...before,remaining_count:4});expect((await ok(user,'/generation-options')).extra_quota.remaining).toBe(4);samples.push({action,failSource:charge(fail.run_id),cancelSource:charge(s.run_id),before,after:balance()});});
}catch(e){results.push({id:'SETUP',result:'FAIL',error:String(e)});console.log(String(e));}
finally{dump('generation-results.json',{results,samples,localProviderCalls:calls,realProviderCalls:0});await stop(browser);for(const res of held)res.destroy();await new Promise(r=>provider.close(r));console.log(JSON.stringify(results,null,2));if(results.some(x=>x.result==='FAIL'))process.exitCode=1;}
