import {createServer} from 'node:http';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {expect,start,stop,login,ok,call,sql,origin,out,t,dump,ready,instrument,randomUUID,env} from './harness.mjs';
let calls=0,action='SETUP';const results=[],samples=[],runtime=[];
const passage='A thoughtful student learns(learn) by building a steady learning(learn) routine through daily reading and discussion. Each morning the student reviews a few ideas, connects them with practical examples, and writes a short reflection. Friends later compare their observations, ask clear questions, and share useful explanations about what they learned(learn). This patient practice makes new knowledge easier to remember and apply with confidence.';
const provider=createServer(async(req,res)=>{if(req.url==='/models'){res.setHeader('content-type','application/json');res.end(JSON.stringify({data:[{id:'provider/integration',supported_parameters:['structured_outputs']}]}));return;}if(req.url!=='/chat/completions'){res.writeHead(404);res.end();return;}let body='';for await(const c of req)body+=c;calls++;const probe=JSON.parse(body).messages.some(m=>m.content.includes('fixed compatibility probe'));const candidate={passage:passage+(probe?' The group also discussed vulnerability(vulnerable) with empathy.':''),tags:['study'],targets:{learn:{entry_meaning:'gain knowledge through study',hint_phrase:'learning(learn) through learned(learn) examples while learning(learn)'}}};if(probe)candidate.targets.vulnerable={entry_meaning:'open to harm',hint_phrase:'vulnerable(vulnerable) communities'};res.setHeader('content-type','text/event-stream');res.end('data: '+JSON.stringify({choices:[{delta:{content:JSON.stringify(candidate)}}]})+'\n\ndata: [DONE]\n\n');});
await new Promise(r=>provider.listen(38082,'127.0.0.1',r));
const browser=await start(),admin=await browser.newContext(),user=await browser.newContext(),other=await browser.newContext(),page=await user.newPage();instrument(page,runtime,()=>action);
const copy=JSON.parse(readFileSync('.planning/milestones/M002/design/copy.json')),tr=(lang,k)=>copy.static[lang+'.'+k]??copy.templates[lang+'.'+k];
async function test(id,name,fn){action=id;try{await fn();results.push({id,name,result:'PASS'});}catch(e){results.push({id,name,result:'FAIL',error:String(e)});await page.screenshot({path:new URL(id+'-failure.png',out).pathname,fullPage:true}).catch(()=>{});}dump('library-results.json',{results,localProviderCalls:calls,realProviderCalls:0});console.log(id,results.at(-1).result);}
async function raw(c,path,method,data,extra={}){const headers={origin,'sec-fetch-site':'same-origin',...extra};if(method!=='GET')headers['x-csrf-token']=(await ok(c,'/bootstrap')).csrf_token;return c.request.fetch(origin+'/api/v1'+path,{method,data,headers});}
let userId,modelId,otherId,ids=[],deletedId,otherBatch;
const register=async(c,name)=>(await ok(c,'/auth/register','POST',{username:'qa6_'+name+'_'+Date.now(),password:env.ADMIN_PASSWORD,password_confirmation:env.ADMIN_PASSWORD,ui_locale:'en-US'})).actor.id;
async function generate(c){const r=await raw(c,'/generations/stream','POST',{model_id:modelId,meaning_language:'en',scenario:'story',length:'short',entries:['learn']});expect(r.status()).toBe(200);const events=(await r.text()).split('\n\n').filter(x=>x.startsWith('event:')).map(x=>{const lines=x.split('\n');return{event:lines[0].slice(7),data:JSON.parse(lines.find(x=>x.startsWith('data:')).slice(6))}});expect(events.filter(x=>/^generation\.(validated|failed|cancelled)$/.test(x.event)).map(x=>x.event)).toEqual(['generation.validated']);const s=events.find(x=>x.event==='generation.started').data;const saved=await raw(c,'/generations/'+s.run_id+'/save','POST',{}, {'X-Generation-Token':s.generation_token});expect(saved.status()).toBe(201);return(await saved.json()).data.batch_id;}
const listed=r=>r.body.data.items.map(x=>x.id);
const query=(entry,cursor='')=>'/me/batches?limit=1&entry='+encodeURIComponent(entry)+(cursor?'&cursor='+encodeURIComponent(cursor):'');
async function search(p,lang,entry){const wait=p.waitForResponse(r=>r.url().includes('/api/v1/me/batches?')&&new URL(r.url()).searchParams.get('entry')===entry.trim());await p.getByRole('searchbox').fill(entry);await p.getByRole('button',{name:tr(lang,'l.searchAction'),exact:true}).click();expect((await wait).status()).toBe(200);await expect(p.locator('.library-row')).toHaveCount(20);}
try{
 await login(admin);const cred=await ok(admin,'/admin/openrouter-credential');await ok(admin,'/admin/openrouter-credential','PUT',{api_key:'qa6-local-only-key',confirmed:true,expected_revision:cred.revision});const m=await ok(admin,'/admin/models','POST',{display_name:'QA06 deterministic provider',description:'Isolated local fixture',openrouter_model_id:'provider/integration'});modelId=m.model.id;await ok(admin,'/admin/models/'+modelId+'/enable','POST',{expected_revision:m.revision});const g=await ok(admin,'/admin/groups'),b=g.items.find(x=>x.code==='basic');await ok(admin,'/admin/groups/basic','PUT',{expected_revision:g.revision,priority:b.priority,max_entries:5,rolling_24h_limit:50,model_ids:[modelId],allowed_lengths:['short']});
 sql("UPDATE wordweave.growth_settings SET activated_at=clock_timestamp()-interval '60 days'; INSERT INTO wordweave.growth_levels(level_no,min_experience,reward_enabled,points) VALUES(1,0,false,0) ON CONFLICT(level_no) DO NOTHING; INSERT INTO wordweave.checkin_rules(effective_day,base_points,step_points,cap_points,normal_experience) VALUES(CURRENT_DATE-60,1,1,7,1) ON CONFLICT(effective_day) DO NOTHING");
 userId=await register(user,'library');otherId=await register(other,'other');for(let i=0;i<22;i++)ids.push(await generate(user));deletedId=ids.pop();otherBatch=await generate(other);const first=(await ok(user,'/me/batches/'+ids[0])).batch;await ok(user,'/me/batches/'+ids[0],'PATCH',{title:'book',expected_title_revision:first.title_revision});await ok(user,'/me/batches/'+ids[1],'PATCH',{participates_in_range_review:false});await ok(user,'/me/batches/'+deletedId,'DELETE',{});
 const stats=await ok(user,'/me/learning-summary');dump('fixture.json',{userId,otherId,modelId,ids,deletedId,otherBatch,stats});
 await test('L01','CR011 normalized exact search and bidirectional cursor continuity',async()=>{for(const entry of ['learn','LEARN','Learn',' \tLeArN\n','\u00a0LEARN\u00a0']){const all=await call(user,'/me/batches?entry='+encodeURIComponent(entry)+'&limit=100');expect(all.status).toBe(200);expect(listed(all)).toEqual(ids);const first=await call(user,query(entry));expect(first.status).toBe(200);const next=await call(user,query(entry==='learn'?' LEARN ':'learn',first.body.meta.next_cursor));expect(next.status).toBe(200);expect([...listed(first),...listed(next)]).toEqual(ids.slice(0,2));expect(next.body.data.items[0].participates_in_range_review).toBe(false);samples.push({action,entry,status:all.status,count:listed(all).length,firstTwo:[...listed(first),...listed(next)]});}});
 await test('L02','CR011 invalid filter/cursor, exact targets and ownership boundaries',async()=>{const first=await call(user,query('LEARN')),cursor=first.body.meta.next_cursor;for(const entry of ['book','','lear'])expect((await call(user,query(entry,cursor))).status).toBe(422);expect((await call(other,query('LEARN',cursor))).status).toBe(422);expect((await call(user,query('learn','invalid'))).status).toBe(422);for(const entry of ['book','study'])expect((await ok(user,'/me/batches?entry='+entry)).items).toEqual([]);for(const entry of ['lear','le arn','learn%',' \t\n'])expect((await call(user,query(entry))).status).toBe(422);expect((await ok(other,'/me/batches?entry=LEARN')).items.map(x=>x.id)).toEqual([otherBatch]);expect((await call(other,'/me/batches/'+ids[0])).status).toBe(404);expect((await call(user,'/me/batches/'+deletedId)).status).toBe(404);expect((await call(admin,'/me/batches?entry=LEARN')).status).toBe(403);expect((await call(await browser.newContext(),'/me/batches?entry=LEARN')).status).toBe(401);expect(await ok(user,'/me/learning-summary')).toEqual(stats);samples.push({action,ownerIsolation:true,deletedExcluded:true,titleAndTagsExcluded:true,statisticsUnchanged:true});});
 await test('L03','Actual bilingual mobile/desktop uppercase search and load more',async()=>{for(const lang of ['en','zh']){await ok(user,'/me/ui-locale','PUT',{ui_locale:lang==='en'?'en-US':'zh-CN'});for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await page.goto(origin+'/library');await ready(page);await expect(page.locator('h1')).toHaveText(tr(lang,'l.library'));await expect(page.locator('.library-stats > div')).toHaveCount(6);for(const entry of ['LEARN','Learn',' learn ']){await search(page,lang,entry);await page.getByRole('button',{name:tr(lang,'l.more'),exact:true}).click();await expect(page.locator('.library-row')).toHaveCount(21);expect(await page.locator('.library-row').evaluateAll(es=>es.map(e=>e.dataset.batch))).toEqual(ids);await expect(page.getByRole('button',{name:tr(lang,'l.more'),exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);}await page.screenshot({path:new URL(`L03-${lang}-${width}.png`,out).pathname,fullPage:true});samples.push({action,lang,width,searchVariants:3,visibleRows:21,duplicateRows:0});}}});
 await test('L04','Detail round trip retains uppercase query, loaded range and focused row',async()=>{await ok(user,'/me/ui-locale','PUT',{ui_locale:'en-US'});await page.setViewportSize({width:1280,height:900});await page.goto(origin+'/library');await ready(page);await search(page,'en','LEARN');await page.getByRole('button',{name:t('l.more'),exact:true}).click();await expect(page.locator('.library-row')).toHaveCount(21);const row=page.locator('.library-row').last();await row.locator('h2 a').click();await expect(page).toHaveURL(new RegExp('/library/'+ids.at(-1)));await page.getByRole('link',{name:t('l.backLibrary'),exact:true}).click();await expect(page.getByRole('searchbox')).toHaveValue('LEARN');await expect(page.locator('.library-row')).toHaveCount(21);await expect(page.locator('.library-row').last().locator('h2 a')).toBeFocused();await expect(page.locator('.library-row').last().locator('h2 a')).toBeInViewport();samples.push({action,query:'LEARN',restoredRows:21,focusRestored:true});});
 await test('L05','No-result/clear search and all six statistics remain consistent',async()=>{await page.goto(origin+'/library');await ready(page);const shown=await page.locator('.library-stats dd').allTextContents();const response=page.waitForResponse(r=>r.url().includes('/api/v1/me/batches?')&&new URL(r.url()).searchParams.get('entry')==='book');await page.getByRole('searchbox').fill('book');await page.getByRole('button',{name:t('l.searchAction'),exact:true}).click();expect((await response).status()).toBe(200);await expect(page.getByText(t('l.noresults'),{exact:true})).toBeVisible();await expect(page.locator('.library-row')).toHaveCount(0);await page.getByRole('button',{name:t('l.clear'),exact:true}).click();await expect(page.getByRole('searchbox')).toHaveValue('');await expect(page.locator('.library-row')).toHaveCount(20);expect(await page.locator('.library-stats dd').allTextContents()).toEqual(shown);expect(await ok(user,'/me/learning-summary')).toEqual(stats);await page.screenshot({path:new URL('L05-cleared.png',out).pathname,fullPage:true});});
 await test('L06','Library search/list accessibility and browser runtime',async()=>{const AxeBuilder=createRequire(process.cwd()+'/frontend/package.json')('@axe-core/playwright').default;const scan=await new AxeBuilder({page}).include('.library-page').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();dump('library-axe.json',{violations:scan.violations,passes:scan.passes.map(x=>x.id)});expect(scan.violations).toEqual([]);expect(runtime).toEqual([]);});
}catch(e){results.push({id:'SETUP',result:'FAIL',error:String(e)});console.log(String(e));}
finally{dump('library-results.json',{results,samples,runtime,localProviderCalls:calls,realProviderCalls:0});await stop(browser);await new Promise(r=>provider.close(r));console.log(JSON.stringify(results,null,2));if(results.some(x=>x.result==='FAIL'))process.exitCode=1;}
