const {chromium,expect}=require('../../../../../frontend/node_modules/@playwright/test');const {default:AxeBuilder}=require('../../../../../frontend/node_modules/@axe-core/playwright');const fs=require('node:fs'),path=require('node:path');
const out={version:'M002-UI-19',scope:'Top-layer toast visibility during modal notifications, five-second lifetime, focus, resize and shared feedback.',checks:[],layouts:[],axe:[]};
const visit=async(p,q={})=>{await p.goto('http://127.0.0.1:4174/prototype/?'+new URLSearchParams({page:'login',role:'guest',lang:'zh',v:out.version,...q}));await p.locator('#main').waitFor()};
const action=(p,a)=>p.locator(`[data-action="${a}"]:visible`).first().click();
const login=async(p,q={})=>{await visit(p,q);await p.fill('#auth-username','learner');await p.fill('#auth-password','prototype-example');await action(p,'identity-submit');await p.locator('#toast.visible').waitFor();const shown=Date.now();await p.locator('#dialog[open]').waitFor();return shown};
const clear=async p=>{const a=await p.locator('#toast').boundingBox(),d=await p.locator('#dialog').boundingBox();expect(a).not.toBeNull();expect(d).not.toBeNull();expect(a.y).toBeGreaterThanOrEqual(d.y+d.height+8);expect(a.x).toBeGreaterThanOrEqual(0);expect(a.x+a.width).toBeLessThanOrEqual(await p.evaluate(()=>innerWidth));expect(a.y+a.height).toBeLessThanOrEqual(await p.evaluate(()=>innerHeight));return {toast:a,dialog:d}};
(async()=>{const b=await chromium.launch();out.browser=b.version();async function check(name,fn,motion='reduce'){const c=await b.newContext({viewport:{width:1440,height:900},reducedMotion:motion}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});try{await fn(p,c);expect(errors).toEqual([]);out.checks.push({name,status:'PASS'})}catch(e){out.checks.push({name,status:'FAIL',error:e.message,errors});await p.screenshot({path:path.join(__dirname,`UI19-failure-${out.checks.length}.png`),fullPage:false})}await c.close();console.log(name,out.checks.at(-1).status)}
await check('Welcome remains above the modal; bilingual mobile and desktop layouts/accessibility',async(p,c)=>{
 for(const [width,height] of [[320,568],[390,844],[1440,900]])for(const lang of ['zh','en']){await p.setViewportSize({width,height});await login(p,{lang});await expect(p.locator('#toast')).toHaveText(lang==='zh'?'欢迎回来，小涟，距离上一次学习已经过去了 2 天':'Welcome back, 小涟. It has been 2 learning days since your last session.');expect(await p.locator('#toast').evaluate(e=>e.matches(':popover-open')&&e.parentElement.id==='dialog')).toBe(true);expect(await p.locator('#toast').evaluate(e=>getComputedStyle(e).pointerEvents)).toBe('none');await expect(p.locator('.dialog-close')).toBeFocused();const boxes=await clear(p);out.layouts.push({width,height,lang,...boxes});await p.screenshot({path:path.join(__dirname,`UI19-welcome-${width}-${lang}.png`),fullPage:false});if((width===320&&lang==='zh')||(width===1440&&lang==='en')){const r=await new AxeBuilder({page:p}).analyze();out.axe.push({width,lang,violations:r.violations});expect(r.violations).toEqual([])}}
 // The live status remains exposed inside the modal, rather than in the inert page.
 await login(p);const client=await c.newCDPSession(p);const doc=await client.send('DOM.getDocument');const {nodeId}=await client.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'#toast'});const ax=await client.send('Accessibility.getPartialAXTree',{nodeId});const status=ax.nodes.find(n=>n.role?.value==='status');expect(status?.ignored).toBe(false);out.liveStatus={role:status.role.value,ignored:status.ignored};await client.detach();
});
await check('Pagination, Escape and reopening preserve one toast and its original five-second deadline',async p=>{
 const started=await login(p);const text=await p.locator('#toast').textContent();await p.locator('#dialog').getByRole('button',{name:'下一步',exact:true}).click();await expect(p.locator('#toast')).toHaveCount(1);await expect(p.locator('#toast')).toHaveText(text);expect(await p.locator('#toast').evaluate(e=>e.matches(':popover-open'))).toBe(true);await p.waitForTimeout(1300);await p.keyboard.press('Escape');await expect(p.locator('#dialog')).not.toBeVisible();await expect(p.locator('#toast')).toBeVisible();expect(await p.locator('#toast').evaluate(e=>e.parentElement===document.body)).toBe(true);await p.locator('.header-actions [data-go="notices"]').click();await p.locator('[data-action^="notice:"]').first().click();await expect(p.locator('#dialog')).toBeVisible();await expect(p.locator('#toast')).toBeVisible();await expect(p.locator('#toast')).toBeHidden({timeout:6000});const elapsed=Date.now()-started;expect(elapsed).toBeGreaterThan(4700);expect(elapsed).toBeLessThan(5800);out.lifetime_ms=elapsed;await expect(p.locator('#dialog')).toBeVisible();await expect(p.locator('#dialog')).not.toHaveClass(/with-toast-space/);
});
await check('Resize and normal animation retain centering, visibility and usable modal controls',async p=>{
 await login(p);await p.setViewportSize({width:320,height:568});await p.waitForTimeout(280);await clear(p);await p.locator('#dialog').getByRole('button',{name:'下一步',exact:true}).click();await p.waitForTimeout(280);await clear(p);await p.locator('.dialog-close').click();await expect(p.locator('#dialog')).not.toBeVisible();await expect(p.locator('#toast')).toBeVisible();
},'no-preference');
await check('Shared nonmodal save toast and modal failure feedback keep their original actions',async p=>{
 await visit(p,{page:'profile',role:'learner'});await p.fill('#nickname','小树');await action(p,'profile-save');await expect(p.locator('#toast')).toContainText('保存');await expect(p.locator('.account-identity h2')).toHaveText('小树');expect(await p.locator('#toast').evaluate(e=>e.parentElement===document.body&&e.matches(':popover-open'))).toBe(true);
 await visit(p,{page:'library',role:'learner',state:'save-error'});await action(p,'learn-delete:b1');await action(p,'learn-delete-confirm');await expect(p.locator('#dialog')).toBeVisible();await expect(p.locator('#toast')).toContainText('失败');expect(await p.locator('#toast').evaluate(e=>e.parentElement.id==='dialog'&&e.matches(':popover-open'))).toBe(true);await expect(p.locator('.library-row')).toHaveCount(2);await p.keyboard.press('Escape');await expect(p.locator('#dialog')).not.toBeVisible();await expect(p.locator('[data-action="learn-delete:b1"]')).toBeFocused();await expect(p.locator('#toast')).toBeVisible();
});
await b.close();out.status=out.checks.every(x=>x.status==='PASS')?'PASS':'FAIL';fs.writeFileSync(path.join(__dirname,'UI19-browser-results.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,checks:out.checks,layouts:out.layouts.length,axe:out.axe.length,lifetime_ms:out.lifetime_ms}));process.exitCode=out.status==='PASS'?0:1})().catch(e=>{console.error(e);process.exit(1)});
