const {chromium,expect}=require('../../../../../frontend/node_modules/@playwright/test');
const {default:AxeBuilder}=require('../../../../../frontend/node_modules/@axe-core/playwright');
const fs=require('node:fs'),path=require('node:path');
const out={version:'M002-UI-09',scope:'Local design prototype: copy, alignment, responsive layouts and retained interactions. No live API.',checks:[],layouts:[],axe:[]};
const root=__dirname,base='http://127.0.0.1:4174/prototype/';
const visit=async(p,route,extra='')=>{const params=new URLSearchParams({page:route,role:'learner',lang:'zh',batch:'b1',v:'M002-UI-09'});for(const [k,v] of new URLSearchParams(extra))params.set(k,v);await p.goto(base+'?'+params);await p.locator('main h1:visible,main h2:visible').first().waitFor()};
const click=(p,a)=>p.locator('[data-action="'+a+'"]:visible').first().click();
(async()=>{const b=await chromium.launch();out.browser=b.version();
async function test(name,fn){if(process.env.UI09_TEST_FILTER&&!name.includes(process.env.UI09_TEST_FILTER))return;const c=await b.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});try{await fn(p);expect(errors).toEqual([]);out.checks.push({name,status:'PASS'});}catch(e){out.checks.push({name,status:'FAIL',error:e.message,errors});await p.screenshot({path:path.join(root,'UI09-failure-'+out.checks.length+'.png'),fullPage:true});}await c.close();console.log(name,out.checks.at(-1).status)}
await test('Authentication alignment, registration hints, validation and Enter login',async p=>{
 await visit(p,'login');await expect(p.locator('#auth-username-hint')).toHaveCount(0);const boxes=await Promise.all(['.auth-form h1','#auth-username','#auth-password','[data-action="identity-submit"]'].map(s=>p.locator(s).boundingBox()));expect(Math.max(...boxes.map(b=>b.x))-Math.min(...boxes.map(b=>b.x))).toBeLessThan(1);expect(boxes[1].width).toBeCloseTo(boxes[3].width,0);
 await p.fill('#auth-username','learner');await p.fill('#auth-password','correct_password');await p.locator('#auth-password').press('Enter');await expect(p.locator('#identity-form')).toHaveCount(0);await expect(p.locator('.account-dropdown')).toBeVisible();
 await visit(p,'register');await expect(p.locator('#auth-username')).toHaveAttribute('aria-describedby','auth-username-hint');await p.fill('#auth-username','new_reader');await p.fill('#auth-password','correct_password');await p.fill('#auth-confirm','other_password');await click(p,'identity-submit');await expect(p.locator('#auth-error')).not.toBeEmpty();await p.fill('#auth-confirm','correct_password');await click(p,'identity-submit');await expect(p.locator('#identity-form')).toHaveCount(0);
 await visit(p,'login','&state=auth-error');await p.fill('#auth-username','learner');await p.fill('#auth-password','incorrect_password');await click(p,'identity-submit');await expect(p.locator('#auth-error')).not.toBeEmpty();await expect(p.locator('[data-action="identity-submit"]')).toBeEnabled();
});
await test('Guest story claim remains visible on mobile login and collects on authentication',async p=>{
 await visit(p,'trial','&role=guest');await click(p,'generate');await expect(p.locator('[data-action="collect"]')).toBeVisible({timeout:15000});await click(p,'collect');await p.setViewportSize({width:390,height:900});await expect(p.locator('.auth-intent')).toBeVisible();await expect(p.locator('.auth-intent')).toContainText('短文');await p.screenshot({path:path.join(root,'UI09-claim-390.png'),fullPage:true});await p.fill('#auth-username','reader');await p.fill('#auth-password','correct_password');await click(p,'identity-submit');await expect(p.locator('#saved-batch-title')).toHaveText('resilient · wander · weave');
});
await test('Admin field alignment, user search, model editing and plan confirmation',async p=>{
 await visit(p,'users');const input=await p.locator('#admin-user-query').boundingBox(),btn=await p.locator('[data-action="adm-search"]').boundingBox();expect(Math.abs(input.y+input.height-btn.y-btn.height)).toBeLessThan(1);await p.fill('#admin-user-query','reader');await click(p,'adm-search');await expect(p.locator('[data-action^="adm-user:"]').first()).toBeVisible();
 await visit(p,'models');await click(p,'adm-model-new');await expect(p.locator('#admin-model-name')).toBeVisible();await p.fill('#admin-model-name','UI09 model');await p.fill('#admin-model-provider','provider/ui09');await click(p,'adm-model-save');await expect(p.locator('main')).toContainText('UI09 model');
 await visit(p,'plans');await expect(p.locator('.form-help')).not.toHaveAttribute('open','');await p.fill('#plan-limit','0');await click(p,'adm-plan-save');await expect(p.locator('#dialog')).toBeVisible();await expect(p.locator('#dialog .notice').first()).toBeVisible();await p.screenshot({path:path.join(root,'UI09-plan-confirm-1440.png'),fullPage:true});await click(p,'close');await p.check('#plan-unlimited');await expect(p.locator('#plan-limit')).toBeDisabled();
});
await test('Preset draft/publication and language filtering retain complete source and locked settings',async p=>{
 await visit(p,'presets');await p.fill('#preset-title','一次散步，一个故事');await click(p,'preset-save');await click(p,'preset-publish');await expect(p.locator('.admin-record.selected')).toContainText('已发布');await p.locator('#demo summary').click();await p.selectOption('#demo-page','explore');await expect(p.locator('.gallery-card h2').first()).toHaveText('一次散步，一个故事');await expect(p.locator('.gallery-passage').first().locator('p')).toHaveCount(3);
 await p.locator('[role="tab"][data-gallery-language="English"]').click();await expect(p.locator('.gallery-card')).toHaveAttribute('data-preset-index','1');await click(p,'try:1');await expect(p.locator('main h1')).toHaveText('一杯咖啡的时间');await expect(p.locator('.settings dd')).toHaveText(['Model B','Story','Brief','English']);await expect(p.locator('[data-region="generation-result"] .article')).toHaveCount(0);
 await visit(p,'explore');await p.locator('[role="tab"][data-gallery-language="all"]').focus();await p.keyboard.press('End');await expect(p.locator('[data-gallery-language="日本語"]')).toBeFocused();await expect(p.locator('.gallery-track')).toHaveCount(0);await p.keyboard.press('Home');await expect(p.locator('.gallery-card')).toHaveCount(2);
});
await test('Review incorrect-but-nonempty navigation, return/edit, overview and summary',async p=>{
 await visit(p,'review');await p.locator('.slot').first().fill('z');await click(p,'learn-next');await expect(p.locator('.slot').first()).toHaveValue('');await click(p,'learn-prev');await expect(p.locator('.slot').first()).toHaveValue('z');await click(p,'learn-overview');await expect(p.locator('.answer-link').first()).toHaveText('z ↗');await click(p,'learn-edit-word:0');await expect(p.locator('.slot').first()).toHaveValue('z');await click(p,'learn-overview');await click(p,'learn-submit');await expect(p.locator('.result-word').first().locator('s')).toHaveText('z');await expect(p.locator('.result-word').first()).toContainText(/resilient|wander|weave/);await expect(p.locator('[data-action="learn-advance"]')).toBeVisible();await p.screenshot({path:path.join(root,'UI09-summary-1440.png'),fullPage:true});
});
await test('All 28 views: 390/768/1440 Chinese and 1440 English, no page overflow or runtime errors',async p=>{
 const routes=['home','login','register','create','library','batch','range','review','overview','summary','sessiondone','profile','notices','growth','bag','shop','adminhome','metrics','models','plans','users','userdetail','operations','credits','messages','presets','explore','trial'];
 for(const [width,language] of [[390,'zh'],[768,'zh'],[1440,'zh'],[1440,'en']]){await p.setViewportSize({width,height:900});for(const route of routes){await p.goto(base+'?page='+route+'&role=learner&lang='+language+'&batch=b1&v=M002-UI-09');await p.locator('main h1:visible,main h2:visible').first().waitFor();const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);out.layouts.push({route,width,language,overflow});expect(overflow,route+' '+width+' '+language).toBe(false);}}
});
await test('Representative authentication, workspace, gallery and admin accessibility',async p=>{
 for(const [route,width] of [['login',1440],['register',390],['create',390],['review',390],['users',1440],['plans',1440],['messages',390],['presets',1440],['explore',390]]){await p.setViewportSize({width,height:900});await visit(p,route);const a=await new AxeBuilder({page:p}).analyze();out.axe.push({route,width,violations:a.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});expect(a.violations,route).toEqual([]);}
});
out.status=out.checks.every(x=>x.status==='PASS')?'PASS':'FAIL';await b.close();fs.writeFileSync(path.join(root,process.env.UI09_TEST_FILTER?'UI09-targeted-results.json':'UI09-browser-results.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,checks:out.checks,layouts:out.layouts.length,axe:out.axe.length}));process.exitCode=out.status==='PASS'?0:1;
})().catch(e=>{console.error(e);process.exit(1)});
