const {chromium,expect}=require('../../../../../frontend/node_modules/@playwright/test');
const {default:AxeBuilder}=require('../../../../../frontend/node_modules/@axe-core/playwright');
const fs=require('node:fs'),path=require('node:path');
const out={version:'M002-UI-14',scope:'Homepage float, animated layering, reading interruption, motion preference, responsive animation bounds and lifecycle.',checks:[],observations:[],layouts:[],axe:[]};
const retry=process.env.UI14_RETRY==='1';if(retry){const first=JSON.parse(fs.readFileSync(path.join(__dirname,'UI14-first-browser-results.json')));out.checks=first.checks.filter(x=>x.status==='PASS');out.layouts=first.layouts;out.axe=first.axe;out.retained_from='UI14-first-browser-results.json';}
const visit=async(p,q={})=>{await p.goto('http://127.0.0.1:4174/prototype/?'+new URLSearchParams({page:'home',role:'guest',lang:'zh',v:'M002-UI-14',...q}));await p.locator('.home-card-stack').waitFor()};
const motion=p=>p.locator('.home-paper').evaluateAll(es=>es.map(e=>({translate:getComputedStyle(e).translate,transform:getComputedStyle(e).transform,animations:e.getAnimations().map(a=>({playState:a.playState,currentTime:a.currentTime}))})));
(async()=>{const b=await chromium.launch();async function check(name,fn,opts={}){if(retry&&!name.startsWith('Real idle')&&!name.startsWith('Animated phone'))return;const c=await b.newContext({viewport:{width:1440,height:900},reducedMotion:'no-preference',...opts}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{await fn(p);expect(errors).toEqual([]);out.checks.push({name,status:'PASS'})}catch(e){out.checks.push({name,status:'FAIL',error:e.message,errors});await p.screenshot({path:path.join(__dirname,'UI14-failure-'+out.checks.length+'.png'),fullPage:true})}const video=p.video();await c.close();if(video){const from=await video.path();fs.renameSync(from,path.join(__dirname,'UI14-motion-1440.webm'))}console.log(name,out.checks.at(-1).status)}
await check('Real idle float and automatic 8-second layered turn; reading stops movement',async p=>{
 await p.mouse.move(0,0);await visit(p);const stack=p.locator('.home-card-stack');await expect(stack).toHaveAttribute('data-motion','running');const start=await motion(p);await p.waitForTimeout(1300);const floated=await motion(p);expect(start.map(x=>x.translate)).not.toEqual(floated.map(x=>x.translate));out.observations.push({name:'Float frames 1.3s apart',start,floated});
 await expect(stack).toHaveAttribute('data-switching','true',{timeout:8500});await p.waitForTimeout(150);const during=await motion(p);await p.screenshot({path:path.join(__dirname,'UI14-turn-midpoint-1440.png'),fullPage:true});await expect(stack).toHaveAttribute('data-top','0');await expect(stack).toHaveAttribute('data-switching','false');out.observations.push({name:'Real first automatic turn',during,settled:await motion(p)});
 const readBox=await p.locator('.home-paper-back h2').boundingBox();await p.mouse.move(readBox.x+readBox.width/2,readBox.y+readBox.height/2);await expect(stack).toHaveAttribute('data-motion','paused');await p.mouse.move(0,0);const paused=await motion(p);await p.waitForTimeout(8500);expect(await motion(p)).toEqual(paused);await expect(stack).toHaveAttribute('data-top','0');await p.screenshot({path:path.join(__dirname,'UI14-reading-1440.png'),fullPage:true});
},{recordVideo:{dir:__dirname,size:{width:1440,height:900}}});
await check('Manual layering, rapid keyboard changes, live reduced-motion and reentry cleanup',async p=>{
 await visit(p);const stack=p.locator('.home-card-stack');await p.locator('.home-paper-back').focus();await expect(stack).toHaveAttribute('data-switching','true');await p.waitForTimeout(120);out.observations.push({name:'Manual turn intermediate transform',cards:await motion(p)});await p.keyboard.press('Tab');await expect(p.locator('.home-paper-front')).toBeFocused();await expect(stack).toHaveAttribute('data-top','1');await p.keyboard.press('Shift+Tab');await expect(stack).toHaveAttribute('data-switching','true');await p.emulateMedia({reducedMotion:'reduce'});await expect(stack).toHaveAttribute('data-top','0');await expect(stack).toHaveAttribute('data-motion','reduced');await expect(stack).toHaveAttribute('data-switching','false');expect(await p.locator('.home-paper').evaluateAll(es=>es.map(e=>e.getAnimations().length))).toEqual([0,0]);await p.keyboard.press('Tab');await expect(stack).toHaveAttribute('data-top','1');const still=await motion(p);await p.waitForTimeout(650);expect(await motion(p)).toEqual(still);
 await p.emulateMedia({reducedMotion:'no-preference'});await expect(stack).toHaveAttribute('data-motion','paused');await p.locator('[data-action="language"]').click();await expect(stack).toHaveAttribute('data-motion','paused');await p.locator('.nav [data-go="explore"]').click();await expect(stack).toHaveCount(0);expect(await p.evaluate(()=>document.getAnimations().filter(a=>a.effect?.target?.classList.contains('home-paper')).length)).toBe(0);await p.locator('.nav [data-go="home"]').click();await expect(stack).toHaveAttribute('data-motion','running');await expect(stack).toHaveAttribute('data-top','1');
});
await check('Animated phone bounds, tap-to-read, unchanged stories and accessible layout',async p=>{
 for(const [width,lang] of [[320,'zh'],[320,'en'],[390,'zh'],[390,'en'],[768,'zh'],[1440,'en']]){
  await p.setViewportSize({width,height:900});await visit(p,{lang});await p.locator('.home-paper-back h2').evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));const tapBox=await p.locator('.home-paper-back h2').boundingBox();await p.touchscreen.tap(tapBox.x+tapBox.width/2,tapBox.y+tapBox.height/2);await expect(p.locator('.home-paper-back')).toBeFocused();const samples=await p.evaluate(()=>new Promise(resolve=>{const frames=[],start=performance.now();function sample(){const cards=[...document.querySelectorAll('.home-paper')].map(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right}});frames.push({overflow:document.documentElement.scrollWidth>innerWidth,cards});if(performance.now()-start<750)requestAnimationFrame(sample);else resolve(frames)}sample()}));expect(samples.every(f=>!f.overflow&&f.cards.every(c=>c.left>=0&&c.right<=width))).toBe(true);await expect(p.locator('.home-card-stack')).toHaveAttribute('data-top','0');await expect(p.locator('.home-card-stack')).toHaveAttribute('data-motion','paused');await expect(p.locator('.home-story')).toHaveCount(2);await expect(p.locator('.home-word')).toHaveCount(12);out.layouts.push({width,lang,frames:samples.length,noOverflow:true});if(width===390&&lang==='zh')await p.screenshot({path:path.join(__dirname,'UI14-reading-390.png'),fullPage:true});
  if((width===390&&lang==='zh')||(width===1440&&lang==='en')){const a=await new AxeBuilder({page:p}).analyze();out.axe.push({width,lang,violations:a.violations});expect(a.violations).toEqual([])}
 }
},{hasTouch:true});
await check('Offscreen animation pauses and resumes only when visible',async p=>{
 await p.setViewportSize({width:390,height:300});await visit(p);const stack=p.locator('.home-card-stack');await expect(stack).toHaveAttribute('data-motion','paused');await stack.scrollIntoViewIfNeeded();await expect(stack).toHaveAttribute('data-motion','running');await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));await expect(stack).toHaveAttribute('data-motion','paused');await stack.scrollIntoViewIfNeeded();await expect(stack).toHaveAttribute('data-motion','running');
});
await b.close();out.status=out.checks.every(x=>x.status==='PASS')?'PASS':'FAIL';fs.writeFileSync(path.join(__dirname,'UI14-browser-results.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,checks:out.checks,layouts:out.layouts.length,axe:out.axe.length}));process.exitCode=out.status==='PASS'?0:1})().catch(e=>{console.error(e);process.exit(1)});
