const {chromium,expect}=require('../../../../../frontend/node_modules/@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const out={version:'M002-UI-21',scope:'Actual opacity samples, ten-second readable dwell, top-layer continuity, replacement, reduced motion and short-screen layout.',checks:[],...(process.env.UI21_RETRY?{retry_of:'UI21-first-browser-results.json'}:{})};
const url=q=>'http://127.0.0.1:4174/prototype/?'+new URLSearchParams({page:'login',role:'guest',lang:'zh',v:out.version,...q});
const login=async p=>{await p.goto(url());await p.fill('#auth-username','learner');await p.fill('#auth-password','prototype-example');await p.evaluate(()=>{window.toastSamples=[];let start;const tick=()=>{const e=document.querySelector('#toast');if(e?.classList.contains('visible')){start??=performance.now();window.toastSamples.push({ms:performance.now()-start,opacity:Number(getComputedStyle(e).opacity),time:e.getAnimations()[0]?.currentTime,modal:!!document.querySelector('#dialog[open]'),popover:e.matches(':popover-open'),host:e.parentElement.id})}if(!start||performance.now()-start<11200)requestAnimationFrame(tick)};requestAnimationFrame(tick)});await p.locator('[data-action="identity-submit"]').click();await p.locator('#dialog[open]').waitFor()};
(async()=>{const b=await chromium.launch();out.browser=b.version();async function check(name,fn){if(process.env.UI21_RETRY && name.startsWith('Short-screen')){out.checks.push(JSON.parse(fs.readFileSync(path.join(__dirname,'UI21-first-browser-results.json'))).checks.find(x=>x.name===name));return}const c=await b.newContext({viewport:{width:1440,height:900},reducedMotion:'no-preference'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{await fn(p);expect(errors).toEqual([]);out.checks.push({name,status:'PASS'})}catch(e){out.checks.push({name,status:'FAIL',error:e.message,stack:e.stack,errors});await p.screenshot({path:path.join(__dirname,`UI21-final-failure-${out.checks.length}.png`)})}await c.close();console.log(name,out.checks.at(-1).status)}
await check('Real fade-in and fade-out surround ten-second dwell; notice changes preserve the timeline',async p=>{
 await login(p);await p.evaluate(()=>{window.welcomeAnimation=document.querySelector('#toast').getAnimations()[0]});await p.waitForTimeout(150);await expect(p.locator('#toast')).toHaveCSS('opacity','1');await expect(p.locator('.dialog-close')).toBeFocused();await p.locator('#dialog').getByRole('button',{name:'下一步',exact:true}).click();expect(await p.evaluate(()=>document.querySelector('#toast').getAnimations()[0]===window.welcomeAnimation),'original animation survives notice update').toBe(true);await p.keyboard.press('Escape');await expect(p.locator('#toast')).toBeVisible();await p.locator('.header-actions [data-go="notices"]').click();await p.locator('[data-action^="notice:"]').first().click();expect(await p.evaluate(()=>document.querySelector('#toast').getAnimations()[0]===window.welcomeAnimation),'original animation survives notice update').toBe(true);await p.screenshot({path:path.join(__dirname,'UI21-welcome-steady-1440.png')});
 await expect(p.locator('#toast')).toBeHidden({timeout:12000});await expect(p.locator('#dialog')).toBeVisible();await expect(p.locator('#dialog')).not.toHaveClass(/with-toast-space/);
 const samples=await p.evaluate(()=>window.toastSamples);out.samples=samples;const fadeIn=samples.filter(x=>x.time<300&&x.opacity>0&&x.opacity<1),steady=samples.filter(x=>x.time>=300&&x.time<10300),fadeOut=samples.filter(x=>x.time>=10300&&x.opacity>0&&x.opacity<1);expect(fadeIn.length).toBeGreaterThan(2);expect(steady.every(x=>x.opacity===1),'opacity stays at one during dwell').toBe(true);expect(fadeOut.length).toBeGreaterThan(2);expect(fadeOut.every(x=>x.popover&&x.host==='dialog'),'all visible exit frames stay above the modal').toBe(true);expect(fadeOut.at(-1).opacity).toBeLessThan(0.15);expect(steady.at(-1).time-steady[0].time).toBeGreaterThan(9900);expect(samples.at(-1).ms).toBeGreaterThan(10400);expect(samples.at(-1).ms).toBeLessThan(11000);out.motion={fadeInFrames:fadeIn.length,fadeOutFrames:fadeOut.length,lastVisibleMs:samples.at(-1).ms};
 // A paused midpoint is a visual illustration only; real motion evidence is the frame series above.
 await login(p);await p.evaluate(()=>{const a=document.querySelector('#toast').getAnimations()[0];a.pause();a.currentTime=10450});await p.screenshot({path:path.join(__dirname,'UI21-welcome-exit-midpoint-1440.png')});
});
await check('Short-screen feedback, replacement and reduced-motion preference remain usable',async p=>{
 await p.setViewportSize({width:320,height:568});await login(p);await p.waitForTimeout(150);const a=await p.locator('#toast').boundingBox(),d=await p.locator('#dialog').boundingBox();expect(a.y).toBeGreaterThanOrEqual(d.y+d.height+8);await expect(p.locator('#toast strong')).toHaveCSS('font-size','24px');await p.screenshot({path:path.join(__dirname,'UI21-welcome-320.png')});await p.emulateMedia({reducedMotion:'reduce'});await expect.poll(()=>p.locator('#toast').evaluate(e=>e.getAnimations().length)).toBe(0);await expect(p.locator('#toast')).toHaveCSS('opacity','1');await p.keyboard.press('Escape');
 await p.goto(url({page:'profile',role:'learner'}));await p.fill('#nickname','小树');await p.locator('[data-action="profile-save"]').click();await expect(p.locator('#toast')).toHaveCSS('opacity','1');expect(await p.locator('#toast').evaluate(e=>e.getAnimations().length)).toBe(0);
 await p.emulateMedia({reducedMotion:'no-preference'});await p.fill('#nickname','小林');await p.locator('[data-action="profile-save"]').click();await p.evaluate(()=>{window.oldToastAnimation=document.querySelector('#toast').getAnimations()[0]});await p.waitForTimeout(80);await p.fill('#nickname','小叶');await p.locator('[data-action="profile-save"]').click();expect(await p.evaluate(()=>window.oldToastAnimation.playState)).toBe('idle');expect(await p.locator('#toast').evaluate(e=>e.getAnimations().length)).toBe(1);await p.waitForTimeout(350);await expect(p.locator('#toast')).toHaveCSS('opacity','1');await expect(p.locator('.account-identity h2')).toHaveText('小叶');
});await b.close();out.status=out.checks.every(c=>c.status==='PASS')?'PASS':'FAIL';fs.writeFileSync(path.join(__dirname,'UI21-browser-results.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({...out,samples:out.samples?.length}));process.exitCode=out.status==='PASS'?0:1})().catch(e=>{console.error(e);process.exit(1)});
