const {chromium,expect}=require('../../../../../frontend/node_modules/@playwright/test');const {default:AxeBuilder}=require('../../../../../frontend/node_modules/@axe-core/playwright');const fs=require('node:fs'),path=require('node:path');
const out={version:'M002-UI-22',scope:'Saved story settings presentation and snapshot retention; shared trial renderer regression.',checks:[],layouts:[]};
const url=q=>'http://127.0.0.1:4174/prototype/?'+new URLSearchParams({page:'batch',batch:'b1',role:'learner',lang:'zh',v:out.version,...q});
(async()=>{const b=await chromium.launch();out.browser=b.version();async function check(name,fn){if(process.env.UI22_RETRY&&name.startsWith('Read-only')){const old=JSON.parse(fs.readFileSync(path.join(__dirname,'UI22-first-browser-results.json')));out.checks.push(old.checks[0]);out.layouts=old.layouts;out.axeViolations=old.axeViolations;out.inherited_from='UI22-first-browser-results.json';return}const c=await b.newContext({reducedMotion:'reduce'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});try{await fn(p);expect(errors).toEqual([]);out.checks.push({name,status:'PASS'})}catch(e){out.checks.push({name,status:'FAIL',error:e.message,stack:e.stack,errors});await p.screenshot({path:path.join(__dirname,'UI22-failure-'+out.checks.length+'.png'),fullPage:true})}await c.close();console.log(name,out.checks.at(-1).status)}
await check('Read-only settings match workstation hierarchy at desktop, tablet and narrow mobile widths',async p=>{
 for(const [width,height,lang] of [[1440,900,'zh'],[1440,900,'en'],[900,900,'zh'],[320,700,'zh'],[320,700,'en']]){
  await p.setViewportSize({width,height});await p.goto(url({lang}));await p.locator('.batch-settings').waitFor();const card=p.locator('.batch-settings');await expect(card.locator('.trial-model dd')).toHaveText('Model A');await expect(card.locator('.trial-config-row dd')).toHaveText(lang==='zh'?['故事','简短','中文']:['Story','Brief','Chinese']);await expect(card.locator('.batch-review-count dd')).toHaveText('2');await expect(card.locator('input,select,textarea,button')).toHaveCount(0);await expect(p.locator('.story-text')).toContainText('Mia was resilient');await expect(p.locator('[data-action="learn-single:b1"]')).toHaveCount(1);await expect(p.locator('[data-action="learn-delete:b1"]')).toHaveCount(1);await expect(p.locator('[data-participation="b1"]')).toBeChecked();await expect(p.locator('[data-action="learn-title-edit"]')).toHaveCount(1);
  expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const rect=await card.boundingBox();expect(rect.x).toBeGreaterThanOrEqual(0);expect(rect.x+rect.width).toBeLessThanOrEqual(width);out.layouts.push({width,height,lang,card:rect});await p.screenshot({path:path.join(__dirname,`UI22-batch-${width}-${lang}.png`),fullPage:true});
  if(width===320&&lang==='en'){const r=await new AxeBuilder({page:p}).analyze();out.axeViolations=r.violations;expect(r.violations).toEqual([])}
 }
});
await check('Historical snapshots stay literal and trial configuration stays read-only',async p=>{
 await p.route('**/fixtures.json?*',async route=>{const response=await route.fetch(),f=await response.json();Object.assign(f.library[0],{model:'Archived Model / Long historical configuration name',style:'Retired style',length:'Custom length',language:'Français'});await route.fulfill({response,json:f})});await p.setViewportSize({width:320,height:700});await p.goto(url());await expect(p.locator('.batch-settings .trial-model dd')).toHaveText('Archived Model / Long historical configuration name');await expect(p.locator('.batch-settings .trial-config-row dd')).toHaveText(['Retired style','Custom length','Français']);expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await p.screenshot({path:path.join(__dirname,'UI22-historical-320.png'),fullPage:true});
 await p.goto(url({page:'trial',role:'guest',lang:'en'}));await p.locator('.trial-settings').waitFor();await expect(p.locator('.trial-settings .trial-config-row dd')).toHaveText(['Story','Brief','Chinese']);await expect(p.locator('.trial-settings select')).toHaveCount(0);
});await b.close();out.status=out.checks.every(x=>x.status==='PASS')?'PASS':'FAIL';fs.writeFileSync(path.join(__dirname,'UI22-browser-results.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));process.exitCode=out.status==='PASS'?0:1})().catch(e=>{console.error(e);process.exit(1)});
