const {chromium,expect}=require('../../../../../frontend/node_modules/@playwright/test');const {default:AxeBuilder}=require('../../../../../frontend/node_modules/@axe-core/playwright');const fs=require('node:fs'),path=require('node:path');
const visit=async(p,q={})=>{await p.goto('http://127.0.0.1:4174/prototype/?'+new URLSearchParams({page:'trial',role:'guest',lang:'zh',v:'M002-UI-15',...q}));await p.locator('main h1').waitFor()};
(async()=>{const b=await chromium.launch(),out={version:'M002-UI-15',scope:'Independent trial configuration display, localization, responsive alignment and retained generation flow.',checks:[],layouts:[],axe:[]};async function check(name,fn){const c=await b.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{await fn(p);expect(errors).toEqual([]);out.checks.push({name,status:'PASS'})}catch(e){out.checks.push({name,status:'FAIL',error:e.message,errors});await p.screenshot({path:path.join(__dirname,'UI15-failure-'+out.checks.length+'.png'),fullPage:true})}await c.close();console.log(name,out.checks.at(-1).status)}
await check('Trial settings: bilingual read-only values, layout and accessible collapse',async p=>{
 for(const width of [320,390,768,1440])for(const lang of ['zh','en']){await p.setViewportSize({width,height:900});await visit(p,{lang});await expect(p.locator('.trial-settings dd')).toHaveText(lang==='zh'?['Model A','故事','简短','中文']:['Model A','Story','Brief','Chinese']);await expect(p.locator('.trial-settings input,.trial-settings select,.trial-settings textarea')).toHaveCount(0);await expect(p.locator('[data-region="generation-result"] .article')).toHaveCount(0);const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);expect(overflow).toBe(false);out.layouts.push({width,lang,overflow});if(lang==='zh'||width===320)await p.screenshot({path:path.join(__dirname,`UI15-trial-${width}-${lang}.png`),fullPage:true});await p.locator('.trial-settings summary').focus();await p.keyboard.press('Enter');await expect(p.locator('.trial-model')).toBeHidden();await p.keyboard.press('Enter');await expect(p.locator('.trial-model')).toBeVisible();await expect(p.locator('#generate')).toBeEnabled();
 if((width===390&&lang==='zh')||(width===1440&&lang==='en')){const a=await new AxeBuilder({page:p}).analyze();out.axe.push({width,lang,violations:a.violations});expect(a.violations).toEqual([])}
 }
});
await check('Selected preset identity, explicit generation, registration handoff and disabled states',async p=>{
 await visit(p,{page:'explore'});await p.locator('[role="tab"][data-gallery-language="English"]').click();await p.locator('[data-action="try:1"]').click();await expect(p.locator('main h1')).toHaveText('一杯咖啡的时间');await expect(p.locator('.trial-settings dd')).toHaveText(['Model B','故事','简短','英语']);await expect(p.locator('.quota-detail')).toContainText('3');await expect(p.locator('[data-region="generation-result"] .article')).toHaveCount(0);await p.locator('[data-action="language"]').click();await expect(p.locator('.trial-settings dd')).toHaveText(['Model B','Story','Brief','English']);await p.locator('#generate').click();await expect(p.locator('[data-action="collect"]')).toBeVisible({timeout:20000});await expect(p.locator('.trial-settings dd')).toHaveText(['Model B','Story','Brief','English']);await p.locator('[data-action="collect"]').click();await expect(p.locator('#identity-form')).toBeVisible();
 for(const state of ['invalid','noquota','nomodel','nolength']){await visit(p,{state});await expect(p.locator('.trial-model')).toBeVisible();await expect(p.locator('#generate')).toBeDisabled();}
});
await check('Long published model names wrap and ordinary creation controls remain editable',async p=>{
 await p.route('**/fixtures.json?*',async route=>{const r=await route.fetch();const f=await r.json();f.presets[0].model='A-very-long-published-model-name-for-layout-verification';await route.fulfill({json:f})});await p.setViewportSize({width:320,height:900});await visit(p);await expect(p.locator('.trial-model dd')).toHaveText('A-very-long-published-model-name-for-layout-verification');expect(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await p.unroute('**/fixtures.json?*');await p.setViewportSize({width:1440,height:900});await visit(p,{page:'create',role:'learner'});await expect(p.locator('.trial-settings')).toHaveCount(0);await expect(p.locator('.settings select')).toHaveCount(4);expect(await p.locator('.settings select').evaluateAll(es=>es.every(x=>!x.disabled))).toBe(true);await expect(p.locator('[data-action="random"]')).toBeVisible();
});
await b.close();out.status=out.checks.every(x=>x.status==='PASS')?'PASS':'FAIL';fs.writeFileSync(path.join(__dirname,'UI15-browser-results.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,checks:out.checks,layouts:out.layouts.length,axe:out.axe.length}));process.exitCode=out.status==='PASS'?0:1})().catch(e=>{console.error(e);process.exit(1)});
