const {chromium,expect}=require('../../../../../frontend/node_modules/@playwright/test');
const {default:AxeBuilder}=require('../../../../../frontend/node_modules/@axe-core/playwright');
const fs=require('node:fs'),path=require('node:path');
(async()=>{const b=await chromium.launch(),c=await b.newContext({reducedMotion:'reduce'}),p=await c.newPage();const out={version:'M002-UI-13',scope:'Homepage two-story crossed cards: content, layout, stacking access and accessibility.',checks:[],layouts:[],axe:[],errors:[]};p.on('pageerror',e=>out.errors.push(e.message));
for(const width of [320,390,768,1440])for(const lang of ['zh','en']){
 await p.setViewportSize({width,height:900});await p.goto('http://127.0.0.1:4174/prototype/?'+new URLSearchParams({page:'home',role:'guest',lang,v:'M002-UI-13'}));await p.locator('.home-story').last().waitFor();await p.mouse.move(0,0);
 const record=await p.evaluate(()=>{const box=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height}};return {overflow:document.documentElement.scrollWidth>innerWidth,cards:[...document.querySelectorAll('.home-paper')].map(e=>({title:e.querySelector('h2').textContent,words:[...e.querySelectorAll('.home-word')].map(x=>x.textContent),highlights:[...e.querySelectorAll('mark')].map(x=>x.textContent),paragraphs:e.querySelectorAll('.home-story').length,wordCount:e.querySelector('.home-story').textContent.split(/\s+/).length,matrix:getComputedStyle(e).transform,...box(e)})),main:box(document.querySelector('main'))}});
 record.width=width;record.lang=lang;out.layouts.push(record);const [back,front]=record.cards;
 const ok=!record.overflow&&record.cards.length===2&&back.title!==front.title&&record.cards.every(r=>r.paragraphs===1&&r.words.length===6&&JSON.stringify(r.words)===JSON.stringify(r.highlights)&&r.wordCount>=40&&r.matrix!=='none'&&r.x>=0&&r.right<=width)&&front.y<back.bottom&&front.y>back.y;
 out.checks.push({name:`Home ${width}px ${lang}: two complete single-paragraph stories, six words each, rotated overlap, no overflow`,status:ok?'PASS':'FAIL'});
 if(lang==='zh'||width===320)await p.screenshot({path:path.join(__dirname,`UI13-home-${width}-${lang}.png`),fullPage:true});
 if((width===390&&lang==='zh')||(width===1440&&lang==='en')){const a=await new AxeBuilder({page:p}).analyze();out.axe.push({width,lang,violations:a.violations});out.checks.push({name:`Home accessibility ${width}px ${lang}`,status:a.violations.length?'FAIL':'PASS'});}
}
// Keyboard raises either card without hiding either story from reading order.
await p.locator('.home-paper-back').focus();await expect(p.locator('.home-paper-back')).toBeFocused();await expect(p.locator('.home-paper-back')).toHaveCSS('z-index','4');await p.keyboard.press('Tab');await expect(p.locator('.home-paper-front')).toBeFocused();await expect(p.locator('.home-paper-front')).toHaveCSS('z-index','4');await p.keyboard.press('Shift+Tab');await expect(p.locator('.home-paper-back')).toBeFocused();await p.screenshot({path:path.join(__dirname,'UI13-back-focused-1440-en.png'),fullPage:true});out.checks.push({name:'Tab / Shift+Tab raises either card with visible focus',status:'PASS'});
await p.locator('.home-actions a').first().focus();await p.locator('.home-paper-back h2').hover();await expect(p.locator('.home-paper-back')).toHaveCSS('z-index','3');out.checks.push({name:'Pointer hover raises back card',status:'PASS'});
const touch=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),tp=await touch.newPage();await tp.goto('http://127.0.0.1:4174/prototype/?page=home&role=guest&lang=zh&v=M002-UI-13');await tp.locator('.home-paper-back h2').tap();await expect(tp.locator('.home-paper-back')).toBeFocused();await expect(tp.locator('.home-paper-back')).toHaveCSS('z-index','4');await tp.screenshot({path:path.join(__dirname,'UI13-back-tapped-390.png'),fullPage:true});await tp.locator('.home-paper-front .home-word-meaning').tap();await expect(tp.locator('.home-paper-front')).toBeFocused();out.checks.push({name:'Emulated mobile tap raises either paper card',status:'PASS'});await touch.close();
out.checks.push({name:'No browser runtime errors',status:out.errors.length?'FAIL':'PASS'});out.status=out.checks.every(x=>x.status==='PASS')?'PASS':'FAIL';fs.writeFileSync(path.join(__dirname,'UI13-browser-results.json'),JSON.stringify(out,null,2)+'\n');await b.close();console.log(JSON.stringify({status:out.status,checks:out.checks,layouts:out.layouts.length,axe:out.axe.length}));process.exitCode=out.status==='PASS'?0:1})().catch(e=>{console.error(e);process.exit(1)});
