const {chromium,expect}=require('../../../../../frontend/node_modules/@playwright/test');const {default:AxeBuilder}=require('../../../../../frontend/node_modules/@axe-core/playwright');const fs=require('node:fs'),path=require('node:path');
const visit=async(p,q={})=>{await p.goto('http://127.0.0.1:4174/prototype/?'+new URLSearchParams({page:'create',role:'learner',lang:'zh',v:'M002-UI-16',...q}));await p.locator('main h1').waitFor()};
const open=async p=>{if(!await p.locator('.creation-settings').evaluate(e=>e.open))await p.locator('.creation-settings summary').click()};
(async()=>{const b=await chromium.launch(),out={version:'M002-UI-16',scope:'Editable normal creation settings hierarchy, responsive controls, continuous editing and retained constraints.',checks:[],layouts:[],axe:[]};const retry=process.env.UI16_RETRY==='1';if(retry){const first=JSON.parse(fs.readFileSync(path.join(__dirname,'UI16-first-browser-results.json')));out.checks=first.checks.filter(x=>x.status==='PASS');out.layouts=first.layouts;out.axe=first.axe;out.retained_from='UI16-first-browser-results.json';}async function check(name,fn){if(retry&&!name.startsWith('Changing settings'))return;const c=await b.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{await fn(p);expect(errors).toEqual([]);out.checks.push({name,status:'PASS'})}catch(e){out.checks.push({name,status:'FAIL',error:e.message,errors});await p.screenshot({path:path.join(__dirname,'UI16-failure-'+out.checks.length+'.png'),fullPage:true})}await c.close();console.log(name,out.checks.at(-1).status)}
await check('Bilingual responsive controls, original defaults and stable editing focus',async p=>{
 for(const width of [320,390,768,1440])for(const lang of ['zh','en']){await p.setViewportSize({width,height:900});await visit(p,{lang});expect(await p.locator('.creation-settings').evaluate(e=>e.open)).toBe(width>1100);await open(p);await expect(p.locator('.creation-settings select')).toHaveCount(4);await expect(p.locator('#model')).toHaveValue('');await expect(p.locator('#explain')).toHaveValue('');await expect(p.locator('#style')).toHaveValue('story');await expect(p.locator('#length')).toHaveValue('brief');await expect(p.locator('#generate')).toBeDisabled();await p.locator('#model').selectOption({index:1});await expect(p.locator('#model')).toBeFocused();expect(await p.locator('.creation-settings').evaluate(e=>e.open)).toBe(true);await p.locator('#explain').selectOption('chinese');await expect(p.locator('#explain')).toBeFocused();await expect(p.locator('#generate')).toBeEnabled();await expect(p.locator('#style option:checked')).toHaveText(lang==='zh'?'故事':'Story');await expect(p.locator('#length option:checked')).toHaveText(lang==='zh'?'简短':'Brief');expect(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);out.layouts.push({width,lang,overflow:false});if(lang==='zh'||width===320)await p.screenshot({path:path.join(__dirname,`UI16-create-${width}-${lang}.png`),fullPage:true});
 if((width===390&&lang==='zh')||(width===1440&&lang==='en')){const a=await new AxeBuilder({page:p}).analyze();out.axe.push({width,lang,violations:a.violations});expect(a.violations).toEqual([])}
 await p.locator('.creation-settings summary').focus();await p.keyboard.press('Enter');expect(await p.locator('.creation-settings').evaluate(e=>e.open)).toBe(false);await p.keyboard.press('Enter');await expect(p.locator('#model')).not.toHaveValue('');
 }
});
await check('Changing settings, UI language, random words and generation preserve configuration',async p=>{
 await p.setViewportSize({width:390,height:900});await visit(p);await open(p);await p.locator('#model').selectOption({index:1});const model=await p.locator('#model').inputValue();await p.locator('#style').selectOption('news');await p.locator('#explain').selectOption('japanese');await p.locator('[data-action="language"]').click();expect(await p.locator('.creation-settings').evaluate(e=>e.open)).toBe(true);await expect(p.locator('#style')).toHaveValue('news');await expect(p.locator('#explain')).toHaveValue('japanese');await p.locator('#style').selectOption('business');await expect(p.locator('#style')).toHaveValue('business');await expect(p.locator('#style')).toBeFocused();const count=await p.locator('.panel .chips .chip').count();await p.locator('[data-action="random"]').click();expect(await p.locator('.panel .chips .chip').count()).toBe(count+1);expect(await p.locator('.creation-settings').evaluate(e=>e.open)).toBe(true);await expect(p.locator('#model')).toHaveValue(model);await p.locator('#generate').click();expect(await p.locator('.creation-settings select').evaluateAll(es=>es.every(e=>e.matches(':disabled')))).toBe(true);await expect(p.locator('[data-action="collect"]')).toBeVisible({timeout:20000});await expect(p.locator('#style')).toHaveValue('business');await expect(p.locator('#explain')).toHaveValue('japanese');await expect(p.locator('#model')).toHaveValue(model);
});
await check('Unavailable constraints, long model labels and read-only trial panel retained',async p=>{
 for(const state of ['noquota','nomodel','nolength']){await visit(p,{state});await expect(p.locator('#generate')).toBeDisabled();if(state==='nomodel')await expect(p.locator('#model')).toBeDisabled();if(state==='nolength')await expect(p.locator('#length')).toHaveValue('');}
 await p.setViewportSize({width:320,height:900});await visit(p);await open(p);await p.locator('#model').evaluate(e=>{const o=document.createElement('option');o.value='layout-only';o.textContent='A very long AI model display name for layout';e.append(o);e.value=o.value});expect(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
 await visit(p,{page:'trial',role:'guest'});await expect(p.locator('.creation-settings')).toHaveCount(0);await expect(p.locator('.trial-settings select')).toHaveCount(0);await expect(p.locator('.trial-settings dd')).toHaveText(['Model A','故事','简短','中文']);
});
await b.close();out.status=out.checks.every(x=>x.status==='PASS')?'PASS':'FAIL';fs.writeFileSync(path.join(__dirname,'UI16-browser-results.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,checks:out.checks,layouts:out.layouts.length,axe:out.axe.length}));process.exitCode=out.status==='PASS'?0:1})().catch(e=>{console.error(e);process.exit(1)});
