const {chromium,expect}=require('../../../../../frontend/node_modules/@playwright/test');const {default:AxeBuilder}=require('../../../../../frontend/node_modules/@axe-core/playwright');const fs=require('node:fs'),path=require('node:path');
const out={version:'M002-UI-10',scope:'Home composition, shared local icons, affected navigation and accessible labels; prototype only.',checks:[],layouts:[],axe:[]};
const visit=async(p,route,q={})=>{await p.goto('http://127.0.0.1:4174/prototype/?'+new URLSearchParams({page:route,role:'learner',lang:'zh',batch:'b1',v:'M002-UI-10',...q}));await p.locator('main h1:visible,main h2:visible').first().waitFor()};
(async()=>{const b=await chromium.launch();out.browser=b.version();async function test(name,fn){if(process.env.UI10_TEST_FILTER&&!new RegExp(process.env.UI10_TEST_FILTER).test(name))return;const c=await b.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'}),p=await c.newPage(),errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4174/'))external.push(r.url())});try{await fn(p);expect(errors).toEqual([]);expect(external).toEqual([]);out.checks.push({name,status:'PASS'});}catch(e){out.checks.push({name,status:'FAIL',error:e.message,errors,external});await p.screenshot({path:path.join(__dirname,'UI10-failure-'+out.checks.length+'.png'),fullPage:true})}await c.close();console.log(name,out.checks.at(-1).status)}
await test('HOME10: bilingual example, text labels, guest actions and zero external requests',async p=>{
 for(const lang of ['zh','en']){await visit(p,'home',{lang,role:'guest'});await expect(p.locator('.home-word')).toHaveText(['resilient','wander','weave']);await expect(p.locator('.home-story mark')).toHaveText(['resilient','wander','weave']);await expect(p.locator('.home-paper h2')).toHaveText('A small town, a new beginning.');await expect(p.locator('.home-path article')).toHaveCount(3);await expect(p.locator('.home-word-meaning')).toContainText(lang==='zh'?'有韧性的':'Able to recover');await expect(p.locator('.home-paper-meta')).toContainText(lang==='zh'?'示例':'sample');await expect(p.locator('.header-actions [data-action="login"]')).toBeVisible();
 await p.locator('.home-actions [data-go="create"] svg').click();await expect(p.locator('#generate')).toBeVisible();await visit(p,'home',{lang,role:'guest'});await p.locator('.home-actions [data-go="explore"] svg').click();await expect(p.locator('.gallery-card')).toHaveCount(2);await expect(p.locator('[data-region="generation-result"]')).toHaveCount(0);}
});
await test('ICON10: SVG click targets preserve user/admin navigation, random/remove and gallery arrows',async p=>{
 await visit(p,'profile');await p.locator('.account-dropdown summary svg').click();await p.locator('.account-popover [data-go="bag"] svg').click();await expect(p.locator('.item .medal svg').first()).toHaveAttribute('data-icon','lucide:calendar-check');await p.locator('.account-nav [data-go="growth"] svg').click();await expect(p.locator('.achievement .medal svg').first()).toBeVisible();
 await visit(p,'models');await p.locator('.admin-nav [data-go="plans"] svg').click();await expect(p.locator('#plan-limit')).toBeVisible();await visit(p,'create');const n=await p.locator('[data-action^="remove-word:"]').count();await p.locator('[data-action="random"] svg').click();await expect(p.locator('[data-action^="remove-word:"]')).toHaveCount(n+1);await p.locator('[data-action^="remove-word:"] svg').first().click();await expect(p.locator('[data-action^="remove-word:"]')).toHaveCount(n);
 await visit(p,'explore');await p.locator('[data-gallery="next"] svg').click();await expect(p.locator('.gallery-position')).toHaveText('2 / 2');await p.locator('[data-gallery="previous"] svg').click();await expect(p.locator('.gallery-position')).toHaveText('1 / 2');
});
await test('ICON10: review shape groups, localized accessible labels and editing affordance',async p=>{
 await visit(p,'review');await p.locator('.slot').first().fill('z');await p.locator('[data-action="learn-overview"]').click();await p.locator('[data-action="learn-edit-word:0"] svg').click();await expect(p.locator('.slot').first()).toHaveValue('z');await p.locator('[data-action="learn-edit-passage"]').click();await expect(p.locator('.gap').first()).toBeVisible();const names=await p.locator('.gap').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label')));expect(names.every(n=>/圆形|菱形|三角形|方形|星形|六边形/.test(n))).toBe(true);await expect(p.locator('.gap-wrap svg').first()).toHaveAttribute('aria-hidden','true');await p.screenshot({path:path.join(__dirname,'UI10-review-groups-1440.png'),fullPage:true});
});
await test('HOME10: restrained word motion, hover pause and reduced-motion static layout',async p=>{
 await p.emulateMedia({reducedMotion:'no-preference'});await visit(p,'home');const word=p.locator('.home-word').first();const before=await word.evaluate(e=>getComputedStyle(e).transform);await p.waitForTimeout(350);const after=await word.evaluate(e=>getComputedStyle(e).transform);expect(after).not.toBe(before);await p.locator('.home-example').hover();expect(await word.evaluate(e=>getComputedStyle(e).animationPlayState)).toBe('paused');await p.emulateMedia({reducedMotion:'reduce'});expect(await word.evaluate(e=>getComputedStyle(e).animationName)).toBe('none');
});
await test('ICON10: all views parse and render; small-screen home and affected surfaces fit',async p=>{
 const routes=['home','login','register','create','library','batch','range','review','overview','summary','sessiondone','profile','notices','growth','bag','shop','adminhome','metrics','models','plans','users','userdetail','operations','credits','messages','presets','explore','trial'];
 for(const [width,lang,list] of [[1440,'zh',routes],[390,'en',['home','login','register','create','growth','bag','plans','users','operations','messages','explore']],[320,'en',['home']],[768,'zh',['home']]]){await p.setViewportSize({width,height:900});for(const route of list){await visit(p,route,{lang});const r=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,unlabeled:[...document.querySelectorAll('button:has(svg),a:has(svg)')].filter(e=>!e.textContent.trim()&&!e.getAttribute('aria-label')).length,badIcons:[...document.querySelectorAll('.ui-icon')].filter(e=>!e.getAttribute('data-icon')||!e.querySelector('*')||e.getAttribute('aria-hidden')!=='true'||e.getAttribute('focusable')!=='false').length}));out.layouts.push({width,lang,route,...r});expect(r.overflow,route).toBe(false);expect(r.unlabeled,route).toBe(0);expect(r.badIcons,route).toBe(0);}}
});
await test('HOME10 / ICON10: representative axe audit',async p=>{
 for(const [route,width,lang] of [['home',1440,'zh'],['home',320,'en'],['login',390,'zh'],['create',390,'zh'],['bag',1440,'zh'],['models',1440,'zh'],['explore',390,'en']]){await p.setViewportSize({width,height:900});await visit(p,route,{lang});const r=await new AxeBuilder({page:p}).analyze();out.axe.push({route,width,lang,violations:r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});expect(r.violations,route).toEqual([]);}
});
await b.close();out.status=out.checks.every(c=>c.status==='PASS')?'PASS':'FAIL';fs.writeFileSync(path.join(__dirname,process.env.UI10_TEST_FILTER?'UI10-targeted-results.json':'UI10-browser-results.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,checks:out.checks,layouts:out.layouts.length,axe:out.axe.length}));process.exitCode=out.status==='PASS'?0:1})().catch(e=>{console.error(e);process.exit(1)});
