package ai

// irregularForms is versioned with ValidatorVersion. Values intentionally contain
// only widely accepted modern forms; ambiguous rare forms fall back to exact-entry
// generation and may be rejected rather than weakening saved learning material.
var irregularForms = map[string][]string{
	"coup d'etat": {"coups d'etat"},
	"analysis":    {"analyses"}, "cactus": {"cacti", "cactuses"}, "child": {"children"},
	"criterion": {"criteria"}, "crisis": {"crises"}, "datum": {"data"}, "foot": {"feet"},
	"goose": {"geese"}, "half": {"halves"}, "index": {"indexes", "indices"}, "knife": {"knives"},
	"leaf": {"leaves"}, "life": {"lives"}, "loaf": {"loaves"}, "man": {"men"},
	"matrix": {"matrices"}, "mouse": {"mice"}, "ox": {"oxen"}, "person": {"people"},
	"phenomenon": {"phenomena"}, "shelf": {"shelves"}, "thesis": {"theses"}, "tooth": {"teeth"},
	"vertex": {"vertices"}, "wife": {"wives"}, "wolf": {"wolves"}, "woman": {"women"},

	"be":     {"am", "are", "been", "being", "is", "was", "were"},
	"become": {"became", "becomes", "becoming"}, "begin": {"began", "begun", "begins", "beginning"},
	"break": {"broke", "broken", "breaks", "breaking"}, "bring": {"brought", "brings", "bringing"},
	"build": {"built", "builds", "building"}, "buy": {"bought", "buys", "buying"},
	"catch": {"caught", "catches", "catching"}, "choose": {"chose", "chosen", "chooses", "choosing"},
	"come": {"came", "comes", "coming"}, "cost": {"costs", "costing"}, "cut": {"cuts", "cutting"},
	"do": {"did", "does", "doing", "done"}, "draw": {"drew", "drawn", "draws", "drawing"},
	"drink": {"drank", "drunk", "drinks", "drinking"}, "drive": {"drove", "driven", "drives", "driving"},
	"eat": {"ate", "eaten", "eats", "eating"}, "fall": {"fell", "fallen", "falls", "falling"},
	"feel": {"felt", "feels", "feeling"}, "fight": {"fought", "fights", "fighting"},
	"find": {"found", "finds", "finding"}, "fly": {"flew", "flown", "flies", "flying"},
	"forget":  {"forgot", "forgotten", "forgets", "forgetting"},
	"forgive": {"forgave", "forgiven", "forgives", "forgiving"},
	"freeze":  {"froze", "frozen", "freezes", "freezing"}, "get": {"got", "gotten", "gets", "getting"},
	"give": {"gave", "given", "gives", "giving"}, "go": {"went", "gone", "goes", "going"},
	"grow": {"grew", "grown", "grows", "growing"}, "hang": {"hung", "hangs", "hanging"},
	"have": {"had", "has", "having"}, "hear": {"heard", "hears", "hearing"},
	"hide": {"hid", "hidden", "hides", "hiding"}, "hit": {"hits", "hitting"},
	"hold": {"held", "holds", "holding"}, "keep": {"kept", "keeps", "keeping"},
	"know": {"knew", "known", "knows", "knowing"}, "lead": {"led", "leads", "leading"},
	"learn": {"learned", "learnt", "learns", "learning"}, "leave": {"left", "leaves", "leaving"},
	"lend": {"lent", "lends", "lending"}, "let": {"lets", "letting"},
	"lie": {"lay", "lain", "lies", "lying"}, "lose": {"lost", "loses", "losing"},
	"make": {"made", "makes", "making"}, "mean": {"meant", "means", "meaning"},
	"meet": {"met", "meets", "meeting"}, "pay": {"paid", "pays", "paying"},
	"put": {"puts", "putting"}, "read": {"reads", "reading"},
	"ride": {"rode", "ridden", "rides", "riding"}, "ring": {"rang", "rung", "rings", "ringing"},
	"rise": {"rose", "risen", "rises", "rising"}, "run": {"ran", "runs", "running"},
	"say": {"said", "says", "saying"}, "see": {"saw", "seen", "sees", "seeing"},
	"sell": {"sold", "sells", "selling"}, "send": {"sent", "sends", "sending"},
	"set": {"sets", "setting"}, "shake": {"shook", "shaken", "shakes", "shaking"},
	"shine": {"shone", "shined", "shines", "shining"}, "shoot": {"shot", "shoots", "shooting"},
	"show": {"showed", "shown", "shows", "showing"}, "shut": {"shuts", "shutting"},
	"sing": {"sang", "sung", "sings", "singing"}, "sink": {"sank", "sunk", "sinks", "sinking"},
	"sit": {"sat", "sits", "sitting"}, "sleep": {"slept", "sleeps", "sleeping"},
	"speak": {"spoke", "spoken", "speaks", "speaking"}, "spend": {"spent", "spends", "spending"},
	"stand": {"stood", "stands", "standing"}, "steal": {"stole", "stolen", "steals", "stealing"},
	"stick": {"stuck", "sticks", "sticking"}, "swim": {"swam", "swum", "swims", "swimming"},
	"take": {"took", "taken", "takes", "taking"}, "teach": {"taught", "teaches", "teaching"},
	"tell": {"told", "tells", "telling"}, "think": {"thought", "thinks", "thinking"},
	"throw":      {"threw", "thrown", "throws", "throwing"},
	"understand": {"understood", "understands", "understanding"},
	"wake":       {"woke", "woken", "wakes", "waking"}, "wear": {"wore", "worn", "wears", "wearing"},
	"weave": {"wove", "woven", "weaves", "weaving"}, "win": {"won", "wins", "winning"},
	"write": {"wrote", "written", "writes", "writing"},
}

var doublingStems = map[string]struct{}{
	"admit": {}, "chat": {}, "clap": {}, "commit": {}, "control": {}, "drop": {}, "equip": {},
	"fit": {}, "grab": {}, "hop": {}, "hug": {}, "occur": {}, "omit": {}, "permit": {},
	"plan": {}, "prefer": {}, "refer": {}, "regret": {}, "shop": {}, "skip": {}, "stop": {},
	"submit": {}, "travel": {},
}
