import {expect,start,stop,login,ok,call,sql,out,dump,randomUUID,env} from './harness.mjs';
import {raw,parse,charge,stream,runCall,terminal} from './api-support.mjs';
import {startProvider} from './provider.mjs';
const provider=await startProvider(),browser=await start(),admin=await browser.newContext(),visitor=await browser.newContext(),learner=await browser.newContext(),trial=await browser.newContext(),refundVisitor=await browser.newContext();
const results=[],samples=[];let action='SETUP',baseModel,presetModel,presetId,zhId,userId,trialId,trialEnd;
async function test(id,name,fn){action=id;try{await fn();results.push({id,name,result:'PASS'});}catch(e){results.push({id,name,result:'FAIL',error:String(e)});}dump('api-results.json',{results,samples,localProviderCalls:provider.calls,realProviderCalls:0});console.log(id,results.at(-1).result,results.at(-1).error??'');}
const register=async(c,suffix)=>(await ok(c,'/auth/register','POST',{username:'qa9_'+suffix+'_'+Date.now(),password:env.ADMIN_PASSWORD,password_confirmation:env.ADMIN_PASSWORD,ui_locale:'en-US'})).actor.id;
async function plan(code,limit,models,max=1,lengths=['short']){const g=await ok(admin,'/admin/groups'),item=g.items.find(x=>x.code===code);return ok(admin,'/admin/groups/'+code,'PUT',{expected_revision:g.revision,priority:item.priority,max_entries:max,rolling_24h_limit:limit,model_ids:models,allowed_lengths:lengths});}
const adminPreset=id=>ok(admin,'/admin/presets/'+id);
const publicPreset=async(id=presetId)=>(await ok(visitor,'/presets/'+id)).preset;
async function preview(id,mode='valid'){const d=await adminPreset(id);provider.words=d.preset.configuration.entries;provider.lang=d.preset.configuration.meaning_language;provider.mode=mode;const r=await raw(admin,'/admin/presets/'+id+'/previews/stream','POST',{draft_version:d.preset.draft_version});expect(r.status()).toBe(200);return parse(await r.text());}
async function publish(id){const d=await adminPreset(id);return ok(admin,'/admin/presets/'+id+'/publish','POST',{draft_version:d.preset.draft_version,expected_revision:d.revision,confirmed:true});}
const publicBody=async()=>({published_version:(await publicPreset()).published_version});
async function begin(c){provider.words=['learn','weave','book'];provider.lang='en';return stream(c,'/presets/'+presetId+'/generations/stream',await publicBody());}
const normal=()=>({model_id:baseModel,meaning_language:'en',scenario:'story',length:'short',entries:['learn']});
const learningCount=()=>Number(sql('SELECT count(*) FROM wordweave.generation_charges'));
const benefits=()=>ok(admin,'/admin/users/'+trialId+'/benefits');
async function sourceFailure(c,path,body,kind,expected){provider.mode=kind;const before=await ok(c,'/generation-options'),count=learningCount();let run,code,status;
 if(kind==='http-failure'){const response=await raw(c,path,'POST',body);status=response.status();expect(status).toBe(503);code=(await response.json()).code;run=sql('SELECT run_id FROM wordweave.generation_charges ORDER BY charged_at DESC LIMIT 1');}
 else{const s=await stream(c,path,body);run=s.run_id;if(kind==='hold'){s.abort();await s.done;await expect.poll(()=>charge(run).state,{timeout:15000}).toBe('refunded');}else{await s.done;terminal(s,'failed');expect(s.events.find(x=>x.event==='generation.failed').data.quota_refunded).toBe(true);}const retry=await runCall(s,c,'/cancel');expect(retry.status()).toBe(200);expect((await retry.json()).data).toEqual({status:'failed',quota_refunded:true});}
 await expect.poll(()=>charge(run).state).toBe('refunded');expect(charge(run)).toMatchObject({...expected,state:'refunded'});expect(learningCount()).toBe(count+1);expect((await ok(c,'/generation-options')).quota).toEqual(before.quota);samples.push({action,kind,run,status,code,charge:charge(run),quotaUnchanged:true});return run;
}
try{
 await login(admin);const cr=await ok(admin,'/admin/openrouter-credential');await ok(admin,'/admin/openrouter-credential','PUT',{api_key:'qa9-local-provider-only',confirmed:true,expected_revision:cr.revision});
 for(const name of ['QA09 basic','QA09 preset model with a longer readable name']){const m=await ok(admin,'/admin/models','POST',{display_name:name,description:'Disposable QA09 model',openrouter_model_id:baseModel?'provider/preset':'provider/integration'});await ok(admin,'/admin/models/'+m.model.id+'/enable','POST',{expected_revision:m.revision});if(!baseModel)baseModel=m.model.id;else presetModel=m.model.id;}
 await plan('visitor',0,[baseModel]);await plan('basic',0,[baseModel]);await plan('pro',4,[baseModel],5,['short','medium']);
 sql("UPDATE wordweave.growth_settings SET activated_at=clock_timestamp()-interval '60 days'; INSERT INTO wordweave.growth_levels(level_no,min_experience,reward_enabled,points) VALUES(1,0,false,0) ON CONFLICT(level_no) DO NOTHING; INSERT INTO wordweave.checkin_rules(effective_day,base_points,step_points,cap_points,normal_experience) VALUES(CURRENT_DATE-60,1,1,7,1) ON CONFLICT(effective_day) DO NOTHING");
 await ok(visitor,'/bootstrap');await ok(refundVisitor,'/bootstrap');userId=await register(learner,'preset');trialId=await register(trial,'trial');
 const input={title:'Ideas woven together',configuration:{model_id:presetModel,entries:['learn','weave','book'],meaning_language:'en',scenario:'business',length:'medium'}};
 presetId=(await ok(admin,'/admin/presets','POST',input)).preset.id;
 zhId=(await ok(admin,'/admin/presets','POST',{title:'一起学习',configuration:{model_id:baseModel,entries:['learn'],meaning_language:'zh',scenario:'story',length:'short'}})).preset.id;
 await test('P01','Admin previews have separate usage without learner quota and never auto-publish',async()=>{
  const before=learningCount(),n=provider.calls,options=await ok(admin,'/admin/generation-options');expect(options.lengths).toEqual(['short','medium','long','xlong']);expect(options).not.toHaveProperty('quota');expect((await call(visitor,'/admin/generation-options')).status).toBe(401);expect((await call(learner,'/admin/generation-options')).status).toBe(403);
  expect((await call(visitor,'/presets/'+presetId)).status).toBe(404);for(let k=0;k<2;k++){const events=await preview(presetId);expect(events.filter(x=>x.event.startsWith('preview.')&&x.event!=='preview.started').map(x=>x.event)).toEqual(['preview.validated']);expect((await call(visitor,'/presets/'+presetId)).status).toBe(404);}expect(provider.calls).toBe(n+2);expect(learningCount()).toBe(before);
  await publish(presetId);await preview(zhId);await publish(zhId);const usage=await ok(admin,'/admin/preset-preview-usage?start_date=2026-09-01&end_date=2026-09-30');expect(usage.summary.logical_runs).toBe(3);expect(usage.summary.provider_calls).toBe(3);expect(usage.summary.input_tokens).toBeNull();expect(usage.summary.cost).toBeNull();expect(usage.summary.unknown_calls).toBe(3);samples.push({action,usage:usage.summary,learningChargesUnchanged:true,publishedOnlyAfterCommand:true});
 });
 await plan('visitor',4,[baseModel]);await plan('basic',4,[baseModel]);
 await test('P02','Title-only draft preserves online version, reuses preview and rejects stale start',async()=>{const old=await publicPreset(),d=await adminPreset(presetId),n=provider.calls,count=learningCount();await ok(admin,'/admin/presets/'+presetId,'PUT',{...input,title:'Shared ideas for a brighter day',expected_revision:d.revision});expect(await publicPreset()).toEqual(old);await publish(presetId);const now=await publicPreset();expect(now.title).toBe('Shared ideas for a brighter day');expect(now.sample).toEqual(old.sample);expect(now.configuration).toEqual(old.configuration);const stale=await call(visitor,'/presets/'+presetId+'/generations/stream','POST',{published_version:old.published_version});expect(stale.status).toBe(409);expect(stale.body.code).toBe('preset_changed');expect(provider.calls).toBe(n);expect(learningCount()).toBe(count);samples.push({action,oldVersion:old.published_version,newVersion:now.published_version,staleCode:stale.body.code,noGeneration:true});});
 await test('P03','Changed generation parameters require a new successful preview; failed preview preserves published snapshot',async()=>{const old=await publicPreset(),d=await adminPreset(presetId);await ok(admin,'/admin/presets/'+presetId,'PUT',{...input,title:old.title,configuration:{...input.configuration,scenario:'news'},expected_revision:d.revision});let current=await adminPreset(presetId),r=await call(admin,'/admin/presets/'+presetId+'/publish','POST',{draft_version:current.preset.draft_version,expected_revision:current.revision,confirmed:true});expect(r.status).toBe(422);expect(r.body.code).toBe('preview_required');const failed=await preview(presetId,'invalid');expect(failed.some(x=>x.event==='preview.failed')).toBe(true);expect(await publicPreset()).toEqual(old);await preview(presetId);expect(await publicPreset()).toEqual(old);await publish(presetId);const now=await publicPreset();expect(now.configuration.scenario).toBe('news');expect(now.sample.passage.length).toBeGreaterThan(700);samples.push({action,invalidPublish:r.body.code,failedPreviewKeptOnline:true,newVersion:now.published_version});});
 await test('P04','Visitor preset overrides configuration restrictions but charges visitor once; claim preserves content and basic quota',async()=>{const preset=await publicPreset(),n=provider.calls,count=learningCount(),before=(await ok(visitor,'/generation-options')).quota;const normalReject=await call(visitor,'/generations/stream','POST',{...input.configuration,scenario:'news'});expect(normalReject.status).toBeGreaterThanOrEqual(400);expect(normalReject.status).toBeLessThan(500);const injected=await call(visitor,'/presets/'+presetId+'/generations/stream','POST',{published_version:preset.published_version,entries:['learn']});expect(injected.status).toBe(400);expect(provider.calls).toBe(n);expect(learningCount()).toBe(count);
  provider.mode='valid';const s=await begin(visitor);await s.done;terminal(s,'validated');expect(charge(s.run_id)).toMatchObject({source_kind:'visitor',state:'consumed'});expect((await ok(visitor,'/generation-options')).quota.remaining).toBe(before.remaining-1);const claim=await runCall(s,visitor,'/visitor-claim');expect(claim.status()).toBe(200);const token=(await claim.json()).data.claim_token;const uid=await register(visitor,'claim'),quota=(await ok(visitor,'/generation-options')).quota;const saved=await raw(visitor,'/visitor-claims/consume','POST',{}, {'X-Claim-Token':token});expect(saved.status()).toBe(201);const batch=(await saved.json()).data;expect(batch.title).toBe('learn · weave · book');const repeated=await raw(visitor,'/visitor-claims/consume','POST',{}, {'X-Claim-Token':token});expect(repeated.status()).toBe(200);expect((await repeated.json()).data.batch_id).toBe(batch.batch_id);expect((await ok(visitor,'/generation-options')).quota).toEqual(quota);expect(provider.calls).toBe(n+1);const detail=(await ok(visitor,'/me/batches/'+batch.batch_id)).batch;expect(detail.passage).toBe(s.events.find(x=>x.event==='generation.validated').data.result.passage);expect((await ok(visitor,'/me/growth')).checkin.signed_today).toBe(true);samples.push({action,run:s.run_id,charge:charge(s.run_id),claimedUser:uid,batch:batch.batch_id,title:batch.title,providerCalls:1,basicQuotaUnchanged:true});});
 await test('P05','Learner preset charges account base quota only, leaves ordinary permissions restricted and rejects exhausted quota',async()=>{const n=provider.calls,before=await ok(learner,'/generation-options'),vis=sql("SELECT count(*) FROM wordweave.generation_charges WHERE source_kind='visitor'");provider.mode='valid';const s=await begin(learner);await s.done;terminal(s,'validated');expect(charge(s.run_id)).toMatchObject({source_kind:'plan',origin:'base',state:'consumed'});expect((await ok(learner,'/generation-options')).quota.remaining).toBe(before.quota.remaining-1);expect((await ok(learner,'/generation-options')).models.map(x=>x.id)).toEqual([baseModel]);expect(sql("SELECT count(*) FROM wordweave.generation_charges WHERE source_kind='visitor'")).toBe(vis);const saved=await runCall(s,learner,'/save');expect(saved.status()).toBe(201);await plan('basic',0,[baseModel]);const reject=await call(learner,'/presets/'+presetId+'/generations/stream','POST',await publicBody());expect(reject.status).toBe(429);expect(provider.calls).toBe(n+1);await plan('basic',4,[baseModel]);samples.push({action,run:s.run_id,charge:charge(s.run_id),visitorLedgerUnchanged:true,noQuotaStatus:429});});
 await test('P06','In-flight preset survives unpublish with original snapshot; new requests see unavailable',async()=>{provider.mode='hold';const s=await begin(learner);try{const d=await adminPreset(presetId);await ok(admin,'/admin/presets/'+presetId+'/unpublish','POST',{expected_revision:d.revision,confirmed:true});expect((await call(learner,'/presets/'+presetId)).status).toBe(404);provider.release();await s.done;terminal(s,'validated');const save=await runCall(s,learner,'/save');expect(save.status()).toBe(201);const id=(await save.json()).data.batch_id,detail=(await ok(learner,'/me/batches/'+id)).batch;expect(detail.targets.map(x=>x.entry)).toEqual(['learn','weave','book']);samples.push({action,run:s.run_id,batch:id,saveStatus:201,newEntryStatus:404,targets:detail.targets.map(x=>x.entry)});}finally{provider.release();provider.mode='valid';await publish(presetId);}});
 await test('P07','Disabled preset model preserves public full sample, blocks new generation without substitution or charge',async()=>{const d=await ok(admin,'/admin/models/'+presetModel),before=learningCount(),n=provider.calls;await ok(admin,'/admin/models/'+presetModel+'/disable','POST',{expected_revision:d.revision});try{const p=await publicPreset();expect(p.availability).toEqual({can_generate:false,reason:'model_unavailable'});expect(p.configuration.model.id).toBe(presetModel);expect(p.sample.passage.length).toBeGreaterThan(700);const r=await call(learner,'/presets/'+presetId+'/generations/stream','POST',{published_version:p.published_version});expect(r.status).toBe(422);expect(r.body.code).toBe('preset_unavailable');expect(provider.calls).toBe(n);expect(learningCount()).toBe(before);samples.push({action,reason:p.availability.reason,rejectedStatus:r.status,noCharge:true});}finally{const now=await ok(admin,'/admin/models/'+presetModel);await ok(admin,'/admin/models/'+presetModel+'/enable','POST',{expected_revision:now.revision});}});
 await test('R01','Visitor provider/validation failures refund the original visitor source exactly once',async()=>{provider.words=['learn'];provider.lang='en';for(const kind of ['http-failure','invalid'])await sourceFailure(refundVisitor,'/generations/stream',normal(),kind,{source_kind:'visitor'});});
 await test('R02','Visitor explicit cancel consumes once; transport interruption refunds and repeated terminal requests do not alter quota',async()=>{provider.mode='hold';const before=(await ok(refundVisitor,'/generation-options')).quota,s=await stream(refundVisitor,'/generations/stream',normal());for(let k=0;k<2;k++){const r=await runCall(s,refundVisitor,'/cancel');expect((await r.json()).data).toEqual({status:'cancelled',quota_refunded:false});}await s.done;terminal(s,'cancelled');expect(charge(s.run_id)).toMatchObject({source_kind:'visitor',state:'consumed'});expect((await ok(refundVisitor,'/generation-options')).quota.remaining).toBe(before.remaining-1);await sourceFailure(refundVisitor,'/generations/stream',normal(),'hold',{source_kind:'visitor'});samples.push({action,cancelledRun:s.run_id,charge:charge(s.run_id),consumedOnce:true});});
 const def=await ok(admin,'/admin/growth/items','POST',{kind:'plan_trial',name:{zh_CN:'验收体验卡',en_US:'QA09 plan trial'},description:{zh_CN:'隔离验证',en_US:'Disposable QA'},exchange_price:'0',activation_ttl_seconds:86400,effect:{kind:'plan_trial',target_plan_code:'pro',trial_seconds:86400}});await ok(admin,'/admin/growth/items/'+def.item.id+'/listing','PUT',{listed:true,expected_revision:def.revision});const item=(await ok(trial,'/shop/exchanges','POST',{definition_id:def.item.id,quantity:1},randomUUID())).receipt.items[0].item_id,pre=await ok(trial,'/me/items/'+item+'/activation-preview','POST',{});await ok(trial,'/me/items/'+item+'/activate','POST',{confirmation_token:pre.confirmation_token,confirm_discard:false},randomUUID());trialEnd=(await benefits()).trial.ends_at;
 await test('R03','Trial provider/validation/transport failures refund trial, preserving base quota and trial expiry',async()=>{const initial=await benefits();expect(initial.effective_origin).toBe('trial');provider.words=['learn'];provider.lang='en';for(const kind of ['http-failure','invalid','hold']){await sourceFailure(trial,'/generations/stream',normal(),kind,{source_kind:'plan',origin:'trial',plan_code:'pro'});expect(await benefits()).toEqual(initial);}expect((await ok(trial,'/me/growth')).checkin.signed_today).toBe(false);samples.push({action,baseAndTrialQuotaUnchanged:true,trialEnd});});
 await test('R04','Admin base reset during in-flight trial failure cannot redirect refund or change trial expiry',async()=>{provider.mode='hold';const before=await benefits(),s=await stream(trial,'/generations/stream',normal());expect(charge(s.run_id)).toMatchObject({origin:'trial',state:'reserved'});const d=await ok(admin,'/admin/users/'+trialId);await ok(admin,'/admin/users/'+trialId+'/group','PUT',{group_code:'pro',confirmed:true,expected_base_revision:d.user.base_revision});const reset=await benefits();expect(reset.effective_origin).toBe('base');s.abort();await s.done;await expect.poll(()=>charge(s.run_id).state).toBe('refunded');const after=await benefits();expect(after.base_plan).toEqual(reset.base_plan);expect(after.trial).toEqual(before.trial);expect(after.trial.ends_at).toBe(trialEnd);expect(charge(s.run_id)).toMatchObject({origin:'trial',state:'refunded'});samples.push({action,run:s.run_id,charge:charge(s.run_id),before,after});});
 dump('fixture.json',{baseModel,presetModel,presetId,zhId,userId,trialId});
}catch(e){results.push({id:'SETUP',result:'FAIL',error:String(e)});console.log('SETUP',String(e));}
finally{dump('api-results.json',{results,samples,providerRequests:provider.requests,localProviderCalls:provider.calls,realProviderCalls:0});await stop(browser);await provider.close();if(results.some(x=>x.result==='FAIL'))process.exitCode=1;}
