import {createRequire} from 'node:module';import fs from 'node:fs';import crypto from 'node:crypto';
const R='/Users/xekinzhuo/Desktop/xekin_develop/ai-en-learning-development/ai-en-learning';const require=createRequire(R+'/frontend/package.json'),{chromium}=require('@playwright/test');const D=R+'/.planning/milestones/M002/design',E=D+'/evidence/ui25';const C=JSON.parse(fs.readFileSync(D+'/copy.json'));const browser=await chromium.launch({headless:true});const checks=[],errors=[];
for(const lang of ['zh','en'])for(const width of [1440,320])for(const route of ['trial','create']){
 const p=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'});p.on('pageerror',e=>errors.push(e.message));await p.goto(`http://127.0.0.1:4186/prototype/?page=${route}&lang=${lang}&v=M002-UI-25`);await p.waitForSelector('.workspace');const section=p.locator('.workspace > div > section').first();
 const locked=route==='trial',facts={badge:await section.locator('.badge,.pill').count(),text:await section.innerText(),heading:await section.locator('h2').first().innerText(),overflow:await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),readonly:await p.locator('.trial-settings input,.trial-settings select').count()};
 const pass=!facts.overflow&&(locked?facts.badge===0&&facts.heading===C.static[lang+'.l.title.targets']&&facts.text.includes(C.templates[lang+'.trial.wordcount'].replace('{count}','3'))&&facts.readonly===0:await section.locator('[data-action="random"]').isVisible());checks.push({name:`${route} ${lang} ${width}`,pass,details:facts});
 if(locked&&lang==='zh'&&width===1440)await p.screenshot({path:E+'/04-trial-final-1440.png',fullPage:true});await p.close();
}
const source_sha256=Object.fromEntries(['prototype/app.js','copy.json'].map(n=>[n,crypto.createHash('sha256').update(fs.readFileSync(D+'/'+n)).digest('hex')]));const report={version:'M002-UI-25',status:checks.every(c=>c.pass)&&!errors.length?'PASS':'FAIL',checks,errors,source_sha256,screenshots:1,reason:'Visual inspection found a residual trial configuration-lock badge and artificial max word count; recheck trial and shared normal workspace.'};fs.writeFileSync(E+'/trial-recheck.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,checks:checks.length,failed:checks.filter(c=>!c.pass),errors},null,2));await browser.close();
