// build-lexicon is an explicit maintainer tool; normal builds never download data.
package main

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"time"

	"wordweave/internal/wordnet"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	sourcePath := flag.String("source", "", "existing official wn3.1.dict.tar.gz (offline rebuild)")
	download := flag.Bool("download", false, "explicitly download the checksum-pinned official source")
	destination := flag.String("out", "assets/lexicon", "generated artifact directory")
	saveSource := flag.String("save-source", "", "optional path for checksum-verified archive, for offline rebuilding")
	flag.Parse()
	if runtime.Version() != wordnet.BuilderGoVersion {
		return fmt.Errorf("asset builder requires %s; use the pinned backend Docker toolchain", wordnet.BuilderGoVersion)
	}
	var source []byte
	var err error
	if *download && *sourcePath == "" {
		client := &http.Client{Timeout: 2 * time.Minute}
		response, err := client.Get(wordnet.SourceURL)
		if err != nil {
			return err
		}
		defer response.Body.Close()
		if response.StatusCode != 200 {
			return fmt.Errorf("source HTTP %d", response.StatusCode)
		}
		source, err = io.ReadAll(io.LimitReader(response.Body, 32<<20))
		if err != nil {
			return err
		}
	} else if !*download && *sourcePath != "" {
		source, err = os.ReadFile(*sourcePath)
		if err != nil {
			return err
		}
	} else {
		return fmt.Errorf("choose exactly one of -source or -download")
	}
	digest := sha256.Sum256(source)
	if hex.EncodeToString(digest[:]) != wordnet.SourceSHA256 {
		return fmt.Errorf("source checksum mismatch")
	}
	if *saveSource != "" {
		if err := os.WriteFile(*saveSource, source, 0644); err != nil {
			return err
		}
	}
	data, notice, err := wordnet.Build(bytes.NewReader(source))
	if err != nil {
		return err
	}
	var compressed bytes.Buffer
	zip, _ := gzip.NewWriterLevel(&compressed, gzip.BestCompression)
	if err := json.NewEncoder(zip).Encode(data); err != nil {
		return err
	}
	if err := zip.Close(); err != nil {
		return err
	}
	asset := compressed.Bytes()
	assetDigest := sha256.Sum256(asset)
	hexDigest := hex.EncodeToString(assetDigest[:])
	manifest := wordnet.Manifest{BuilderGoVersion: wordnet.BuilderGoVersion, ParserVersion: wordnet.ParserVersion, SourceURL: wordnet.SourceURL, SourceSHA256: wordnet.SourceSHA256, AssetSHA256: hexDigest, AssetBytes: len(asset), Lemmas: len(data.Lemmas), Edges: len(data.Edges), Exceptions: len(data.Exceptions)}
	manifestJSON, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(*destination, 0755); err != nil {
		return err
	}
	outputs := map[string][]byte{
		"wordnet31.json.gz": asset, "manifest.json": append(manifestJSON, '\n'), "NOTICE.txt": []byte(notice),
		"digest.go": []byte("// Code generated by cmd/build-lexicon; DO NOT EDIT.\npackage lexicon\n\nconst AssetSHA256 = \"" + hexDigest + "\"\n"),
	}
	for name, body := range outputs {
		if err := os.WriteFile(filepath.Join(*destination, name), body, 0644); err != nil {
			return err
		}
	}
	fmt.Println(string(manifestJSON))
	return nil
}
