import {execFileSync,spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {dir,sql} from './lib.mjs';
const root=resolve(dir,'../../../../../..'),json=p=>JSON.parse(readFileSync(join(dir,p),'utf8')),sha=b=>createHash('sha256').update(b).digest('hex'),docker=a=>execFileSync('docker',a,{encoding:'utf8'}).trim();
const source=json('source-baseline.json'),modified=Object.entries(source.hashes).filter(([p,h])=>!existsSync(join(root,p))||sha(readFileSync(join(root,p)))!==h).map(([p])=>p);
const production=['frontend/app/pages/login.vue','frontend/app/pages/register.vue','frontend/app/pages/account.vue','frontend/i18n/locales/en-US.json'];
const allowed=[...production,'.planning/milestones/M001/implementation/frontend-cr037-080-worktree-plan.md'];
if(modified.some(p=>!allowed.includes(p))||production.some(p=>!modified.includes(p)))throw Error('Unexpected source edits '+modified.join(','));
const chromium=json('browser-chromium-complete-results.json'),webkitVisual=json('browser-webkit-visual-results.json'),e2e=json('e2e-full-final.json'),quality=json('quality-commands-final.json');
const checks={status:'PARTIAL_BROWSER_COVERAGE',chromiumComplete:chromium.counts,webkitVisual:webkitVisual.counts,unverified:['macOS WebKit password-input and complete update/session flow: native process exception; Linux fallback NOT_RUN']};
if(chromium.counts.PASS!==85||chromium.counts.FAIL||chromium.counts.ERROR||webkitVisual.counts.PASS!==55||webkitVisual.counts.FAIL||webkitVisual.counts.ERROR||e2e.stats.expected!==122||e2e.stats.unexpected||e2e.stats.skipped||e2e.stats.flaky||quality.length!==2||quality.some(r=>r.status!==0))throw Error('Unexpected completed development check results');
const environment={...json('environment.json'),frontend:json('runtime-final.json').frontend};
const files=[...production,'frontend/tests/unit/auth-card-design.test.ts','frontend/tests/e2e/cr037-auth-account.spec.ts'];
const uatNames=['wordweave_uat-frontend-1','wordweave_uat-backend-1','wordweave_uat-nginx-1','wordweave_uat-postgres-1'];
const uatSnapshot=()=>JSON.parse(docker(['inspect',...uatNames])).map(x=>({name:x.Name,id:x.Id,image:x.Image,started:x.State.StartedAt}));
if(JSON.stringify(uatSnapshot())!==JSON.stringify(json('baseline.json').uat))throw Error('UAT changed; inspect before cleanup');
const data=JSON.parse(sql("SELECT json_build_object('accounts',(SELECT count(*) FROM wordweave.accounts),'batches',(SELECT count(*) FROM wordweave.learning_batches),'models',(SELECT count(*) FROM wordweave.ai_models),'credentials',(SELECT count(*) FROM wordweave.openrouter_credentials),'generation_runs',(SELECT count(*) FROM wordweave.generation_runs))"));
const names=['ww-dev-080-nginx','ww-dev-080-frontend','ww-dev-080-backend','ww-dev-080-db'],networks=['ww-dev-080','ww-dev-080-edge'];
for(const n of names)if(JSON.parse(docker(['inspect',n]))[0].Config.Labels['wordweave.dev']!=='080')throw Error('Unowned '+n);
for(const n of networks)if(JSON.parse(docker(['network','inspect',n]))[0].Labels['wordweave.dev']!=='080')throw Error('Unowned network '+n);
if(data.accounts!==14||data.batches||data.credentials||data.models||data.generation_runs)throw Error('Unexpected synthetic data '+JSON.stringify(data));
writeFileSync(join(dir,'candidate.json'),JSON.stringify({date:new Date().toISOString(),agent:'frontend-claire',status:'implemented_with_explicit_browser_validation_gap_pending_independent_qa',frontend:environment.frontend,backend:environment.backend,sourceFiles:files.map(path=>({path,sha256:sha(readFileSync(join(root,path)))})),modifiedExistingFiles:modified,quality,unit:{files:21,tests:196,newRegression:22},browser:checks,e2e:e2e.stats,retainedInitialFailures:{unit:{total:22,failed:11},browser:json('browser-results.json').counts,e2e:json('e2e-full.json').stats,macNativeRuns:[json('browser-final-results.json').counts,json('browser-final2-results.json').counts,json('browser-webkit-keyboard-results.json').counts]},linuxFallback:json('linux-fallback-status.json').status,noUatDeployment:true,noRealAiCalls:true},null,2),{flag:'wx'});
for(const n of names){docker(['stop',n]);docker(['rm',n]);}
for(const n of networks)docker(['network','rm',n]);
const released=port=>spawnSync('lsof',['-nP','-iTCP:'+port,'-sTCP:LISTEN']).status===1;
const result={date:new Date().toISOString(),uatUnchanged:JSON.stringify(uatSnapshot())===JSON.stringify(json('baseline.json').uat),removedContainers:names,removedNetworks:networks,data,portsReleased:{6101:released(6101),3300:released(3300),38080:released(38080)},dataRecovery:'Only DEV080 synthetic tmpfs DB removed; exact contents unrecoverable, setup and browser scripts reproduce. UAT data preserved.'};
writeFileSync(join(dir,'cleanup.json'),JSON.stringify(result,null,2),{flag:'wx'});
console.log(JSON.stringify({candidate:environment.frontend,checks,e2e:e2e.stats,cleanup:result}));
if(!result.uatUnchanged||Object.values(result.portsReleased).some(v=>!v))process.exitCode=1;
