// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entitlement.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAccountRollingUsage = `-- name: CountAccountRollingUsage :one
SELECT count(*)::integer AS used,
       extract(epoch FROM coalesce((min(started_at) FILTER (
         WHERE started_at >= greatest(clock_timestamp() - interval '24 hours', $1::timestamptz)
       )), '1970-01-01 00:00:00+00'::timestamptz))::bigint AS oldest_charge_unix
FROM wordweave.generation_runs
WHERE account_id = $2
  AND quota_charged
  AND started_at >= greatest(clock_timestamp() - interval '24 hours', $1::timestamptz)
`

type CountAccountRollingUsageParams struct {
	QuotaResetAt pgtype.Timestamptz `json:"quota_reset_at"`
	AccountID    uuid.NullUUID      `json:"account_id"`
}

type CountAccountRollingUsageRow struct {
	Used             int32 `json:"used"`
	OldestChargeUnix int64 `json:"oldest_charge_unix"`
}

func (q *Queries) CountAccountRollingUsage(ctx context.Context, arg CountAccountRollingUsageParams) (CountAccountRollingUsageRow, error) {
	row := q.db.QueryRow(ctx, countAccountRollingUsage, arg.QuotaResetAt, arg.AccountID)
	var i CountAccountRollingUsageRow
	err := row.Scan(&i.Used, &i.OldestChargeUnix)
	return i, err
}

const countVisitorRollingUsage = `-- name: CountVisitorRollingUsage :one
SELECT count(*)::integer AS used,
       extract(epoch FROM coalesce(min(started_at), '1970-01-01 00:00:00+00'::timestamptz))::bigint AS oldest_charge_unix
FROM wordweave.generation_runs
WHERE visitor_id = $1
  AND quota_charged
  AND started_at >= clock_timestamp() - interval '24 hours'
`

type CountVisitorRollingUsageRow struct {
	Used             int32 `json:"used"`
	OldestChargeUnix int64 `json:"oldest_charge_unix"`
}

func (q *Queries) CountVisitorRollingUsage(ctx context.Context, visitorID uuid.NullUUID) (CountVisitorRollingUsageRow, error) {
	row := q.db.QueryRow(ctx, countVisitorRollingUsage, visitorID)
	var i CountVisitorRollingUsageRow
	err := row.Scan(&i.Used, &i.OldestChargeUnix)
	return i, err
}

const getEntitlementGroup = `-- name: GetEntitlementGroup :one
SELECT code, rolling_quota_limit, max_entries_per_run, updated_at
FROM wordweave.entitlement_groups
WHERE code = $1
`

func (q *Queries) GetEntitlementGroup(ctx context.Context, code string) (WordweaveEntitlementGroup, error) {
	row := q.db.QueryRow(ctx, getEntitlementGroup, code)
	var i WordweaveEntitlementGroup
	err := row.Scan(
		&i.Code,
		&i.RollingQuotaLimit,
		&i.MaxEntriesPerRun,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveAccountGeneration = `-- name: HasActiveAccountGeneration :one
SELECT EXISTS(
  SELECT 1 FROM wordweave.generation_runs
  WHERE account_id = $1 AND call_status = 'active'
)
`

func (q *Queries) HasActiveAccountGeneration(ctx context.Context, accountID uuid.NullUUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveAccountGeneration, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasActiveVisitorGeneration = `-- name: HasActiveVisitorGeneration :one
SELECT EXISTS(
  SELECT 1 FROM wordweave.generation_runs
  WHERE visitor_id = $1 AND call_status = 'active'
)
`

func (q *Queries) HasActiveVisitorGeneration(ctx context.Context, visitorID uuid.NullUUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveVisitorGeneration, visitorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasOpenRouterCredential = `-- name: HasOpenRouterCredential :one
SELECT EXISTS(SELECT 1 FROM wordweave.openrouter_credentials WHERE provider = 'openrouter')
`

func (q *Queries) HasOpenRouterCredential(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasOpenRouterCredential)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGroupLengths = `-- name: ListGroupLengths :many
SELECT length_code
FROM wordweave.group_lengths
WHERE group_code = $1
ORDER BY CASE length_code WHEN 'short' THEN 1 WHEN 'medium' THEN 2 WHEN 'long' THEN 3 WHEN 'xlong' THEN 4 END
`

func (q *Queries) ListGroupLengths(ctx context.Context, groupCode string) ([]string, error) {
	rows, err := q.db.Query(ctx, listGroupLengths, groupCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var length_code string
		if err := rows.Scan(&length_code); err != nil {
			return nil, err
		}
		items = append(items, length_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupModels = `-- name: ListGroupModels :many
SELECT m.id, m.display_name, m.description, m.enabled
FROM wordweave.group_models gm
JOIN wordweave.ai_models m ON m.id = gm.model_id
WHERE gm.group_code = $1 AND m.enabled
ORDER BY lower(m.display_name), m.id
`

type ListGroupModelsRow struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	Enabled     bool        `json:"enabled"`
}

func (q *Queries) ListGroupModels(ctx context.Context, groupCode string) ([]ListGroupModelsRow, error) {
	rows, err := q.db.Query(ctx, listGroupModels, groupCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupModelsRow{}
	for rows.Next() {
		var i ListGroupModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Description,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
