// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO wordweave.accounts(username, password_hash, role, group_code, ui_locale)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password_hash, role, group_code, status, ui_locale,
          quota_reset_at, created_at, updated_at
`

type CreateAccountParams struct {
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	GroupCode    pgtype.Text `json:"group_code"`
	UiLocale     pgtype.Text `json:"ui_locale"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (WordweaveAccount, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.GroupCode,
		arg.UiLocale,
	)
	var i WordweaveAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.GroupCode,
		&i.Status,
		&i.UiLocale,
		&i.QuotaResetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAccountSession = `-- name: CreateAccountSession :one
INSERT INTO wordweave.account_sessions(account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, created_at, last_seen_at, expires_at
`

type CreateAccountSessionParams struct {
	AccountID uuid.UUID          `json:"account_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateAccountSessionRow struct {
	ID         uuid.UUID          `json:"id"`
	AccountID  uuid.UUID          `json:"account_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAccountSession(ctx context.Context, arg CreateAccountSessionParams) (CreateAccountSessionRow, error) {
	row := q.db.QueryRow(ctx, createAccountSession, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i CreateAccountSessionRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createVisitorIdentity = `-- name: CreateVisitorIdentity :one
INSERT INTO wordweave.visitor_identities(token_hash)
VALUES ($1)
RETURNING id, created_at, last_seen_at
`

type CreateVisitorIdentityRow struct {
	ID         uuid.UUID          `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) CreateVisitorIdentity(ctx context.Context, tokenHash []byte) (CreateVisitorIdentityRow, error) {
	row := q.db.QueryRow(ctx, createVisitorIdentity, tokenHash)
	var i CreateVisitorIdentityRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.LastSeenAt)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM wordweave.accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, accountID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAccountSession = `-- name: DeleteAccountSession :execrows
DELETE FROM wordweave.account_sessions
WHERE id = $1 AND account_id = $2
`

type DeleteAccountSessionParams struct {
	SessionID uuid.UUID `json:"session_id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) DeleteAccountSession(ctx context.Context, arg DeleteAccountSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountSession, arg.SessionID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAllAccountSessions = `-- name: DeleteAllAccountSessions :execrows
DELETE FROM wordweave.account_sessions WHERE account_id = $1
`

func (q *Queries) DeleteAllAccountSessions(ctx context.Context, accountID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllAccountSessions, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOtherAccountSessions = `-- name: DeleteOtherAccountSessions :execrows
DELETE FROM wordweave.account_sessions
WHERE account_id = $1 AND id <> $2
`

type DeleteOtherAccountSessionsParams struct {
	AccountID        uuid.UUID `json:"account_id"`
	CurrentSessionID uuid.UUID `json:"current_session_id"`
}

func (q *Queries) DeleteOtherAccountSessions(ctx context.Context, arg DeleteOtherAccountSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherAccountSessions, arg.AccountID, arg.CurrentSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAccountByID = `-- name: FindAccountByID :one
SELECT id, username, password_hash, role, group_code, status, ui_locale,
       quota_reset_at, created_at, updated_at
FROM wordweave.accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) FindAccountByID(ctx context.Context, id uuid.UUID) (WordweaveAccount, error) {
	row := q.db.QueryRow(ctx, findAccountByID, id)
	var i WordweaveAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.GroupCode,
		&i.Status,
		&i.UiLocale,
		&i.QuotaResetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAccountByUsername = `-- name: FindAccountByUsername :one
SELECT id, username, password_hash, role, group_code, status, ui_locale,
       quota_reset_at, created_at, updated_at
FROM wordweave.accounts
WHERE lower(username) = lower($1)
LIMIT 1
`

func (q *Queries) FindAccountByUsername(ctx context.Context, username string) (WordweaveAccount, error) {
	row := q.db.QueryRow(ctx, findAccountByUsername, username)
	var i WordweaveAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.GroupCode,
		&i.Status,
		&i.UiLocale,
		&i.QuotaResetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAccountSession = `-- name: FindAccountSession :one
SELECT s.id AS session_id, s.account_id, s.created_at AS session_created_at,
       s.last_seen_at, s.expires_at,
       a.username, a.password_hash, a.role, a.group_code, a.status, a.ui_locale,
       a.quota_reset_at, a.created_at AS account_created_at
FROM wordweave.account_sessions s
JOIN wordweave.accounts a ON a.id = s.account_id
WHERE s.token_hash = $1
LIMIT 1
`

type FindAccountSessionRow struct {
	SessionID        uuid.UUID          `json:"session_id"`
	AccountID        uuid.UUID          `json:"account_id"`
	SessionCreatedAt pgtype.Timestamptz `json:"session_created_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Username         string             `json:"username"`
	PasswordHash     string             `json:"password_hash"`
	Role             string             `json:"role"`
	GroupCode        pgtype.Text        `json:"group_code"`
	Status           string             `json:"status"`
	UiLocale         pgtype.Text        `json:"ui_locale"`
	QuotaResetAt     pgtype.Timestamptz `json:"quota_reset_at"`
	AccountCreatedAt pgtype.Timestamptz `json:"account_created_at"`
}

func (q *Queries) FindAccountSession(ctx context.Context, tokenHash []byte) (FindAccountSessionRow, error) {
	row := q.db.QueryRow(ctx, findAccountSession, tokenHash)
	var i FindAccountSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.AccountID,
		&i.SessionCreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.GroupCode,
		&i.Status,
		&i.UiLocale,
		&i.QuotaResetAt,
		&i.AccountCreatedAt,
	)
	return i, err
}

const findVisitorIdentity = `-- name: FindVisitorIdentity :one
SELECT id, created_at, last_seen_at
FROM wordweave.visitor_identities
WHERE token_hash = $1
LIMIT 1
`

type FindVisitorIdentityRow struct {
	ID         uuid.UUID          `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) FindVisitorIdentity(ctx context.Context, tokenHash []byte) (FindVisitorIdentityRow, error) {
	row := q.db.QueryRow(ctx, findVisitorIdentity, tokenHash)
	var i FindVisitorIdentityRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.LastSeenAt)
	return i, err
}

const touchAccountSession = `-- name: TouchAccountSession :exec
UPDATE wordweave.account_sessions
SET last_seen_at = clock_timestamp()
WHERE id = $1 AND last_seen_at < clock_timestamp() - interval '5 minutes'
`

func (q *Queries) TouchAccountSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAccountSession, sessionID)
	return err
}

const touchVisitorIdentity = `-- name: TouchVisitorIdentity :exec
UPDATE wordweave.visitor_identities
SET last_seen_at = clock_timestamp()
WHERE id = $1 AND last_seen_at < clock_timestamp() - interval '5 minutes'
`

func (q *Queries) TouchVisitorIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchVisitorIdentity, id)
	return err
}

const updateAccountLocale = `-- name: UpdateAccountLocale :one
UPDATE wordweave.accounts
SET ui_locale = $1
WHERE id = $2
RETURNING ui_locale
`

type UpdateAccountLocaleParams struct {
	UiLocale  pgtype.Text `json:"ui_locale"`
	AccountID uuid.UUID   `json:"account_id"`
}

func (q *Queries) UpdateAccountLocale(ctx context.Context, arg UpdateAccountLocaleParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, updateAccountLocale, arg.UiLocale, arg.AccountID)
	var ui_locale pgtype.Text
	err := row.Scan(&ui_locale)
	return ui_locale, err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :exec
UPDATE wordweave.accounts
SET password_hash = $1
WHERE id = $2
`

type UpdateAccountPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	AccountID    uuid.UUID `json:"account_id"`
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAccountPassword, arg.PasswordHash, arg.AccountID)
	return err
}
