// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type WordweaveAccount struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	GroupCode    pgtype.Text        `json:"group_code"`
	Status       string             `json:"status"`
	UiLocale     pgtype.Text        `json:"ui_locale"`
	QuotaResetAt pgtype.Timestamptz `json:"quota_reset_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WordweaveAccountSession struct {
	ID         uuid.UUID          `json:"id"`
	AccountID  uuid.UUID          `json:"account_id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type WordweaveAiModel struct {
	ID              uuid.UUID          `json:"id"`
	DisplayName     string             `json:"display_name"`
	Description     pgtype.Text        `json:"description"`
	ProviderModelID string             `json:"provider_model_id"`
	Enabled         bool               `json:"enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type WordweaveBatchTarget struct {
	ID                  uuid.UUID `json:"id"`
	OwnerID             uuid.UUID `json:"owner_id"`
	BatchID             uuid.UUID `json:"batch_id"`
	VocabularyEntryID   int64     `json:"vocabulary_entry_id"`
	SourceEntrySnapshot string    `json:"source_entry_snapshot"`
	InputOrder          int32     `json:"input_order"`
	EntryMeaning        string    `json:"entry_meaning"`
	HintPhrase          string    `json:"hint_phrase"`
	HintSurface         string    `json:"hint_surface"`
	HintStart           int32     `json:"hint_start"`
	HintEnd             int32     `json:"hint_end"`
}

type WordweaveEntitlementGroup struct {
	Code              string             `json:"code"`
	RollingQuotaLimit pgtype.Int4        `json:"rolling_quota_limit"`
	MaxEntriesPerRun  int32              `json:"max_entries_per_run"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type WordweaveGenerationDraft struct {
	RunID           uuid.UUID          `json:"run_id"`
	AccessTokenHash []byte             `json:"access_token_hash"`
	Payload         []byte             `json:"payload"`
	ValidatedAt     pgtype.Timestamptz `json:"validated_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type WordweaveGenerationRun struct {
	ID                       uuid.UUID          `json:"id"`
	AccountID                uuid.NullUUID      `json:"account_id"`
	VisitorID                uuid.NullUUID      `json:"visitor_id"`
	CreditedAccountID        uuid.NullUUID      `json:"credited_account_id"`
	GroupCodeSnapshot        string             `json:"group_code_snapshot"`
	ModelID                  uuid.UUID          `json:"model_id"`
	ModelDisplayNameSnapshot string             `json:"model_display_name_snapshot"`
	ProviderModelIDSnapshot  string             `json:"provider_model_id_snapshot"`
	MeaningLanguage          string             `json:"meaning_language"`
	Scenario                 string             `json:"scenario"`
	LengthCode               string             `json:"length_code"`
	MinimumWordsSnapshot     int32              `json:"minimum_words_snapshot"`
	QuotaLimitSnapshot       pgtype.Int4        `json:"quota_limit_snapshot"`
	MaxEntriesSnapshot       int32              `json:"max_entries_snapshot"`
	CallStatus               string             `json:"call_status"`
	Disposition              string             `json:"disposition"`
	QuotaCharged             bool               `json:"quota_charged"`
	CountsTowardCumulative   bool               `json:"counts_toward_cumulative"`
	FailureCode              pgtype.Text        `json:"failure_code"`
	StartedAt                pgtype.Timestamptz `json:"started_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
}

type WordweaveGenerationRunEntry struct {
	RunID               uuid.UUID `json:"run_id"`
	VocabularyEntryID   int64     `json:"vocabulary_entry_id"`
	InputOrder          int32     `json:"input_order"`
	SourceEntrySnapshot string    `json:"source_entry_snapshot"`
}

type WordweaveGroupLength struct {
	GroupCode  string `json:"group_code"`
	LengthCode string `json:"length_code"`
}

type WordweaveGroupModel struct {
	GroupCode string    `json:"group_code"`
	ModelID   uuid.UUID `json:"model_id"`
}

type WordweaveHintOccurrence struct {
	ID              uuid.UUID `json:"id"`
	OwnerID         uuid.UUID `json:"owner_id"`
	BatchID         uuid.UUID `json:"batch_id"`
	TargetID        uuid.UUID `json:"target_id"`
	OccurrenceOrder int32     `json:"occurrence_order"`
	Surface         string    `json:"surface"`
	StartOffset     int32     `json:"start_offset"`
	EndOffset       int32     `json:"end_offset"`
}

type WordweaveLearningBatch struct {
	ID                        uuid.UUID          `json:"id"`
	OwnerID                   uuid.UUID          `json:"owner_id"`
	GenerationRunID           uuid.NullUUID      `json:"generation_run_id"`
	SavedAt                   pgtype.Timestamptz `json:"saved_at"`
	GroupCodeSnapshot         string             `json:"group_code_snapshot"`
	ModelDisplayNameSnapshot  string             `json:"model_display_name_snapshot"`
	ProviderModelIDSnapshot   string             `json:"provider_model_id_snapshot"`
	MeaningLanguage           string             `json:"meaning_language"`
	Scenario                  string             `json:"scenario"`
	LengthCode                string             `json:"length_code"`
	Passage                   string             `json:"passage"`
	Tags                      []string           `json:"tags"`
	ParticipatesInRangeReview bool               `json:"participates_in_range_review"`
	ExpectedTargetCount       int32              `json:"expected_target_count"`
	ValidatorVersion          string             `json:"validator_version"`
}

type WordweaveOpenrouterCredential struct {
	Provider             string             `json:"provider"`
	Ciphertext           []byte             `json:"ciphertext"`
	Nonce                []byte             `json:"nonce"`
	EncryptionKeyVersion int32              `json:"encryption_key_version"`
	DisplayFingerprint   string             `json:"display_fingerprint"`
	UpdatedBy            uuid.NullUUID      `json:"updated_by"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type WordweavePassageOccurrence struct {
	ID              uuid.UUID `json:"id"`
	OwnerID         uuid.UUID `json:"owner_id"`
	BatchID         uuid.UUID `json:"batch_id"`
	TargetID        uuid.UUID `json:"target_id"`
	OccurrenceOrder int32     `json:"occurrence_order"`
	Surface         string    `json:"surface"`
	StartOffset     int32     `json:"start_offset"`
	EndOffset       int32     `json:"end_offset"`
}

type WordweaveReviewResult struct {
	ID              uuid.UUID          `json:"id"`
	OwnerID         uuid.UUID          `json:"owner_id"`
	SessionID       uuid.UUID          `json:"session_id"`
	BatchID         uuid.UUID          `json:"batch_id"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Successful      bool               `json:"successful"`
	ErrorCount      int32              `json:"error_count"`
	SkipCount       int32              `json:"skip_count"`
	Stage1Completed bool               `json:"stage1_completed"`
	Stage2Completed bool               `json:"stage2_completed"`
}

type WordweaveReviewSession struct {
	ID             uuid.UUID          `json:"id"`
	OwnerID        uuid.UUID          `json:"owner_id"`
	Mode           string             `json:"mode"`
	SingleBatchID  uuid.NullUUID      `json:"single_batch_id"`
	RangeStartDate pgtype.Date        `json:"range_start_date"`
	RangeEndDate   pgtype.Date        `json:"range_end_date"`
	TimezoneName   pgtype.Text        `json:"timezone_name"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type WordweaveReviewSessionBatch struct {
	OwnerID    uuid.UUID `json:"owner_id"`
	SessionID  uuid.UUID `json:"session_id"`
	BatchID    uuid.UUID `json:"batch_id"`
	BatchOrder int32     `json:"batch_order"`
}

type WordweaveReviewSessionTarget struct {
	SessionID   uuid.UUID `json:"session_id"`
	BatchID     uuid.UUID `json:"batch_id"`
	TargetID    uuid.UUID `json:"target_id"`
	TargetOrder int32     `json:"target_order"`
}

type WordweaveSchemaMigration struct {
	Version   string             `json:"version"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type WordweaveVisitorClaim struct {
	ID                uuid.UUID          `json:"id"`
	RunID             uuid.UUID          `json:"run_id"`
	VisitorID         uuid.UUID          `json:"visitor_id"`
	TokenHash         []byte             `json:"token_hash"`
	Status            string             `json:"status"`
	ConsumedAccountID uuid.NullUUID      `json:"consumed_account_id"`
	ConsumedBatchID   uuid.NullUUID      `json:"consumed_batch_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type WordweaveVisitorIdentity struct {
	ID         uuid.UUID          `json:"id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

type WordweaveVocabularyEntry struct {
	ID          int64     `json:"id"`
	SnapshotID  uuid.UUID `json:"snapshot_id"`
	Entry       string    `json:"entry"`
	SourceOrder int32     `json:"source_order"`
}

type WordweaveVocabularySnapshot struct {
	ID         uuid.UUID          `json:"id"`
	Version    string             `json:"version"`
	Sha256     string             `json:"sha256"`
	ByteSize   int32              `json:"byte_size"`
	EntryCount int32              `json:"entry_count"`
	ImportedAt pgtype.Timestamptz `json:"imported_at"`
}
