// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const currentMigrationVersion = `-- name: CurrentMigrationVersion :one
SELECT version FROM wordweave.schema_migrations ORDER BY version DESC LIMIT 1
`

func (q *Queries) CurrentMigrationVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, currentMigrationVersion)
	var version string
	err := row.Scan(&version)
	return version, err
}

const databaseNow = `-- name: DatabaseNow :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) DatabaseNow(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, databaseNow)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}
