// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAccountRollingUsage(ctx context.Context, arg CountAccountRollingUsageParams) (CountAccountRollingUsageRow, error)
	CountVisitorRollingUsage(ctx context.Context, visitorID uuid.NullUUID) (CountVisitorRollingUsageRow, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error)
	CreateAccountSession(ctx context.Context, arg CreateAccountSessionParams) (CreateAccountSessionRow, error)
	CreateVisitorIdentity(ctx context.Context, tokenHash []byte) (CreateVisitorIdentityRow, error)
	CurrentMigrationVersion(ctx context.Context) (string, error)
	DatabaseNow(ctx context.Context) (pgtype.Timestamptz, error)
	DeleteAccount(ctx context.Context, accountID uuid.UUID) (int64, error)
	DeleteAccountSession(ctx context.Context, arg DeleteAccountSessionParams) (int64, error)
	DeleteAllAccountSessions(ctx context.Context, accountID uuid.UUID) (int64, error)
	DeleteOtherAccountSessions(ctx context.Context, arg DeleteOtherAccountSessionsParams) (int64, error)
	FindAccountByID(ctx context.Context, id uuid.UUID) (FindAccountByIDRow, error)
	FindAccountByUsername(ctx context.Context, username string) (FindAccountByUsernameRow, error)
	FindAccountSession(ctx context.Context, tokenHash []byte) (FindAccountSessionRow, error)
	FindVisitorIdentity(ctx context.Context, tokenHash []byte) (FindVisitorIdentityRow, error)
	GetEntitlementGroup(ctx context.Context, code string) (GetEntitlementGroupRow, error)
	GetVocabularySnapshot(ctx context.Context) (GetVocabularySnapshotRow, error)
	HasActiveAccountGeneration(ctx context.Context, accountID uuid.NullUUID) (bool, error)
	HasActiveVisitorGeneration(ctx context.Context, visitorID uuid.NullUUID) (bool, error)
	HasModelCredential(ctx context.Context) (bool, error)
	ListGroupLengths(ctx context.Context, groupCode string) ([]string, error)
	ListGroupModels(ctx context.Context, groupCode string) ([]ListGroupModelsRow, error)
	ResolveVocabularyEntries(ctx context.Context, entries []string) ([]ResolveVocabularyEntriesRow, error)
	SearchVocabulary(ctx context.Context, arg SearchVocabularyParams) ([]string, error)
	TouchAccountSession(ctx context.Context, sessionID uuid.UUID) error
	TouchVisitorIdentity(ctx context.Context, id uuid.UUID) error
	UpdateAccountLocale(ctx context.Context, arg UpdateAccountLocaleParams) (pgtype.Text, error)
	UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error
}

var _ Querier = (*Queries)(nil)
