// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vocabulary.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getVocabularySnapshot = `-- name: GetVocabularySnapshot :one
SELECT id, version, btrim(sha256)::text AS sha256, byte_size, entry_count, imported_at
FROM wordweave.vocabulary_snapshots
WHERE version = 'm001'
`

type GetVocabularySnapshotRow struct {
	ID         uuid.UUID          `json:"id"`
	Version    string             `json:"version"`
	Sha256     string             `json:"sha256"`
	ByteSize   int32              `json:"byte_size"`
	EntryCount int32              `json:"entry_count"`
	ImportedAt pgtype.Timestamptz `json:"imported_at"`
}

func (q *Queries) GetVocabularySnapshot(ctx context.Context) (GetVocabularySnapshotRow, error) {
	row := q.db.QueryRow(ctx, getVocabularySnapshot)
	var i GetVocabularySnapshotRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Sha256,
		&i.ByteSize,
		&i.EntryCount,
		&i.ImportedAt,
	)
	return i, err
}

const resolveVocabularyEntries = `-- name: ResolveVocabularyEntries :many
SELECT id, entry
FROM wordweave.vocabulary_entries
WHERE snapshot_id = (SELECT id FROM wordweave.vocabulary_snapshots WHERE version = 'm001')
  AND entry = ANY($1::text[])
ORDER BY array_position($1::text[], entry)
`

type ResolveVocabularyEntriesRow struct {
	ID    int64  `json:"id"`
	Entry string `json:"entry"`
}

func (q *Queries) ResolveVocabularyEntries(ctx context.Context, entries []string) ([]ResolveVocabularyEntriesRow, error) {
	rows, err := q.db.Query(ctx, resolveVocabularyEntries, entries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveVocabularyEntriesRow{}
	for rows.Next() {
		var i ResolveVocabularyEntriesRow
		if err := rows.Scan(&i.ID, &i.Entry); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVocabulary = `-- name: SearchVocabulary :many
SELECT entry
FROM wordweave.vocabulary_entries
WHERE snapshot_id = (SELECT id FROM wordweave.vocabulary_snapshots WHERE version = 'm001')
  AND lower(entry) LIKE '%' || lower($1) || '%'
ORDER BY
  CASE WHEN lower(entry) LIKE lower($1) || '%' THEN 0 ELSE 1 END,
  length(entry),
  entry
LIMIT $2
`

type SearchVocabularyParams struct {
	Query       string `json:"query"`
	ResultLimit int32  `json:"result_limit"`
}

func (q *Queries) SearchVocabulary(ctx context.Context, arg SearchVocabularyParams) ([]string, error) {
	rows, err := q.db.Query(ctx, searchVocabulary, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var entry string
		if err := rows.Scan(&entry); err != nil {
			return nil, err
		}
		items = append(items, entry)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
