import {createServer} from 'node:http';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {expect,start,stop,login,ok,call,sql,origin,out,t,dump,ready,instrument,randomUUID,env} from './harness.mjs';
let calls=0,action='SETUP';const results=[],samples=[],runtime=[];
const passage='A thoughtful student learns(learn) by building a steady learning(learn) routine through daily reading and discussion. Each morning the student reviews a few ideas, connects them with practical examples, and writes a short reflection. Friends later compare their observations, ask clear questions, and share useful explanations about what they learned(learn). This patient practice makes new knowledge easier to remember and apply with confidence.';
const provider=createServer(async(req,res)=>{if(req.url==='/models'){res.setHeader('content-type','application/json');res.end(JSON.stringify({data:[{id:'provider/integration',supported_parameters:['structured_outputs']}]}));return;}if(req.url!=='/chat/completions'){res.writeHead(404);res.end();return;}let body='';for await(const c of req)body+=c;calls++;const probe=JSON.parse(body).messages.some(m=>m.content.includes('fixed compatibility probe'));const candidate={passage:passage+(probe?' The group also discussed vulnerability(vulnerable) with empathy.':''),tags:['study'],targets:{learn:{entry_meaning:'gain knowledge through study',hint_phrase:'learning(learn) through learned(learn) examples while learning(learn)'}}};if(probe)candidate.targets.vulnerable={entry_meaning:'open to harm',hint_phrase:'vulnerable(vulnerable) communities'};res.setHeader('content-type','text/event-stream');res.end('data: '+JSON.stringify({choices:[{delta:{content:JSON.stringify(candidate)}}]})+'\n\ndata: [DONE]\n\n');});
await new Promise(r=>provider.listen(38082,'127.0.0.1',r));
const browser=await start(),admin=await browser.newContext(),user=await browser.newContext(),other=await browser.newContext(),page=await user.newPage();instrument(page,runtime,()=>action);
const copy=JSON.parse(readFileSync('.planning/milestones/M002/design/copy.json')),tr=(lang,k)=>copy.static[lang+'.'+k]??copy.templates[lang+'.'+k];
async function test(id,name,fn){action=id;try{await fn();results.push({id,name,result:'PASS'});}catch(e){results.push({id,name,result:'FAIL',error:String(e)});await page.screenshot({path:new URL(id+'-failure.png',out).pathname,fullPage:true}).catch(()=>{});}dump('library-results.json',{results,localProviderCalls:calls,realProviderCalls:0});console.log(id,results.at(-1).result);}
async function raw(c,path,method,data,extra={}){const headers={origin,'sec-fetch-site':'same-origin',...extra};if(method!=='GET')headers['x-csrf-token']=(await ok(c,'/bootstrap')).csrf_token;return c.request.fetch(origin+'/api/v1'+path,{method,data,headers});}
let userId,modelId,otherId,ids=[],deletedId,otherBatch;
const register=async(c,name)=>(await ok(c,'/auth/register','POST',{username:'qa7_'+name+'_'+Date.now(),password:env.ADMIN_PASSWORD,password_confirmation:env.ADMIN_PASSWORD,ui_locale:'en-US'})).actor.id;
async function generate(c){const r=await raw(c,'/generations/stream','POST',{model_id:modelId,meaning_language:'en',scenario:'story',length:'short',entries:['learn']});expect(r.status()).toBe(200);const events=(await r.text()).split('\n\n').filter(x=>x.startsWith('event:')).map(x=>{const lines=x.split('\n');return{event:lines[0].slice(7),data:JSON.parse(lines.find(x=>x.startsWith('data:')).slice(6))}});expect(events.filter(x=>/^generation\.(validated|failed|cancelled)$/.test(x.event)).map(x=>x.event)).toEqual(['generation.validated']);const s=events.find(x=>x.event==='generation.started').data;const saved=await raw(c,'/generations/'+s.run_id+'/save','POST',{}, {'X-Generation-Token':s.generation_token});expect(saved.status()).toBe(201);return(await saved.json()).data.batch_id;}
const listed=r=>r.body.data.items.map(x=>x.id);
const query=(entry,cursor='')=>'/me/batches?limit=1&entry='+encodeURIComponent(entry)+(cursor?'&cursor='+encodeURIComponent(cursor):'');
async function search(p,lang,entry){const wait=p.waitForResponse(r=>r.url().includes('/api/v1/me/batches?')&&new URL(r.url()).searchParams.get('entry')===entry.trim());await p.getByRole('searchbox').fill(entry);await p.getByRole('button',{name:tr(lang,'l.searchAction'),exact:true}).click();expect((await wait).status()).toBe(200);await expect(p.locator('.library-row')).toHaveCount(20);}
try{
 await login(admin);const cred=await ok(admin,'/admin/openrouter-credential');await ok(admin,'/admin/openrouter-credential','PUT',{api_key:'qa7-local-only-key',confirmed:true,expected_revision:cred.revision});const m=await ok(admin,'/admin/models','POST',{display_name:'QA07 deterministic provider',description:'Isolated local fixture',openrouter_model_id:'provider/integration'});modelId=m.model.id;await ok(admin,'/admin/models/'+modelId+'/enable','POST',{expected_revision:m.revision});const g=await ok(admin,'/admin/groups'),b=g.items.find(x=>x.code==='basic');await ok(admin,'/admin/groups/basic','PUT',{expected_revision:g.revision,priority:b.priority,max_entries:5,rolling_24h_limit:50,model_ids:[modelId],allowed_lengths:['short']});
 sql("UPDATE wordweave.growth_settings SET activated_at=clock_timestamp()-interval '60 days'; INSERT INTO wordweave.growth_levels(level_no,min_experience,reward_enabled,points) VALUES(1,0,false,0) ON CONFLICT(level_no) DO NOTHING; INSERT INTO wordweave.checkin_rules(effective_day,base_points,step_points,cap_points,normal_experience) VALUES(CURRENT_DATE-60,1,1,7,1) ON CONFLICT(effective_day) DO NOTHING");
 userId=await register(user,'library');otherId=await register(other,'other');for(let i=0;i<22;i++)ids.push(await generate(user));deletedId=ids.pop();otherBatch=await generate(other);const first=(await ok(user,'/me/batches/'+ids[0])).batch;await ok(user,'/me/batches/'+ids[0],'PATCH',{title:'book',expected_title_revision:first.title_revision});await ok(user,'/me/batches/'+ids[1],'PATCH',{participates_in_range_review:false});await ok(user,'/me/batches/'+deletedId,'DELETE',{});
 const stats=await ok(user,'/me/learning-summary');dump('fixture.json',{userId,otherId,modelId,ids,deletedId,otherBatch,stats});

 const last=await ok(user,'/me/batches/'+ids.at(-1));const longTitle='Learning grows through patient daily reading, thoughtful questions, and stories shared with friends';await ok(user,'/me/batches/'+ids.at(-1),'PATCH',{title:longTitle,expected_title_revision:last.batch.title_revision});
 async function loaded(lang){await page.goto(origin+'/library?entry=LEARN');await ready(page);await expect(page.getByRole('searchbox')).toHaveValue('LEARN');await expect(page.locator('.library-row')).toHaveCount(20);await page.getByRole('button',{name:tr(lang,'l.more'),exact:true}).click();await expect(page.locator('.library-row')).toHaveCount(21);await page.evaluate(()=>document.fonts.ready);}
 async function geometry(){return page.evaluate(id=>{const a=document.querySelector('[data-batch="'+id+'"] h2 a'),r=a?.getBoundingClientRect();return{y:scrollY,top:r?.top,bottom:r?.bottom,focus:document.activeElement===a,count:document.querySelectorAll('.library-row').length,width:document.documentElement.scrollWidth,viewport:innerWidth,height:innerHeight}},ids.at(-1));}
 const proto=await browser.newPage();for(const width of [320,1440]){await proto.setViewportSize({width,height:900});await proto.goto('http://127.0.0.1:4186/prototype/?page=library&lang=en');await proto.waitForTimeout(300);await proto.screenshot({path:new URL('prototype-library-'+width+'.png',out).pathname});}await proto.close();
 for(const [id,kind] of [['J01','page-link'],['J02','browser-history']]) await test(id,'CR012 '+kind+' return preserves query/range/scroll/focus in both languages and four widths',async()=>{for(const lang of ['en','zh']){await ok(user,'/me/ui-locale','PUT',{ui_locale:lang==='en'?'en-US':'zh-CN'});for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await loaded(lang);const link=page.locator('.library-row').last().locator('h2 a');await link.scrollIntoViewIfNeeded();const before=await geometry();await link.click();await expect(page.locator('.batch-title')).toHaveText(longTitle);if(kind==='browser-history')await page.goBack();else await page.getByRole('link',{name:tr(lang,'l.backLibrary'),exact:true}).click();await expect(page.locator('.library-row')).toHaveCount(21);await page.waitForTimeout(700);const after=await geometry();samples.push({action,lang,width,kind,before,after});await page.screenshot({path:new URL(id+'-'+lang+'-'+width+'.png',out).pathname});expect(Math.abs(after.y-before.y)).toBeLessThan(3);expect(after.focus).toBe(true);expect(after.top).toBeLessThan(after.height);expect(after.bottom).toBeGreaterThan(0);expect(after.width).toBeLessThanOrEqual(width);await expect(page.getByRole('searchbox')).toHaveValue('LEARN');expect(await page.locator('.library-row').evaluateAll(rows=>rows.map(row=>row.dataset.batch))).toEqual(ids);}}});
 await test('J03','CR012 direct navigation and departure via home retain normal initial scrolling',async()=>{await ok(user,'/me/ui-locale','PUT',{ui_locale:'en-US'});await page.setViewportSize({width:1440,height:900});await loaded('en');await page.locator('.library-row').last().getByRole('link',{name:t('l.detail'),exact:true}).click();await expect(page.locator('.batch-title')).toHaveText(longTitle);await page.locator('header a[href="/"]').first().click();await expect(page).toHaveURL(origin+'/');await page.locator('header a[href="/library"]').click();await expect(page.locator('.library-row')).toHaveCount(20);await page.waitForTimeout(700);expect(await page.evaluate(()=>scrollY)).toBe(0);await page.goto(origin+'/library/'+ids.at(-1)+'?entry=LEARN');await ready(page);await expect(page.locator('.batch-title')).toHaveText(longTitle);await page.getByRole('link',{name:t('l.backLibrary'),exact:true}).click();await expect(page.locator('.library-row')).toHaveCount(20);await page.waitForTimeout(700);expect(await page.evaluate(()=>scrollY)).toBe(0);});
 await test('J04','Title change returns to the current row with the original words and range',async()=>{await loaded('en');await page.locator('.library-row').last().locator('h2 a').click();await expect(page.locator('.batch-title')).toHaveText(longTitle);await page.getByRole('button',{name:t('l.title.edit'),exact:true}).click();await page.locator('#batch-title').fill('An edited reading journal');await page.getByRole('button',{name:t('l.title.save'),exact:true}).click();await expect(page.locator('.batch-title')).toHaveText('An edited reading journal');await page.getByRole('link',{name:t('l.backLibrary'),exact:true}).click();await expect(page.locator('.library-row')).toHaveCount(21);await page.waitForTimeout(700);const row=page.locator('.library-row').last();await expect(row.locator('h2 a')).toHaveText('An edited reading journal');await expect(row.locator('h2 a')).toBeFocused();await expect(row.locator('h2 a')).toBeInViewport();await expect(row.locator('.batch-targets')).toContainText('learn');await expect(page.getByRole('searchbox')).toHaveValue('LEARN');});
 const focusState=()=>page.evaluate(()=>({tag:document.activeElement?.tagName,id:document.activeElement?.id,type:document.activeElement?.getAttribute('type'),text:document.activeElement?.textContent?.slice(0,100),batch:document.activeElement?.closest('[data-batch]')?.getAttribute('data-batch')}));
 await test('J05','UI18 search completion returns keyboard focus to the search input',async()=>{const observed=[];for(const lang of ['en','zh']){await ok(user,'/me/ui-locale','PUT',{ui_locale:lang==='en'?'en-US':'zh-CN'});for(const width of [320,1440]){await page.setViewportSize({width,height:900});await page.goto(origin+'/library');await ready(page);await page.getByRole('searchbox').fill('LEARN');const response=page.waitForResponse(r=>r.url().includes('/api/v1/me/batches?')&&new URL(r.url()).searchParams.get('entry')==='LEARN');await page.getByRole('button',{name:tr(lang,'l.searchAction'),exact:true}).click();expect((await response).status()).toBe(200);await expect(page.locator('.library-row')).toHaveCount(20);await page.waitForTimeout(200);const focused=await page.getByRole('searchbox').evaluate(el=>document.activeElement===el);observed.push({lang,width,focused,actual:await focusState()});await page.screenshot({path:new URL('J05-'+lang+'-'+width+'.png',out).pathname});}}samples.push({action,observed});expect(observed.every(x=>x.focused)).toBe(true);});
 await test('J06','UI18 load-more completion focuses the first newly appended title',async()=>{const observed=[];for(const lang of ['en','zh']){await ok(user,'/me/ui-locale','PUT',{ui_locale:lang==='en'?'en-US':'zh-CN'});for(const width of [320,1440]){await page.setViewportSize({width,height:900});await page.goto(origin+'/library?entry=LEARN');await ready(page);await expect(page.locator('.library-row')).toHaveCount(20);await page.getByRole('button',{name:tr(lang,'l.more'),exact:true}).click();await expect(page.locator('.library-row')).toHaveCount(21);await page.waitForTimeout(200);const focused=await page.locator('.library-row').last().locator('h2 a').evaluate(el=>document.activeElement===el);observed.push({lang,width,focused,actual:await focusState()});await page.screenshot({path:new URL('J06-'+lang+'-'+width+'.png',out).pathname});}}samples.push({action,observed});expect(observed.every(x=>x.focused)).toBe(true);});
 await test('J07','Participation update keeps checkbox focus and synchronizes whole-library count',async()=>{await ok(user,'/me/ui-locale','PUT',{ui_locale:'en-US'});await page.goto(origin+'/library?entry=LEARN');await ready(page);const count=Number(await page.locator('.library-stats dd').nth(2).textContent()),row=page.locator('.library-row').first(),box=row.getByRole('checkbox');await expect(box).toBeChecked();const response=page.waitForResponse(r=>r.url().includes('/api/v1/me/batches/'+ids[0])&&r.request().method()==='PATCH');await box.click();expect((await response).status()).toBe(200);await expect(box).not.toBeChecked();await expect(page.locator('.library-stats dd').nth(2)).toHaveText(String(count-1));await expect(box).toBeFocused();expect((await ok(user,'/me/batches/'+ids[0])).batch.participates_in_range_review).toBe(false);});
 await test('J08','Language switch preserves committed search and loaded range',async()=>{await loaded('en');await page.getByRole('button',{name:tr('en','language'),exact:true}).click();await expect(page.locator('h1')).toHaveText(tr('zh','l.library'));await expect(page.getByRole('searchbox')).toHaveValue('LEARN');await expect(page.locator('.library-row')).toHaveCount(21);expect(await page.locator('.library-row').evaluateAll(rows=>rows.map(row=>row.dataset.batch))).toEqual(ids);});
 await test('J09','Library exact content/order and accessibility/runtime',async()=>{await expect(page.locator('.library-stats > div')).toHaveCount(6);expect(await page.locator('.library-stats dt').allTextContents()).toEqual(['generated','words','participating','paused','successes','successfulbatches'].map(k=>tr('zh','l.stat.'+k)));const order=await page.locator('.library-page').evaluate(el=>{const selectors=['.page-head','.library-stats','.library-toolbar','.library-list'];return selectors.map(s=>el.querySelector(s)?.getBoundingClientRect().top)});expect(order.every((v,i)=>i===0||v>=order[i-1])).toBe(true);const AxeBuilder=createRequire(process.cwd()+'/frontend/package.json')('@axe-core/playwright').default;const scan=await new AxeBuilder({page}).include('.library-page').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();dump('library-axe.json',{violations:scan.violations,passes:scan.passes.map(x=>x.id)});expect(scan.violations).toEqual([]);expect(runtime).toEqual([]);});
}catch(e){results.push({id:'SETUP',result:'FAIL',error:String(e)});console.log(String(e));}
finally{dump('library-results.json',{results,samples,runtime,localProviderCalls:calls,realProviderCalls:0});await stop(browser);await new Promise(r=>provider.close(r));console.log(JSON.stringify(results,null,2));if(results.some(x=>x.result==='FAIL'))process.exitCode=1;}
