import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {dirname,resolve,join} from 'node:path';
import {fileURLToPath} from 'node:url';
export const dir=dirname(fileURLToPath(import.meta.url)),root=resolve(dir,'../../../../../..'),origin='http://localhost:6001';
export const names=['wordweave_uat-frontend-1','wordweave_uat-backend-1','wordweave_uat-nginx-1','wordweave_uat-postgres-1'];
export const target='sha256:ab12e7dec0a6a8beb55df2ec6a8174d01d288681215c1108cec997e6f99f8eee',frontend='sha256:fd251e7439aad8e058656e2751ed84f40715fec570a872da53542688a6dd6904',previous='sha256:642ed57ad0ed6c8a13e4bba1101d8b50188e8ea636791583a6ffb5eaa6917aac';
export function docker(args,{input,env=process.env,binary=false}={}){try{const r=execFileSync('docker',args,{cwd:root,encoding:binary?undefined:'utf8',stdio:['pipe','pipe','pipe'],maxBuffer:256*1024*1024,input,env});return binary?r:r.trim();}catch(e){throw Error('Docker operation failed: '+args[0]+' (exit '+e.status+'); command output withheld to protect runtime secrets');}}
export const sql=q=>docker(['exec','-i',names[3],'psql','-U','postgres','-d','wordweave','-XAt','-v','ON_ERROR_STOP=1'],{input:q});
export const sha=b=>createHash('sha256').update(b).digest('hex');
export const hash=p=>sha(readFileSync(p));
export const output=(name,data)=>writeFileSync(join(dir,name),JSON.stringify(data,null,2)+'\n',{flag:'wx'});
export const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
export const inspect=()=>JSON.parse(docker(['inspect',...names]));
export const envOf=c=>Object.fromEntries(c.Config.Env.map(x=>{const i=x.indexOf('=');return [x.slice(0,i),x.slice(i+1)];}).sort(([a],[b])=>a.localeCompare(b)));
export const safe=c=>({name:c.Name,id:c.Id,image:c.Image,started:c.State.StartedAt,status:c.State.Status,health:c.State.Health?.Status,networks:Object.keys(c.NetworkSettings.Networks).sort(),mounts:c.Mounts.map(m=>({type:m.Type,name:m.Name,destination:m.Destination})),readonly:c.HostConfig.ReadonlyRootfs});
const digest=(table,projection='*')=>sql(`SELECT md5(coalesce(string_agg(md5(row_to_json(x)::text),'' ORDER BY md5(row_to_json(x)::text)),'')) FROM (SELECT ${projection} FROM wordweave.${table}) x;`);
export function data(){return {counts:JSON.parse(sql("SELECT json_build_object('accounts',(SELECT count(*) FROM wordweave.accounts),'sessions',(SELECT count(*) FROM wordweave.account_sessions),'batches',(SELECT count(*) FROM wordweave.learning_batches),'models',(SELECT count(*) FROM wordweave.ai_models),'runs',(SELECT count(*) FROM wordweave.generation_runs),'active_runs',(SELECT count(*) FROM wordweave.generation_runs WHERE call_status='active'),'drafts',(SELECT count(*) FROM wordweave.generation_drafts),'claims',(SELECT count(*) FROM wordweave.visitor_claims),'migration_count',(SELECT count(*) FROM wordweave.schema_migrations),'latest_migration',(SELECT max(version) FROM wordweave.schema_migrations));")),digests:{accounts:digest('accounts','id,username,role,group_code,status,ui_locale,quota_reset_at,created_at,updated_at'),...Object.fromEntries(['learning_batches','batch_targets','passage_occurrences','hint_occurrences','review_sessions','review_session_batches','review_session_targets','review_results','generation_runs','generation_run_entries','generation_drafts','visitor_claims','ai_models','entitlement_groups','group_models','group_lengths','schema_migrations','vocabulary_entries','vocabulary_snapshots'].map(t=>[t,digest(t)]))}};}
export const privateData=()=>({passwords:digest('accounts','id,password_hash'),credentials:digest('openrouter_credentials'),sessions:digest('account_sessions','id,account_id,token_hash,created_at,expires_at')});
export const models=()=>JSON.parse(sql("SELECT coalesce(json_agg(json_build_object('id',id,'name',display_name,'provider_model',provider_model_id,'enabled',enabled) ORDER BY id),'[]') FROM wordweave.ai_models;"));
export function protectedHashes(){const allowed=new Set(['report.md','coverage-matrix.md','ai-evaluation.md','uat.md'].map(p=>'.planning/milestones/M001/verification/'+p).concat('.planning/milestones/M001/handoffs/verification.md'));const paths=execFileSync('rg',['--files','--hidden','backend','frontend','nginx','.planning','compose.yaml','README.md'],{cwd:root,encoding:'utf8'}).trim().split('\n').filter(p=>!allowed.has(p)&&!p.includes('/verification/evidence/uat-099/')&&!p.includes('/verification/uat-099-')).sort();return Object.fromEntries(paths.map(p=>[p,hash(join(root,p))]));}
export async function inFlight(){const n=Number(docker(['exec',names[0],'node','-e',`fetch('http://backend:9090/internal/metrics').then(r=>r.text()).then(s=>{const m=s.match(/^wordweave_http_requests_in_flight (\\d+)$/m);if(!m)process.exit(2);console.log(m[1]);}).catch(()=>process.exit(1));`]));if(!Number.isFinite(n))throw Error('In-flight observation unavailable');return n;}
export async function waitHealthy(){for(let i=0;i<60;i++){const c=inspect()[1];if(c.State.Running&&c.State.Health?.Status==='healthy')return;await new Promise(r=>setTimeout(r,500));}throw Error('Candidate did not become healthy within observation window');}
export function assertAuthority(){const s=readFileSync(join(root,'.planning/workflow/state.yaml'),'utf8'),a=s.split('\nai_mapping_uat_preparation_authorization:\n')[1],agents=readFileSync(join(root,'.planning/agt/agents.yaml'),'utf8');if(!/^stage: verification$/m.test(s)||!/^active_agent: qa-quinn$/m.test(s)||!/^active_role: quality\/base$/m.test(s)||!a||!/^  decision_id: TRANSITION-M001-099$/m.test(a)||!/^  status: active$/m.test(a)||!/^  uat_deployment_authorized: true$/m.test(a)||!/^  real_model_calls_authorized: false$/m.test(a))throw Error('UAT099 authority mismatch');if((agents.match(/status: "active"/g)||[]).length!==1||!agents.match(/display_name: "qa-quinn"[\s\S]*?status: "active"/))throw Error('Semantic role not active');if(hash(join(root,'../agt-coding-v2/profiles/consumer-ai-web/PROFILE.yaml'))!=='9d9258ebc8cba13f5df2f8289fa81e973e60af9f10e5ca126fd83482aa0c050f')throw Error('Profile drift');}
