import {createRequire} from 'node:module';import{readFileSync,writeFileSync}from'node:fs';
const {chromium,webkit,expect}=createRequire(process.cwd()+'/frontend/package.json')('@playwright/test');
const out=new URL('./',import.meta.url),origin='http://127.0.0.1:3313',proto='http://127.0.0.1:4183/prototype/';const samples=[];
for(const width of [1440,390]){const b=await(width===390?webkit:chromium).launch(),ctx=await b.newContext({viewport:{width,height:1000},reducedMotion:'reduce'}),p=await ctx.newPage();try{
 await ctx.addCookies([{name:'wordweave_session',value:'admin',url:origin},{name:'wordweave_ui_locale',value:'zh-CN',url:origin}]);
 await p.request.post(origin+'/api/v1/__test/admin-reset');await p.goto(origin+'/admin/plans');await p.waitForFunction(()=>document.documentElement.dataset.appReady==='true');await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:new URL('plans-runtime-'+width+'.png',out).pathname,fullPage:true});
 await p.goto(proto+'?page=plans&lang=zh&role=admin');await expect(p.locator('.admin-options')).toHaveCount(2);await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:new URL('plans-prototype-'+width+'.png',out).pathname,fullPage:true});
 await ctx.addCookies([{name:'wordweave_session',value:'learner',url:origin}]);
 const notice={id:'notice-1',title:'让复习成为完整的一段时光',body_html:'<h2>欢迎回来</h2><p>现在，你可以在提交前回看和修改答案。</p><p><strong>一点点进步，也值得被记住。</strong></p>',content_locale:'zh-CN',remind:true,published_at:'2026-09-17T01:00:00Z',revision:'notice-1'};
 await p.route('**/api/v1/notices**',route=>route.fulfill({json:new URL(route.request().url()).pathname.endsWith('/notices')?{data:{items:[notice]},meta:{request_id:'visual-notices',next_cursor:null,has_more:false}}:{data:{notice},meta:{request_id:'visual-notice'}}}));
 await p.goto(origin+'/notices');await p.waitForFunction(()=>document.documentElement.dataset.appReady==='true');await p.locator('.notice-entry').first().click();await expect(p.locator('#platform-notice')).toBeVisible();await p.locator('#platform-notice').screenshot({path:new URL('notice-runtime-'+width+'.png',out).pathname});
 await p.goto(proto+'?page=notices&lang=zh&role=learner');await p.locator('.notice-entry').first().click();await expect(p.locator('#dialog')).toBeVisible();await p.locator('#dialog').screenshot({path:new URL('notice-prototype-'+width+'.png',out).pathname});
 await ctx.clearCookies();await p.goto(origin+'/login');await p.waitForFunction(()=>document.documentElement.dataset.appReady==='true');await p.locator('input[autocomplete=username]').fill('learner_e2e');await p.locator('input[type=password]').fill('WrongPass123!');await p.locator('form button[type=submit]').click();await expect(p.locator('.app-error')).toBeVisible();await p.locator('.auth-layout').screenshot({path:new URL('auth-error-'+width+'.png',out).pathname});
 samples.push({width,result:'captured',plans:'Actual fixture has one model and default visitor; prototype has different fixture/selected plan. Compare grouping/spacing, not pixel equality.',notice:'Same title and body; actual timestamp includes time, single item1/1 vs prototype pool1/2; both navigation controls visible with correct boundaries.'});
}finally{await b.close();}}
writeFileSync(new URL('visual-inputs.json',out),JSON.stringify({samples,screenshots:10,imagesSentToModel:'record after inspection'},null,2));
